// affaires.js — VOLET COMMERCE (nuit du 09 au 10/10/2026, Ethan : « pour les chargés d'affaires commence à créer tout un volet commercial : création de l'affaire,
// ajout du DCE, dessiner le projet pour la première fois, importer les infos… gros volet commerce, chiffrage, facturation, gestion d'affaire »).
// Sources : Reporting Activité 2026 (états, numéros, clients, chargés d'affaires, situations mensuelles, restant à facturer), Suivi facturation OUEST (Pierre-Antoine :
// envoi situation → validation → préparation facture → validation facture → enregistrement Drive → dépôt / avoir, RG), Tableau de chiffrage V2B O2512-04 (Saint-Lô zone bleue :
// soudures par DN, pouces, cadences, prix du pouce et du manchon, autocontrôle, marge, RCFA par client, chapitres).
// Données : registre kind « affaire », id = numéro (O2512-04). Droits : affaires.view (voir), affaires.edit (créer / modifier). Une affaire peut être liée à des chantiers tracés.
import {regAll,regGet,regSet,regLoad,regLoaded} from './reg.js';
let A=null;
export function initAffaires(api){A=api;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nb=(x,d)=>{x=+x||0;return x.toLocaleString('fr-FR',{maximumFractionDigits:d===undefined?0:d,minimumFractionDigits:d===undefined?0:d});};
const eur=x=>nb(x)+' €';
const dFR=x=>x?new Date(x).toLocaleDateString('fr-FR'):'';
export const ETATS=[['preconsult','Préconsult.','#ececea'],['devis','Devis','#fff4d6'],['perdu','Perdu','#fdeae7'],['a_debuter','À débuter','#e8f0fb'],['en_cours','En cours','#e6f5ec'],['termine','Terminé','#efeafb']];
export const SECTEURS_AFF={ouest:'Ouest',idf:'Île-de-France',sudouest:'Sud-Ouest',sud:'Sud',sudest:'Sud-Est',est:'Est'};
const etat=k=>ETATS.find(e=>e[0]===k)||ETATS[1];
const MOIS=['Janv','Fév','Mars','Avr','Mai','Juin','Juil','Août','Sept','Oct','Nov','Déc'];
export const RCFA={CORIANCE:0.05,ENGIE:0.04,DALKIA:0.035,IDEX:0,EHTP:0.01};
export const rcfaOf=client=>{const c=String(client||'').toUpperCase();for(const k in RCFA)if(c.includes(k))return RCFA[k];return 0;};
/* ── base de prix SCR (tableau de chiffrage V2B, feuille « Prix base fourniture ») ── */
export const BASE={taux:85.32,heures:10,nSoud:3,nManch:1,autocontrole:0.05,ratioManchons:0.85,marge:0.08,dechets:0.10,radioPct:0.05,radioVac:9,radioForfait:1945};
// DN : [pouces, cadence soudure (3 pers / j), cadence manchon (1 pers / j), kg/ml acier, m3/ml (iso 2)]
export const DN_BASE={20:[1,18,18,6.3,0.0094985],25:[1,17,17,6.3,0.0094985],32:[1.25,18,18,6.3,0.012265625],40:[1.5,18,18,6.3,0.012265625],50:[2,16,16,6.3,0.015386],65:[2.5,14,14,7.9,0.020096],80:[3,14,14,9.9,0.025434],100:[4,12,12,14.6,0.039740625],125:[5,12,12,17.7,0.0490625],150:[6,10,10,23,0.061544],200:[8,10,10,34.6,0.098929625],250:[10,8,8,50.4,0.1589625],300:[12,6,6,64.5,0.19625],350:[14,5,5,74.6,0.246176],400:[16,4,4,94.9,0.3115665],450:[18,3,3,109.8,0.3115665],500:[20,3,3,125,0.39571850],600:[24,2,2,150,0.39571850]};
export const DNS=Object.keys(DN_BASE).map(Number);
const radioPU=dn=>dn<=65?90:dn<=200?115:dn<=400?125:145;
export const CHAPITRES=[['amene','Amené – repli – nettoyage'],['conteneur','Conteneur – benne – pelle (rotation, déchets)'],['decharg','Déchargement'],['bardage','Bardage'],['purges','Purges'],['vidanges','Vidanges'],['vannes','Vannes préisolées'],['sst','Vannes SST'],['raccord','Raccordement sur existant'],['ressuage','Ressuage externe'],['us','Contrôles ultrasons'],['radio','Radio (vacations supplémentaires)'],['epreuve','Épreuve hydraulique'],['eau','Eau adoucie'],['boulet','Boulet mousse'],['rincage','Rinçage'],['passivation','Passivation'],['fo_preiso','Fournitures pré-isolées'],['fo_acier','Fournitures acier nu'],['fo_autres','Fournitures autres'],['calo','Calorifuge + peinture + supports'],['aerien','Pose aérien'],['foncage','Fonçage'],['depose','Dépose réseau'],['extrusion','Extrusion'],['etiquettes','Étiquettes'],['nuit','Plus-value nuit'],['doe','DOE / plans iso'],['etudes','Études diverses'],['autre','Autres prestations']];
/* ── calcul d'une zone (lot) : lignes par DN {dn, nb (soudures), ml (tranchée)} ── */
export function calcZone(z,base){base=Object.assign({},BASE,base||{});const out={rows:[],soud:0,manch:0,auto:0,pouces:0,nb:0,ml:0,jS:0,jM:0,t:0,m3:0,radios:0,radioEur:0};
  const cS=base.taux*base.heures*base.nSoud,cM=base.taux*base.heures*base.nManch;
  (z.rows||[]).forEach(r=>{const dn=+r.dn;const b=DN_BASE[dn];if(!b)return;const nbS=+r.nb||0,ml=+r.ml||0;const [pouce,cadS,cadM,kg,m3]=b;const pPouce=cS/(cadS*pouce),pManch=cM/cadM;const pouces=nbS*pouce;const soud=pouces*pPouce;const manch=nbS*pManch*base.ratioManchons;const auto=soud*base.autocontrole;const jS=cadS?nbS/cadS:0,jM=cadM?nbS/cadM:0;const radios=nbS*base.radioPct;
    out.rows.push({dn,nb:nbS,ml,pouce,pouces,pPouce,pManch,soud,manch,auto,jS,jM,t:base.dechets*ml*kg/1000,m3:base.dechets*ml*m3,radios,radioEur:radios*radioPU(dn)});
    out.nb+=nbS;out.ml+=ml;out.pouces+=pouces;out.soud+=soud;out.manch+=manch;out.auto+=auto;out.jS+=jS;out.jM+=jM;out.t+=base.dechets*ml*kg/1000;out.m3+=base.dechets*ml*m3;out.radios+=radios;out.radioEur+=radios*radioPU(dn);});
  out.radioVacs=out.radios?Math.ceil(out.radios/base.radioVac):0;out.radioEur+=out.radioVacs*base.radioForfait;out.achat=out.soud+out.manch+out.auto+out.radioEur;return out;}
export function calcAffaire(a){const ch=a.chiffrage||{};const base=Object.assign({},BASE,ch.base||{});const zones=(ch.zones||[]).map(z=>Object.assign({nom:z.nom},calcZone(z,base)));const chap=(ch.chapitres||[]).reduce((s,c)=>s+(+c.achat||0),0);
  const achat=zones.reduce((s,z)=>s+z.achat,0)+chap;const vente=base.marge<1?achat/(1-base.marge):achat;const rcfaPct=ch.rcfa!==undefined&&ch.rcfa!==null&&ch.rcfa!==''?+ch.rcfa:rcfaOf(a.client);const rcfa=vente*rcfaPct;const total=vente+rcfa;const ml=zones.reduce((s,z)=>s+z.ml,0);
  return {zones,chap,achat,vente,rcfaPct,rcfa,total,ml,parMl:ml?total/ml:0,marge:base.marge,nb:zones.reduce((s,z)=>s+z.nb,0),jS:zones.reduce((s,z)=>s+z.jS,0),jM:zones.reduce((s,z)=>s+z.jM,0),t:zones.reduce((s,z)=>s+z.t,0),m3:zones.reduce((s,z)=>s+z.m3,0)};}
/* ── facturation ── */
export const FACT_ETAPES=[['envoi','Envoi situation'],['valid_sit','Validation situation'],['prep','Préparation facture'],['valid_fac','Validation facture'],['drive','Enregistrement Drive'],['depot','Dépôt de facture'],['avoir','Avoir'],['paye','Payée']];
export function factTotaux(a,year){const f=a.fact||{};const y=year||new Date().getFullYear();const mois=MOIS.map((m,i)=>+f[y+'-'+String(i+1).padStart(2,'0')]||0);const annee=mois.reduce((s,x)=>s+x,0);const avant=Object.keys(f).filter(k=>k<y+'-01').reduce((s,k)=>s+(+f[k]||0),0)+(+a.cumulN1||0);const cumul=avant+annee;const restant=(+a.montant||0)-cumul;return {mois,annee,avant,cumul,restant,y};}
/* ── données ── */
export const affLoad=()=>regLoad(['affaire']);
export const affAll=()=>regAll('affaire').filter(a=>a&&a.num).sort((a,b)=>String(b.num).localeCompare(String(a.num)));
export const affGet=id=>regGet('affaire',id);
export function affSet(id,patch){return regSet('affaire',id,patch);}
export function affNew(num,data){return regSet('affaire',num,Object.assign({num,etat:'preconsult',at:new Date().toISOString(),by:A.userName?A.userName():''},data||{}));}
export const SECT_LETTER={O:'ouest',I:'idf',S:'sud',W:'sudouest',E:'est'};
export const parentNum=num=>{const m=String(num||'').match(/^([A-Z]\d{4}-\d{2})/);return m?m[1]:String(num||'');};
export const isSub=a=>parentNum(a.num)!==String(a.num);
/* ── vues (HTML) : état interne du module ── */
const AS={view:'list',cur:null,tab:'fiche',etat:'',secteur:'',q:'',zone:0,year:new Date().getFullYear(),newOpen:false};
export const affState=()=>AS;
const tag=k=>{const e=etat(k);return `<span class="af-tag" style="background:${e[2]}">${e[1]}</span>`;};
function filtered(me){let L=affAll();if(AS.etat)L=L.filter(a=>a.etat===AS.etat);if(AS.secteur)L=L.filter(a=>(a.secteur||SECT_LETTER[String(a.num)[0]])===AS.secteur);const q=AS.q.trim().toLowerCase();if(q)L=L.filter(a=>[a.num,a.nom,a.client,a.ville,a.charge,a.cdtx].some(x=>String(x||'').toLowerCase().includes(q)));return L;}
export function affListHTML(me,canEdit){const L=filtered(me);const all=affAll();const y=AS.year;
  const enCours=all.filter(a=>a.etat==='en_cours');const ca=all.reduce((s,a)=>s+factTotaux(a,y).annee,0);const restant=all.filter(a=>['en_cours','a_debuter'].includes(a.etat)).reduce((s,a)=>s+Math.max(0,factTotaux(a,y).restant),0);const devis=all.filter(a=>a.etat==='devis').reduce((s,a)=>s+(+a.montant||0),0);
  const row=a=>{const t=factTotaux(a,y);return `<button class="ac-row af-row" data-act="af" data-v="open|${esc(a.num)}"><span class="ic" style="background:${etat(a.etat)[2]};font-size:12px;font-weight:800">${esc(String(a.num).slice(0,1))}</span><span class="tx"><b>${esc(a.num)} · ${esc(a.nom||'')}</b><small>${esc(a.client||'—')} · ${esc(a.ville||'')}${a.charge?' · '+esc(a.charge):''}${isSub(a)?' · <span class="eq-tag">sous-affaire</span>':''}</small><small>${tag(a.etat)} ${a.montant?'<b>'+eur(a.montant)+'</b>':''}${['en_cours','a_debuter','termine'].includes(a.etat)&&a.montant?' · facturé '+eur(t.cumul)+(t.restant>1?' · <span style="color:#7a5200">reste '+eur(t.restant)+'</span>':' · <span style="color:#15673a">soldé</span>'):''}</small></span><span class="chev">›</span></button>`;};
  return `<div class="ac-stats" style="margin-bottom:8px"><div class="ac-stat"><b>${all.length}</b><small>affaires</small></div><div class="ac-stat ok"><b>${enCours.length}</b><small>en cours</small></div><div class="ac-stat"><b>${nb(ca/1000)} k€</b><small>facturé ${y}</small></div><div class="ac-stat ${restant>0?'warn':''}"><b>${nb(restant/1000)} k€</b><small>restant à facturer</small></div><div class="ac-stat"><b>${nb(devis/1000)} k€</b><small>devis en cours</small></div></div>
    <div class="eq-filtres"><button class="chip${AS.etat?'':' active'}" data-act="af" data-v="etat|">Tous</button>${ETATS.map(e=>`<button class="chip${AS.etat===e[0]?' active':''}" data-act="af" data-v="etat|${e[0]}">${e[1]} <span class="eq-badge">${all.filter(a=>a.etat===e[0]).length}</span></button>`).join('')}</div>
    <div class="eq-filtres"><button class="chip${AS.secteur?'':' active'}" data-act="af" data-v="sect|">Tous secteurs</button>${Object.entries(SECTEURS_AFF).filter(([k])=>all.some(a=>(a.secteur||SECT_LETTER[String(a.num)[0]])===k)).map(([k,v])=>`<button class="chip${AS.secteur===k?' active':''}" data-act="af" data-v="sect|${k}">${v}</button>`).join('')}</div>
    <div class="row" style="display:flex;gap:6px;margin:6px 0"><input class="f" data-afin="q" value="${esc(AS.q)}" placeholder="🔍 numéro, nom, client, ville, chargé d'affaires" style="flex:1"><button class="btn" data-act="af" data-v="recap|">📊 Récap CA</button>${canEdit?`<button class="btn primary" data-act="af" data-v="new|">➕ Affaire</button>`:''}</div>
    ${AS.newOpen&&canEdit?affNewFormHTML():''}
    ${L.length?L.map(row).join(''):'<div class="ac-empty">Aucune affaire'+(all.length?' pour ce filtre':' — crée la première, ou passe le SQL d\'import du reporting (sql/affaires_import_2026.sql)')+'.</div>'}
    <div class="hint" style="margin-top:8px">Numéro : lettre du secteur (O Ouest, I IDF, S Sud, W Sud-Ouest) + année-mois + rang, ex. O2512-04 ; une sous-affaire (TS, BDC, avenant, OS) = numéro parent + suffixe (O2512-08-BDC1). Cycle : préconsultation → devis → perdu / à débuter → en cours → terminé.</div>`;}
export function affNextNum(secteur,d){const now=d||new Date();const L={ouest:'O',idf:'I',sud:'S',sudouest:'W',sudest:'S',est:'E'}[secteur||'ouest']||'O';const pre=L+String(now.getFullYear()).slice(2)+String(now.getMonth()+1).padStart(2,'0')+'-';const ranks=affAll().map(a=>String(a.num)).filter(n=>n.startsWith(pre)).map(n=>parseInt(n.slice(pre.length),10)).filter(n=>isFinite(n));return pre+String((ranks.length?Math.max(...ranks):0)+1).padStart(2,'0');}
function affNewFormHTML(){const def=affNextNum('ouest');
  return `<div class="card eq-form"><h3>Nouvelle affaire</h3><div class="row" style="display:flex;gap:6px;flex-wrap:wrap"><div style="flex:0 0 130px"><label class="f">Numéro</label><input class="f" id="afn-num" value="${def}" placeholder="O2610-01"></div><div style="flex:1;min-width:160px"><label class="f">Nom</label><input class="f" id="afn-nom" placeholder="ex. Caen — Folie Couvrechef"></div></div>
    <div class="row" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"><div style="flex:1;min-width:120px"><label class="f">Client</label><input class="f" id="afn-client" placeholder="CORIANCE, ENGIE, DALKIA…"></div><div style="flex:0 0 70px"><label class="f">CP</label><input class="f" id="afn-cp"></div><div style="flex:1;min-width:120px"><label class="f">Ville</label><input class="f" id="afn-ville"></div></div>
    <div class="row" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"><div style="flex:1"><label class="f">Secteur <span class="dim">(propose le numéro)</span></label><select class="f" id="afn-sect" data-afin="newsect">${Object.entries(SECTEURS_AFF).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div style="flex:1"><label class="f">État</label><select class="f" id="afn-etat">${ETATS.map(e=>`<option value="${e[0]}">${e[1]}</option>`).join('')}</select></div><div style="flex:1"><label class="f">Montant devis € HT</label><input class="f" id="afn-montant" type="number" step="0.01"></div></div>
    <div class="eq-acts" style="margin-top:8px"><button class="btn primary" data-act="af" data-v="create|">Créer l'affaire</button><button class="btn" data-act="af" data-v="new|">Annuler</button></div></div>`;}
export function affFicheHTML(me,canEdit,ctx){const a=affGet(AS.cur);if(!a)return '<div class="card"><div class="eq-s">Affaire introuvable.</div></div>';const t=factTotaux(a,AS.year);const C=calcAffaire(a);const ro=!canEdit;
  const subs=affAll().filter(x=>x.num!==a.num&&parentNum(x.num)===a.num);const parent=isSub(a)?affGet(parentNum(a.num)):null;
  const tabs=[['fiche','Fiche'],['dce','DCE · documents'],['chiffrage','Chiffrage'],['fact','Facturation'],['sites','Chantiers liés']];
  const head=`<div class="card af-head"><div class="af-num">${esc(a.num)} ${tag(a.etat)}${parent?` <span class="hint">· sous-affaire de <button class="lnk" data-act="af" data-v="open|${esc(parent.num)}">${esc(parent.num)}</button></span>`:''}</div><h2 class="vt" style="margin:2px 0 4px">${esc(a.nom||'(sans nom)')}</h2><div class="kv" style="font-size:12.5px"><span>${esc(a.client||'client ?')}</span><span>${esc(a.ville||'')}${a.cp?' ('+esc(a.cp)+')':''}</span><span>${esc(SECTEURS_AFF[a.secteur||SECT_LETTER[String(a.num)[0]]]||'')}</span>${a.charge?`<span>CA : ${esc(a.charge)}</span>`:''}${a.cdtx?`<span>CDTX : ${esc(a.cdtx)}</span>`:''}</div>
      <div class="ac-stats" style="margin-top:8px"><div class="ac-stat"><b>${a.montant?eur(a.montant):'—'}</b><small>montant devis HT</small></div><div class="ac-stat ${t.cumul?'ok':''}"><b>${eur(t.cumul)}</b><small>facturé cumulé</small></div><div class="ac-stat ${t.restant>1&&a.montant?'warn':''}"><b>${a.montant?eur(t.restant):'—'}</b><small>restant à facturer</small></div>${C.total?`<div class="ac-stat"><b>${eur(C.total)}</b><small>chiffrage (vente + RCFA)</small></div>`:''}</div></div>
    <div class="eq-filtres">${tabs.map(([k,l])=>`<button class="chip${AS.tab===k?' active':''}" data-act="af" data-v="tab|${k}">${l}</button>`).join('')}</div>`;
  let body='';
  if(AS.tab==='fiche'){const F=(k,l,type,extra)=>`<div><label class="f">${l}</label>${type==='select'?`<select class="f" data-afin="${k}" ${ro?'disabled':''}>${extra}</select>`:type==='textarea'?`<textarea class="f" data-afin="${k}" ${ro?'disabled':''} style="min-height:56px">${esc(a[k]||'')}</textarea>`:`<input class="f" data-afin="${k}" type="${type||'text'}" value="${esc(a[k]||'')}" ${ro?'disabled':''}>`}</div>`;
    body=`<div class="card eq-form"><div class="row af-grid">${F('nom','Nom de l\'affaire')}${F('client','Client')}${F('etat','État','select',ETATS.map(e=>`<option value="${e[0]}"${a.etat===e[0]?' selected':''}>${e[1]}</option>`).join(''))}${F('secteur','Secteur','select',Object.entries(SECTEURS_AFF).map(([k,v])=>`<option value="${k}"${(a.secteur||SECT_LETTER[String(a.num)[0]])===k?' selected':''}>${v}</option>`).join(''))}${F('cp','Code postal')}${F('ville','Ville')}${F('charge','Chargé d\'affaires (initiales)')}${F('cdtx','Conducteur de travaux (initiales)')}${F('dateOuverture','Date d\'ouverture','date')}${F('dateReponse','Date de réponse','date')}${F('montant','Montant du devis € HT','number')}${F('cumulN1','Cumul facturé N-1 € HT','number')}${F('moa','Maître d\'ouvrage')}${F('moe','Maître d\'œuvre / BE')}</div>
      <label class="f" style="margin-top:6px">Commentaires</label><textarea class="f" data-afin="commentaire" ${ro?'disabled':''} style="min-height:64px">${esc(a.commentaire||'')}</textarea>
      ${subs.length?`<div class="eq-lab" style="margin-top:8px">Sous-affaires (TS, BDC, avenants, OS)</div>${subs.map(x=>`<button class="ac-row" data-act="af" data-v="open|${esc(x.num)}" style="min-height:52px;margin-bottom:6px"><span class="tx"><b>${esc(x.num)} · ${esc(x.nom||'')}</b><small>${tag(x.etat)} ${x.montant?eur(x.montant):''}</small></span><span class="chev">›</span></button>`).join('')}`:''}
      ${canEdit?`<div class="eq-acts" style="margin-top:8px"><button class="btn" data-act="af" data-v="sub|">➕ Sous-affaire (TS / BDC / avenant)</button><button class="btn" data-act="af" data-v="del|" style="color:#9b2c22">Supprimer l'affaire</button></div>`:''}
      <div class="hint" style="margin-top:6px">Les champs s'enregistrent à la sortie du champ (serveur si connecté, sinon rejoués). ${a.by?'Créée par '+esc(a.by)+(a.at?' le '+dFR(a.at):''):''}</div></div>`;}
  else if(AS.tab==='dce'){const docs=(a.dce||[]).filter(d=>!d.deleted);
    body=`<div class="card"><h3>Dossier de consultation (DCE) et documents de l'affaire</h3><div class="hint" style="margin:0 0 6px">Pièces du DCE (CCTP, DPGF, plans, mémoire technique attendu…), devis remis, courriers. Un fichier part au serveur (stockage) ; sinon un lien (Drive, SharePoint) suffit.</div>
      ${docs.length?`<table class="rc">${docs.map(d=>`<tr><td>${d.url?`<a href="${esc(d.url)}" target="_blank" rel="noopener" style="color:#1c3d6b;font-weight:600">${esc(d.name)}</a>`:'<b>'+esc(d.name)+'</b>'}${d.note?'<div class="dim" style="font-size:11px">'+esc(d.note)+'</div>':''}</td><td class="dim">${esc(d.cat||'')}</td><td class="dim">${esc(d.by||'')} · ${dFR(d.at)}</td><td>${canEdit?`<button class="btn sm" data-act="af" data-v="dcerm|${esc(d.id)}" style="color:#9b2c22">✕</button>`:''}</td></tr>`).join('')}</table>`:'<div class="eq-s">Aucune pièce pour l\'instant.</div>'}
      ${canEdit?`<div class="eq-form" style="margin-top:8px"><div class="row" style="display:flex;gap:6px;flex-wrap:wrap"><div style="flex:1;min-width:140px"><label class="f">Catégorie</label><select class="f" id="afd-cat"><option>DCE · CCTP / règlement</option><option>DCE · DPGF / BPU</option><option>DCE · plans</option><option>Devis / offre remise</option><option>Mémoire technique</option><option>Courrier / échange client</option><option>Marché / OS / avenant</option><option>Autre</option></select></div><div style="flex:2;min-width:160px"><label class="f">Nom</label><input class="f" id="afd-name" placeholder="ex. DPGF lot 2 V2"></div></div>
        <div class="row" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"><div style="flex:2;min-width:160px"><label class="f">Lien (Drive, SharePoint…)</label><input class="f" id="afd-url" placeholder="https://…"></div><div style="flex:1;min-width:120px"><label class="f">Note</label><input class="f" id="afd-note"></div></div>
        <div class="eq-acts" style="margin-top:8px"><button class="btn primary" data-act="af" data-v="dceadd|">Ajouter la pièce</button><label class="btn">📎 Déposer un fichier<input type="file" id="afd-file" style="display:none" multiple></label></div></div>`:''}</div>`;}
  else if(AS.tab==='chiffrage')body=chiffrageHTML(a,C,canEdit,ctx);
  else if(AS.tab==='fact')body=factHTML(a,t,canEdit);
  else if(AS.tab==='sites'){const sites=(ctx&&ctx.sites)||[];const linked=(a.sites||[]).map(id=>sites.find(s=>s.id===id)||{id,name:id});
    body=`<div class="card"><h3>Chantiers liés</h3><div class="hint" style="margin:0 0 6px">Le projet se dessine une première fois dans le traceur (à partir du DWG du BE ou du plan du calepinage) ; le chantier tracé se lie ici à l'affaire : le chiffrage peut alors se pré-remplir avec les soudures et le linéaire par DN du tracé, et l'exécution (plan, fiches, DOE) suit.</div>
      ${linked.length?linked.map(s=>`<div class="ac-row" style="min-height:52px;margin-bottom:6px"><span class="ic" style="background:#e8f0fb">📍</span><span class="tx"><b>${esc(s.name||s.id)}</b><small>${esc(s.ville||'')}${s.nw?' · '+s.nw+' soudures':''}</small></span><span class="eq-acts" style="margin:0"><button class="btn sm" data-act="opensite" data-v="${esc(s.id)}">Ouvrir</button>${canEdit?`<button class="btn sm" data-act="af" data-v="unlink|${esc(s.id)}" style="color:#9b2c22">✕</button>`:''}</span></div>`).join(''):'<div class="eq-s">Aucun chantier lié.</div>'}
      ${canEdit?`<div class="eq-acts" style="margin-top:8px"><select class="f" id="afs-site" style="flex:1;min-width:160px"><option value="">— lier un chantier existant —</option>${sites.filter(s=>!(a.sites||[]).includes(s.id)).map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.id)}</option>`).join('')}</select><button class="btn" data-act="af" data-v="link|">Lier</button><button class="btn primary" data-act="tabgo" data-v="traceur">✎ Dessiner le projet (traceur)</button></div>`:''}</div>`;}
  return head+body;}
function chiffrageHTML(a,C,canEdit,ctx){const ch=a.chiffrage||{};const zones=ch.zones||[];const base=Object.assign({},BASE,ch.base||{});const zi=Math.min(AS.zone,Math.max(0,zones.length-1));const z=zones[zi];const Z=C.zones[zi];const ro=!canEdit;const sites=(ctx&&ctx.sites)||[];const linked=(a.sites||[]).filter(id=>sites.some(s=>s.id===id));
  const dnRow=(r,i)=>{const R=Z&&Z.rows.find(x=>x.dn===+r.dn);return `<tr><td><select class="f af-dn" data-afz="${i}|dn" ${ro?'disabled':''}>${DNS.map(d=>`<option value="${d}"${+r.dn===d?' selected':''}>DN ${d}</option>`).join('')}</select></td><td><input class="f af-n" type="number" min="0" data-afz="${i}|nb" value="${esc(r.nb||'')}" ${ro?'disabled':''}></td><td><input class="f af-n" type="number" min="0" data-afz="${i}|ml" value="${esc(r.ml||'')}" ${ro?'disabled':''}></td><td class="num">${R?nb(R.pouces):''}</td><td class="num">${R?nb(R.pPouce,2):''}</td><td class="num"><b>${R?nb(R.soud):''}</b></td><td class="num">${R?nb(R.manch):''}</td><td class="num">${R?nb(R.jS,1):''}</td><td>${canEdit?`<button class="btn sm" data-act="af" data-v="dnrm|${i}" style="color:#9b2c22">✕</button>`:''}</td></tr>`;};
  return `<div class="card"><h3>Chiffrage <span class="hint">· méthode SCR (tableau V2B) : soudures par DN × pouces × prix du pouce, manchons, autocontrôle, chapitres, marge, RCFA</span></h3>
    <div class="eq-filtres">${zones.map((zz,i)=>`<button class="chip${i===zi?' active':''}" data-act="af" data-v="zone|${i}">${esc(zz.nom||'Zone '+(i+1))}</button>`).join('')}${canEdit?`<button class="chip" data-act="af" data-v="zoneadd|">➕ zone / lot</button>`:''}</div>
    ${z?`<div class="row" style="display:flex;gap:6px;align-items:end;flex-wrap:wrap;margin:4px 0"><div style="flex:1;min-width:140px"><label class="f">Nom de la zone / du lot</label><input class="f" data-afzn="nom" value="${esc(z.nom||'')}" ${ro?'disabled':''}></div>${canEdit?`<button class="btn" data-act="af" data-v="dnadd|">➕ DN</button>${linked.length?`<select class="f" id="afz-site" style="min-width:150px"><option value="">pré-remplir depuis le tracé…</option>${linked.map(id=>{const s=sites.find(x=>x.id===id);return `<option value="${esc(id)}">${esc(s.name||id)}</option>`;}).join('')}</select><button class="btn" data-act="af" data-v="prefill|">Pré-remplir</button>`:'<span class="hint" style="flex-basis:100%">lie un chantier tracé (onglet Chantiers liés) pour pré-remplir soudures et linéaire par DN</span>'}<button class="btn" data-act="af" data-v="zonerm|" style="color:#9b2c22">✕ zone</button>`:''}</div>
      <div style="overflow:auto"><table class="rc af-tab"><tr><th>DN</th><th>Soudures</th><th>ml tranchée</th><th>Pouces</th><th>€ / pouce</th><th>Soudure €</th><th>Manchons €</th><th>Jours soud.</th><th></th></tr>${(z.rows||[]).map(dnRow).join('')}
        ${Z?`<tr class="tot"><td>Total</td><td class="num">${nb(Z.nb)}</td><td class="num">${nb(Z.ml)}</td><td class="num">${nb(Z.pouces)}</td><td></td><td class="num"><b>${nb(Z.soud)}</b></td><td class="num">${nb(Z.manch)}</td><td class="num">${nb(Z.jS,1)}</td><td></td></tr>`:''}</table></div>
      ${Z?`<div class="eq-s" style="margin-top:6px">Autocontrôle ${nb(base.autocontrole*100)} % : <b>${eur(Z.auto)}</b> · Radios ${nb(base.radioPct*100)} % des soudures = ${nb(Z.radios)} clichés, ${Z.radioVacs} vacation${Z.radioVacs>1?'s':''} : <b>${eur(Z.radioEur)}</b> · Déchets ${nb(Z.t,1)} t / ${nb(Z.m3,1)} m³ · ${nb(Z.jM,1)} jours de manchonnage · <b>Achat zone : ${eur(Z.achat)}</b></div>`:''}`:'<div class="eq-s">Ajoute une zone (lot) pour commencer : chaque zone a sa table par DN.</div>'}</div>
    <div class="card"><h3>Chapitres <span class="hint">· prix d'achat (coût) par poste — comme le Récap Prix</span></h3><div style="overflow:auto"><table class="rc af-tab"><tr><th>Poste</th><th>Achat €</th><th>Vente €</th><th>Observations</th><th></th></tr>${(ch.chapitres||[]).map((c,i)=>`<tr><td><select class="f" data-afc="${i}|k" ${ro?'disabled':''}>${CHAPITRES.map(x=>`<option value="${x[0]}"${c.k===x[0]?' selected':''}>${x[1]}</option>`).join('')}</select></td><td><input class="f af-n" type="number" step="0.01" data-afc="${i}|achat" value="${esc(c.achat||'')}" ${ro?'disabled':''}></td><td class="num">${nb((+c.achat||0)/(1-base.marge))}</td><td><input class="f" data-afc="${i}|obs" value="${esc(c.obs||'')}" ${ro?'disabled':''}></td><td>${canEdit?`<button class="btn sm" data-act="af" data-v="chaprm|${i}" style="color:#9b2c22">✕</button>`:''}</td></tr>`).join('')}</table></div>${canEdit?`<div class="eq-acts" style="margin-top:6px"><button class="btn" data-act="af" data-v="chapadd|">➕ Chapitre</button></div>`:''}</div>
    <div class="card"><h3>Récapitulatif</h3><table class="rc"><tr><td>Soudures + manchons + autocontrôle + radios (zones)</td><td class="num">${eur(C.achat-C.chap)}</td></tr><tr><td>Chapitres</td><td class="num">${eur(C.chap)}</td></tr><tr><td><b>Total prix d'achat</b></td><td class="num"><b>${eur(C.achat)}</b></td></tr><tr><td>Marge ${nb(C.marge*100,1)} % (vente = achat / (1 − marge))</td><td class="num">${eur(C.vente-C.achat)}</td></tr><tr><td><b>Prix de vente</b></td><td class="num"><b>${eur(C.vente)}</b></td></tr><tr><td>RCFA ${nb(C.rcfaPct*100,1)} % ${esc(a.client||'')}</td><td class="num">${eur(C.rcfa)}</td></tr><tr class="tot"><td><b>Total offre € HT</b></td><td class="num"><b>${eur(C.total)}</b></td></tr><tr><td>Info : ${nb(C.nb)} soudures · ${nb(C.ml)} ml · ${nb(C.jS,0)} j soudure · ${nb(C.jM,0)} j manchonnage</td><td class="num">${C.ml?nb(C.parMl,2)+' €/ml':''}</td></tr></table>
      <details style="margin-top:8px"><summary class="eq-s" style="cursor:pointer">⚙ Base de prix (taux horaire, équipes, ratios, marge, RCFA)</summary><div class="row af-grid" style="margin-top:6px">${[['taux','Taux horaire total €/h'],['heures','Heures / jour'],['nSoud','Soudeurs / équipe soudure'],['nManch','Personnes / équipe manchon'],['autocontrole','Autocontrôle (0,05 = 5 %)'],['ratioManchons','Manchons / soudures (0,85)'],['marge','Marge (0,08 = 8 %)'],['dechets','Déchets (0,10 = 10 % du poids)'],['radioPct','Radios (0,05 = 5 % des soudures)'],['radioForfait','Forfait vacation radio €']].map(([k,l])=>`<div><label class="f">${l}</label><input class="f" type="number" step="any" data-afb="${k}" value="${esc(base[k])}" ${ro?'disabled':''}></div>`).join('')}<div><label class="f">RCFA (vide = selon le client)</label><input class="f" type="number" step="any" data-afb="rcfa" value="${esc(ch.rcfa===undefined||ch.rcfa===null?'':ch.rcfa)}" ${ro?'disabled':''} placeholder="${rcfaOf(a.client)}"></div></div>
      <div class="hint" style="margin-top:6px">Prix du pouce = (taux × heures × soudeurs) / (cadence journalière × pouces du DN) ; prix du manchon = (taux × heures × manchonneurs) / cadence ; cadences SCR par DN (3 soudeurs, 1 manchonneur) ; Récap : vente = achat / (1 − marge) comme dans le tableau. Approximation radios : clichés = % des soudures × PU par DN (90 / 115 / 125 / 145 €) + vacations de 9 clichés.</div></details>
      <div class="eq-acts" style="margin-top:8px"><button class="btn" data-act="af" data-v="print|">🖨 Fiche de chiffrage</button></div></div>`;}
function factHTML(a,t,canEdit){const y=t.y;const f=a.fact||{};const sits=(a.situations||[]).filter(s=>!s.deleted).sort((x,yy)=>String(x.mois||'')<String(yy.mois||'')?-1:1);const ro=!canEdit;
  return `<div class="card"><h3>Facturation ${y} <span class="hint">· situations mensuelles (reporting d'activité)</span></h3>
    <div class="eq-filtres"><button class="chip" data-act="af" data-v="year|${y-1}">‹ ${y-1}</button><button class="chip active">${y}</button><button class="chip" data-act="af" data-v="year|${y+1}">${y+1} ›</button></div>
    <div style="overflow:auto"><table class="rc af-tab"><tr>${MOIS.map(m=>`<th>${m}</th>`).join('')}<th>Année</th></tr><tr>${MOIS.map((m,i)=>`<td><input class="f af-n" type="number" step="0.01" data-aff="${y}-${String(i+1).padStart(2,'0')}" value="${esc(f[y+'-'+String(i+1).padStart(2,'0')]||'')}" ${ro?'disabled':''}></td>`).join('')}<td class="num"><b>${eur(t.annee)}</b></td></tr></table></div>
    <div class="ac-stats" style="margin-top:8px"><div class="ac-stat"><b>${eur(t.avant)}</b><small>facturé avant ${y}</small></div><div class="ac-stat ok"><b>${eur(t.cumul)}</b><small>cumul situations</small></div><div class="ac-stat ${t.restant>1?'warn':''}"><b>${eur(t.restant)}</b><small>restant à facturer</small></div><div class="ac-stat"><b>${a.montant?nb(100*t.cumul/(+a.montant||1)):'—'} %</b><small>avancement facturé</small></div></div></div>
    <div class="card"><h3>Situations et factures <span class="hint">· suivi Pierre-Antoine</span></h3>
      ${sits.length?`<div style="overflow:auto"><table class="rc af-tab"><tr><th>Mois</th><th>N° situation</th><th>N° facture</th><th>Montant € HT</th><th>RG</th><th>Étape</th><th>Envoi</th><th>Commentaire</th><th></th></tr>${sits.map(s=>`<tr><td><input class="f" type="month" data-afs="${s.id}|mois" value="${esc(s.mois||'')}" ${ro?'disabled':''}></td><td><input class="f" data-afs="${s.id}|sit" value="${esc(s.sit||'')}" ${ro?'disabled':''}></td><td><input class="f" data-afs="${s.id}|num" value="${esc(s.num||'')}" placeholder="FAC-000…" ${ro?'disabled':''}></td><td><input class="f af-n" type="number" step="0.01" data-afs="${s.id}|montant" value="${esc(s.montant||'')}" ${ro?'disabled':''}></td><td><input class="f" data-afs="${s.id}|rg" value="${esc(s.rg||'')}" placeholder="5 % / OK" style="width:70px" ${ro?'disabled':''}></td><td><select class="f" data-afs="${s.id}|etape" ${ro?'disabled':''}>${FACT_ETAPES.map(e=>`<option value="${e[0]}"${s.etape===e[0]?' selected':''}>${e[1]}</option>`).join('')}</select></td><td><input class="f" data-afs="${s.id}|envoi" value="${esc(s.envoi||'')}" placeholder="MLB, mail, factor…" ${ro?'disabled':''}></td><td><input class="f" data-afs="${s.id}|com" value="${esc(s.com||'')}" ${ro?'disabled':''}></td><td>${canEdit?`<button class="btn sm" data-act="af" data-v="sitrm|${esc(s.id)}" style="color:#9b2c22">✕</button>`:''}</td></tr>`).join('')}</table></div>`:'<div class="eq-s">Aucune situation saisie.</div>'}
      ${canEdit?`<div class="eq-acts" style="margin-top:6px"><button class="btn primary" data-act="af" data-v="sitadd|">➕ Situation / facture</button></div>`:''}
      <div class="hint" style="margin-top:6px">Étapes du suivi de facturation : envoi de la situation → validation → préparation de la facture → validation → enregistrement Drive → dépôt (ou avoir) → payée. La RG (retenue de garantie, 5 %) se note par situation. Le montant d'une situation déposée alimente le mois correspondant si la case du mois est vide.</div></div>`;}
/* ── fiche de chiffrage imprimable ── */
export function chiffragePrintHTML(a){const C=calcAffaire(a);const base=Object.assign({},BASE,(a.chiffrage||{}).base||{});
  const zones=C.zones.map((Z,i)=>`<h2>${esc(Z.nom||'Zone '+(i+1))}</h2><table class="em"><tr><th>DN</th><th>Soudures</th><th>ml</th><th>Pouces</th><th>€/pouce</th><th>Soudure</th><th>Manchons</th><th>Autocontrôle</th><th>Jours soud.</th><th>Jours manch.</th></tr>${Z.rows.map(r=>`<tr><td>DN ${r.dn}</td><td>${nb(r.nb)}</td><td>${nb(r.ml)}</td><td>${nb(r.pouces)}</td><td>${nb(r.pPouce,2)}</td><td>${nb(r.soud)}</td><td>${nb(r.manch)}</td><td>${nb(r.auto)}</td><td>${nb(r.jS,1)}</td><td>${nb(r.jM,1)}</td></tr>`).join('')}<tr><td><b>Total</b></td><td><b>${nb(Z.nb)}</b></td><td><b>${nb(Z.ml)}</b></td><td>${nb(Z.pouces)}</td><td></td><td><b>${nb(Z.soud)}</b></td><td><b>${nb(Z.manch)}</b></td><td>${nb(Z.auto)}</td><td>${nb(Z.jS,1)}</td><td>${nb(Z.jM,1)}</td></tr></table><p>Radios : ${nb(Z.radios)} clichés, ${Z.radioVacs} vacations → ${eur(Z.radioEur)} · Déchets ${nb(Z.t,1)} t / ${nb(Z.m3,1)} m³ · <b>Achat zone ${eur(Z.achat)}</b></p>`).join('');
  const chap=((a.chiffrage||{}).chapitres||[]).map(c=>`<tr><td>${esc((CHAPITRES.find(x=>x[0]===c.k)||[])[1]||c.k)}</td><td>${nb(c.achat)}</td><td>${nb((+c.achat||0)/(1-base.marge))}</td><td>${esc(c.obs||'')}</td></tr>`).join('');
  return A.docHTML({title:'Chiffrage — '+(a.nom||a.num),kicker:'Commerce · fiche de chiffrage · '+esc(a.num),sub:esc(a.client||'')+(a.ville?' · '+esc(a.ville):''),meta:[['Affaire',esc(a.num)],['État',etat(a.etat)[1]],['Total offre HT',eur(C.total)],['€ / ml',C.ml?nb(C.parMl,2):'—']],
    body:zones+`<h2>Chapitres</h2><table class="em"><tr><th>Poste</th><th>Achat €</th><th>Vente €</th><th>Observations</th></tr>${chap||'<tr><td colspan="4">—</td></tr>'}</table><h2>Récapitulatif</h2><table class="em"><tr><td>Total prix d'achat</td><td>${eur(C.achat)}</td></tr><tr><td>Marge ${nb(C.marge*100,1)} %</td><td>${eur(C.vente-C.achat)}</td></tr><tr><td>Prix de vente</td><td>${eur(C.vente)}</td></tr><tr><td>RCFA ${nb(C.rcfaPct*100,1)} %</td><td>${eur(C.rcfa)}</td></tr><tr><td><b>Total offre € HT</b></td><td><b>${eur(C.total)}</b></td></tr></table><div class="card soft">Base : taux ${nb(base.taux,2)} €/h · ${base.heures} h/j · ${base.nSoud} soudeurs · ${base.nManch} manchonneur · autocontrôle ${nb(base.autocontrole*100)} % · manchons ${nb(base.ratioManchons*100)} % des soudures · déchets ${nb(base.dechets*100)} %.</div>`,css:'table.em td{text-align:right}table.em td:first-child{text-align:left}',footLeft:'SCR · commerce'});}
/* ── actions (data-act="af" data-v="k|arg") ── */
export function affAct(v,el,ctx){const [k,arg]=String(v).split('|');const a=AS.cur?affGet(AS.cur):null;const canEdit=ctx.canEdit;const say=t=>A.toast&&A.toast(t);
  const upd=patch=>{if(!a)return;affSet(a.num,patch);};
  switch(k){
    case 'etat':AS.etat=arg;break;case 'sect':AS.secteur=arg;break;case 'year':AS.year=+arg;break;case 'tab':AS.tab=arg;break;case 'zone':AS.zone=+arg;break;
    case 'open':AS.cur=arg;AS.view='fiche';AS.tab='fiche';AS.zone=0;break;
    case 'back':AS.view='list';AS.cur=null;break;case 'recap':AS.view='recap';break;
    case 'csv':{const csv=affCSV();const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const u=URL.createObjectURL(blob);const el2=document.createElement('a');el2.href=u;el2.download='affaires_'+AS.year+'.csv';document.body.appendChild(el2);el2.click();el2.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);return;}
    case 'new':if(!canEdit)return;AS.newOpen=!AS.newOpen;break;
    case 'create':{if(!canEdit)return;const g=id=>(document.getElementById(id)||{}).value||'';const num=g('afn-num').trim().toUpperCase();if(!/^[A-Z]\d{4}-\d{2}/.test(num)){say('Numéro attendu : lettre + AAMM-rang, ex. O2610-01');return;}if(affGet(num)){say('Ce numéro existe déjà');return;}
      affNew(num,{nom:g('afn-nom').trim(),client:g('afn-client').trim(),cp:g('afn-cp').trim(),ville:g('afn-ville').trim(),secteur:g('afn-sect'),etat:g('afn-etat'),montant:g('afn-montant')?+g('afn-montant'):null,dateOuverture:new Date().toISOString().slice(0,10)});AS.newOpen=false;AS.cur=num;AS.view='fiche';AS.tab='fiche';say('Affaire '+num+' créée');break;}
    case 'sub':{if(!canEdit||!a)return;const suf=prompt('Suffixe de la sous-affaire (TS1, BDC1, AV1, OS4…)','TS1');if(!suf)return;const num=a.num+'-'+suf.trim().toUpperCase().replace(/[^A-Z0-9]/g,'');if(affGet(num)){say('Existe déjà');return;}affNew(num,{nom:(a.nom||'')+' : '+suf,client:a.client,cp:a.cp,ville:a.ville,secteur:a.secteur,charge:a.charge,cdtx:a.cdtx,etat:'devis'});AS.cur=num;break;}
    case 'del':{if(!canEdit||!a)return;if(!confirm('Supprimer l\'affaire '+a.num+' ?'))return;regSet('affaire',a.num,{deleted:true,deletedAt:new Date().toISOString()});AS.view='list';AS.cur=null;break;}
    case 'dceadd':{if(!canEdit||!a)return;const g=id=>(document.getElementById(id)||{}).value||'';const name=g('afd-name').trim();if(!name){say('Le nom de la pièce');return;}const d={id:'D'+Date.now().toString(36),cat:g('afd-cat'),name,url:g('afd-url').trim()||undefined,note:g('afd-note').trim(),by:A.userName(),at:new Date().toISOString()};upd({dce:(a.dce||[]).concat([d])});break;}
    case 'dcerm':{if(!canEdit||!a)return;upd({dce:(a.dce||[]).filter(d=>d.id!==arg)});break;}
    case 'zoneadd':{if(!canEdit||!a)return;const ch=Object.assign({zones:[],chapitres:[]},a.chiffrage||{});ch.zones=(ch.zones||[]).concat([{nom:'Zone '+((ch.zones||[]).length+1),rows:[{dn:100,nb:'',ml:''}]}]);upd({chiffrage:ch});AS.zone=ch.zones.length-1;break;}
    case 'zonerm':{if(!canEdit||!a)return;const ch=Object.assign({},a.chiffrage||{});if(!confirm('Retirer cette zone du chiffrage ?'))return;ch.zones=(ch.zones||[]).filter((z,i)=>i!==AS.zone);upd({chiffrage:ch});AS.zone=0;break;}
    case 'dnadd':{if(!canEdit||!a)return;const ch=Object.assign({},a.chiffrage||{});const z=(ch.zones||[])[AS.zone];if(!z)return;z.rows=(z.rows||[]).concat([{dn:DNS.find(d=>!(z.rows||[]).some(r=>+r.dn===d))||100,nb:'',ml:''}]);upd({chiffrage:ch});break;}
    case 'dnrm':{if(!canEdit||!a)return;const ch=Object.assign({},a.chiffrage||{});const z=(ch.zones||[])[AS.zone];if(!z)return;z.rows=(z.rows||[]).filter((r,i)=>i!==+arg);upd({chiffrage:ch});break;}
    case 'prefill':{if(!canEdit||!a)return;const sel=document.getElementById('afz-site');const id=sel&&sel.value;if(!id){say('Choisis le chantier tracé');return;}const agg=ctx.traceAgg?ctx.traceAgg(id):null;if(!agg||!Object.keys(agg).length){say('Rien à lire dans ce tracé sur cet appareil (ouvre-le une fois)');return;}
      const ch=Object.assign({},a.chiffrage||{});const z=(ch.zones||[])[AS.zone];if(!z)return;z.rows=Object.keys(agg).map(Number).sort((x,y)=>x-y).map(dn=>({dn,nb:agg[dn].nb,ml:Math.round(agg[dn].ml)}));z.source=id;upd({chiffrage:ch});say('Zone pré-remplie depuis le tracé : '+z.rows.length+' DN');break;}
    case 'chapadd':{if(!canEdit||!a)return;const ch=Object.assign({zones:[],chapitres:[]},a.chiffrage||{});ch.chapitres=(ch.chapitres||[]).concat([{k:'conteneur',achat:'',obs:''}]);upd({chiffrage:ch});break;}
    case 'chaprm':{if(!canEdit||!a)return;const ch=Object.assign({},a.chiffrage||{});ch.chapitres=(ch.chapitres||[]).filter((c,i)=>i!==+arg);upd({chiffrage:ch});break;}
    case 'sitadd':{if(!canEdit||!a)return;const now=new Date();upd({situations:(a.situations||[]).concat([{id:'S'+Date.now().toString(36),mois:now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0'),etape:'envoi',montant:'',sit:String((a.situations||[]).length+1)}])});break;}
    case 'sitrm':{if(!canEdit||!a)return;upd({situations:(a.situations||[]).filter(s=>s.id!==arg)});break;}
    case 'link':{if(!canEdit||!a)return;const sel=document.getElementById('afs-site');const id=sel&&sel.value;if(!id)return;upd({sites:(a.sites||[]).concat([id])});break;}
    case 'unlink':{if(!canEdit||!a)return;upd({sites:(a.sites||[]).filter(x=>x!==arg)});break;}
    case 'print':{if(!a)return;const w=window.open('','_blank');if(!w){say('Autorise la fenêtre pop-up pour imprimer');return;}w.document.write(chiffragePrintHTML(a));w.document.close();return;}
    default:return;}
  if(ctx.render)ctx.render();}
/* ── saisie des champs (data-afin, data-afz, data-afc, data-afb, data-aff, data-afs, data-afzn) ── */
export function affInput(el,ctx){const d=el.dataset;if(d.afin==='q'){AS.q=el.value;if(ctx.render)ctx.render();return true;}if(d.afin==='newsect'){const n=document.getElementById('afn-num');if(n)n.value=affNextNum(el.value);return true;}
  if(!ctx.canEdit){if(A.toast)A.toast('Lecture seule : droit « Affaires : créer et modifier » nécessaire');return true;}
  const a=AS.cur?affGet(AS.cur):null;if(!a)return false;const num=v=>v===''?null:(isFinite(+v)?+v:v);
  if(d.afin){affSet(a.num,{[d.afin]:['montant','cumulN1'].includes(d.afin)?num(el.value):el.value});return true;}
  if(d.afzn){const ch=Object.assign({},a.chiffrage||{});const z=(ch.zones||[])[AS.zone];if(z){z.nom=el.value;affSet(a.num,{chiffrage:ch});}return true;}
  if(d.afz){const [i,k]=d.afz.split('|');const ch=Object.assign({},a.chiffrage||{});const z=(ch.zones||[])[AS.zone];if(z&&z.rows[+i]){z.rows[+i][k]=k==='dn'?+el.value:num(el.value);affSet(a.num,{chiffrage:ch});}if(ctx.render)ctx.render();return true;}
  if(d.afc){const [i,k]=d.afc.split('|');const ch=Object.assign({},a.chiffrage||{});const c=(ch.chapitres||[])[+i];if(c){c[k]=k==='achat'?num(el.value):el.value;affSet(a.num,{chiffrage:ch});}if(ctx.render)ctx.render();return true;}
  if(d.afb){const ch=Object.assign({},a.chiffrage||{});if(d.afb==='rcfa'){ch.rcfa=el.value===''?null:+el.value;}else{ch.base=Object.assign({},ch.base||{});ch.base[d.afb]=+el.value;}affSet(a.num,{chiffrage:ch});if(ctx.render)ctx.render();return true;}
  if(d.aff){const f=Object.assign({},a.fact||{});if(el.value==='')delete f[d.aff];else f[d.aff]=+el.value;affSet(a.num,{fact:f});if(ctx.render)ctx.render();return true;}
  if(d.afs){const [id,k]=d.afs.split('|');const sits=(a.situations||[]).map(s=>s.id===id?Object.assign({},s,{[k]:k==='montant'?num(el.value):el.value}):s);const patch={situations:sits};const s=sits.find(x=>x.id===id);
    if(s&&(k==='etape'||k==='montant')&&s.etape==='depot'&&s.mois&&s.montant){const f=Object.assign({},a.fact||{});if(f[s.mois]===undefined||f[s.mois]===''||f[s.mois]===null){f[s.mois]=+s.montant;patch.fact=f;}} /* facture déposée → alimente le mois si vide */
    affSet(a.num,patch);if(ctx.render)ctx.render();return true;}
  return false;}
export function affRecapHTML(){const y=AS.year;const all=affAll();const sects=Object.keys(SECTEURS_AFF).filter(k=>all.some(a=>(a.secteur||SECT_LETTER[String(a.num)[0]])===k));const M=MOIS.map((m,i)=>y+'-'+String(i+1).padStart(2,'0'));
  const cell=(k,mo)=>all.filter(a=>(a.secteur||SECT_LETTER[String(a.num)[0]])===k).reduce((s,a)=>s+(+(a.fact||{})[mo]||0),0);const totS={};sects.forEach(k=>totS[k]=M.reduce((s,mo)=>s+cell(k,mo),0));const tot=M.map(mo=>sects.reduce((s,k)=>s+cell(k,mo),0));const T=tot.reduce((s,x)=>s+x,0);
  const restant={};sects.forEach(k=>restant[k]=all.filter(a=>(a.secteur||SECT_LETTER[String(a.num)[0]])===k&&['en_cours','a_debuter'].includes(a.etat)).reduce((s,a)=>s+Math.max(0,factTotaux(a,y).restant),0));const devis={};sects.forEach(k=>devis[k]=all.filter(a=>(a.secteur||SECT_LETTER[String(a.num)[0]])===k&&['devis','preconsult'].includes(a.etat)).reduce((s,a)=>s+(+a.montant||0),0));
  return `<div class="card"><h3>CA mensuel ${y} par secteur <span class="hint">· situations facturées (reporting)</span></h3><div class="eq-filtres"><button class="chip" data-act="af" data-v="year|${y-1}">‹ ${y-1}</button><button class="chip active">${y}</button><button class="chip" data-act="af" data-v="year|${y+1}">${y+1} ›</button></div>
    <div style="overflow:auto"><table class="rc af-tab"><tr><th>Mois</th>${sects.map(k=>`<th>${esc(SECTEURS_AFF[k])}</th>`).join('')}<th>Total SCR</th></tr>${M.map((mo,i)=>`<tr><td>${MOIS[i]}</td>${sects.map(k=>`<td class="num">${cell(k,mo)?nb(cell(k,mo)/1000)+' k€':'—'}</td>`).join('')}<td class="num"><b>${tot[i]?nb(tot[i]/1000)+' k€':'—'}</b></td></tr>`).join('')}<tr class="tot"><td>Total ${y}</td>${sects.map(k=>`<td class="num">${nb(totS[k]/1000)} k€</td>`).join('')}<td class="num">${nb(T/1000)} k€</td></tr><tr><td>Part</td>${sects.map(k=>`<td class="num">${T?nb(100*totS[k]/T):0} %</td>`).join('')}<td></td></tr><tr><td>Restant à facturer</td>${sects.map(k=>`<td class="num">${nb(restant[k]/1000)} k€</td>`).join('')}<td class="num"><b>${nb(Object.values(restant).reduce((s,x)=>s+x,0)/1000)} k€</b></td></tr><tr><td>Devis / préconsult. en cours</td>${sects.map(k=>`<td class="num">${nb(devis[k]/1000)} k€</td>`).join('')}<td class="num">${nb(Object.values(devis).reduce((s,x)=>s+x,0)/1000)} k€</td></tr></table></div>
    <div class="eq-acts" style="margin-top:8px"><button class="btn" data-act="af" data-v="csv|">⬇ Export CSV des affaires (Excel)</button></div><div class="hint" style="margin-top:4px">Même logique que l'onglet Récap du reporting : CA = situations mensuelles saisies sur chaque affaire.</div></div>`;}
export function affCSV(){const all=affAll();const y=AS.year;const H=['Numéro','Nom','État','Secteur','Client','CP','Ville','Chargé d\'affaires','CDTX','Montant devis HT','Cumul N-1','Cumul situations','Restant à facturer'].concat(MOIS.map(m=>m+' '+y)).concat(['Commentaires']);
  const E=ETATS.reduce((o,e)=>{o[e[0]]=e[1];return o;},{});const q=v=>'"'+String(v===undefined||v===null?'':v).replace(/"/g,'""')+'"';
  const rows=all.map(a=>{const t=factTotaux(a,y);return [a.num,a.nom,E[a.etat]||a.etat,SECTEURS_AFF[a.secteur||SECT_LETTER[String(a.num)[0]]]||'',a.client,a.cp,a.ville,a.charge,a.cdtx,a.montant,a.cumulN1,t.cumul,t.restant].concat(t.mois).concat([a.commentaire]).map(v=>typeof v==='number'?String(v).replace('.',','):q(v)).join(';');});
  return '\ufeff'+H.map(q).join(';')+'\n'+rows.join('\n');}
export function affView(me,ctx){const canEdit=ctx.canEdit;if(AS.view==='recap')return `<button class="ac-back" data-act="af" data-v="back|">‹ Affaires</button><h2 class="vt">Récap commerce <span class="hint">· CA mensuel par secteur</span></h2>`+affRecapHTML();return AS.view==='fiche'&&AS.cur?`<button class="ac-back" data-act="af" data-v="back|">‹ Affaires</button>`+affFicheHTML(me,canEdit,ctx):`<h2 class="vt">Affaires <span class="hint">· commerce · chiffrage · facturation</span></h2>`+affListHTML(me,canEdit);}
export const affReady=()=>regLoaded('affaire');
