// commandes.js — BONS DE COMMANDE & DÉBOURS (nuit du 09 au 10/10/2026 — « Exploitation : soit faire des bons de commande, débours », vision d'Ethan du 09/10).
// Bon de commande (registre kind « commande », id = BC-AAMM-nn) : chantier, affaire, fournisseur, objet, lignes (désignation, quantité, unité, PU), total HT, livraison
// prévue, état brouillon → envoyée → reçue → facturée ; bon imprimable (charte SCR). Encadrement / bureau.
// Débours = note de frais (kind « debours », id = <clé personne>|<horodatage>) : date, chantier, nature, montant TTC, payé par, moyen, justificatif (lien), état
// saisi → validé / refusé → remboursé. Chacun saisit les siens (Mon espace → Mes débours) ; conducteur / bureau valident (Exploitation).
import {regAll,regGet,regSet,regLoad,regLoaded} from './reg.js';
let A=null;
export function initCommandes(api){A=api;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nb=(x,d)=>(+x||0).toLocaleString('fr-FR',{minimumFractionDigits:d===undefined?2:d,maximumFractionDigits:d===undefined?2:d});
const eur=x=>nb(x)+' €';
const dFR=x=>x?new Date(x).toLocaleDateString('fr-FR'):'';
export const BC_ETATS=[['brouillon','Brouillon','#ececea'],['envoyee','Envoyée','#fff4d6'],['recue','Reçue','#e6f5ec'],['facturee','Facturée','#efeafb'],['annulee','Annulée','#fdeae7']];
export const NATURES=[['carburant','Carburant'],['peage','Péage / parking'],['hebergement','Hébergement'],['repas','Repas'],['fourniture','Fourniture / consommable'],['outillage','Outillage / location'],['transport','Transport / train'],['autre','Autre']];
export const DB_ETATS=[['saisi','Saisi','#fff4d6'],['valide','Validé','#e6f5ec'],['refuse','Refusé','#fdeae7'],['rembourse','Remboursé','#efeafb']];
export const cmdLoad=()=>regLoad(['commande','debours']);
export const cmdAll=()=>regAll('commande').filter(c=>c&&c.num).sort((a,b)=>String(b.at||'').localeCompare(String(a.at||'')));
export const dbAll=()=>regAll('debours').filter(d=>d&&d.date).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.at||'').localeCompare(String(a.at||'')));
export const dbDe=key=>dbAll().filter(d=>d.key===key);
export function cmdNextNum(d){const now=d||new Date();const pre='BC-'+String(now.getFullYear()).slice(2)+String(now.getMonth()+1).padStart(2,'0')+'-';const r=cmdAll().map(c=>String(c.num)).filter(n=>n.startsWith(pre)).map(n=>parseInt(n.slice(pre.length),10)).filter(n=>isFinite(n));return pre+String((r.length?Math.max(...r):0)+1).padStart(2,'0');}
export const cmdTotal=c=>(c.lignes||[]).reduce((s,l)=>s+(+l.qte||0)*(+l.pu||0),0);
const tag=(k,T)=>{const e=T.find(x=>x[0]===k)||T[0];return `<span class="af-tag" style="background:${e[2]}">${e[1]}</span>`;};
const CS={tab:'cmd',cur:null,etat:'',site:''};
export const cmdState=()=>CS;
/* ── bons de commande ── */
export function cmdListHTML(ctx){const all=cmdAll();let L=all;if(CS.etat)L=L.filter(c=>c.etat===CS.etat);if(CS.site)L=L.filter(c=>c.site===CS.site);const sites=ctx.sites||[];const sname=id=>(sites.find(s=>s.id===id)||{}).name||id||'—';
  const row=c=>`<button class="ac-row" data-act="cmd" data-v="open|${esc(c.num)}"><span class="ic" style="background:${(BC_ETATS.find(e=>e[0]===c.etat)||BC_ETATS[0])[2]}">🧾</span><span class="tx"><b>${esc(c.num)} · ${esc(c.fournisseur||'fournisseur ?')}</b><small>${esc(c.objet||'')} · ${esc(sname(c.site))}${c.livraison?' · livraison '+dFR(c.livraison):''}</small><small>${tag(c.etat,BC_ETATS)} <b>${eur(cmdTotal(c))} HT</b> · ${esc(c.by||'')} · ${dFR(c.at)}</small></span><span class="chev">›</span></button>`;
  return `<div class="eq-filtres"><button class="chip${CS.etat?'':' active'}" data-act="cmd" data-v="etat|">Tous</button>${BC_ETATS.map(e=>`<button class="chip${CS.etat===e[0]?' active':''}" data-act="cmd" data-v="etat|${e[0]}">${e[1]} <span class="eq-badge">${all.filter(c=>c.etat===e[0]).length}</span></button>`).join('')}</div>
    ${ctx.canEdit?`<div class="eq-acts" style="margin:4px 0 8px"><button class="btn primary" data-act="cmd" data-v="new|">➕ Bon de commande</button></div>`:''}
    ${L.length?L.map(row).join(''):'<div class="ac-empty">Aucun bon de commande.</div>'}`;}
export function cmdFicheHTML(ctx){const c=regGet('commande',CS.cur);if(!c)return '<div class="card"><div class="eq-s">Introuvable.</div></div>';const ro=!ctx.canEdit;const sites=ctx.sites||[];const affs=ctx.affaires||[];
  const F=(k,l,type,extra)=>`<div><label class="f">${l}</label>${type==='select'?`<select class="f" data-cmdf="${k}" ${ro?'disabled':''}>${extra}</select>`:`<input class="f" data-cmdf="${k}" type="${type||'text'}" value="${esc(c[k]||'')}" ${ro?'disabled':''}>`}</div>`;
  return `<div class="card af-head"><div class="af-num">${esc(c.num)} ${tag(c.etat,BC_ETATS)}</div><h2 class="vt" style="margin:2px 0 4px">${esc(c.fournisseur||'Bon de commande')} <span class="hint">· ${eur(cmdTotal(c))} HT</span></h2><div class="kv" style="font-size:12.5px"><span>${esc((sites.find(s=>s.id===c.site)||{}).name||'chantier ?')}</span>${c.affaire?`<span>affaire ${esc(c.affaire)}</span>`:''}<span>${esc(c.by||'')} · ${dFR(c.at)}</span></div></div>
    <div class="card eq-form"><div class="row af-grid">${F('fournisseur','Fournisseur')}${F('objet','Objet')}${F('etat','État','select',BC_ETATS.map(e=>`<option value="${e[0]}"${c.etat===e[0]?' selected':''}>${e[1]}</option>`).join(''))}${F('site','Chantier','select','<option value="">—</option>'+sites.map(s=>`<option value="${esc(s.id)}"${c.site===s.id?' selected':''}>${esc(s.name||s.id)}</option>`).join(''))}${F('affaire','Affaire','select','<option value="">—</option>'+affs.map(a=>`<option value="${esc(a.num)}"${c.affaire===a.num?' selected':''}>${esc(a.num)} · ${esc(a.nom||'')}</option>`).join(''))}${F('livraison','Livraison prévue','date')}${F('refFournisseur','Référence fournisseur / devis')}${F('contact','Contact fournisseur')}</div>
      <label class="f" style="margin-top:6px">Lignes</label><div style="overflow:auto"><table class="rc af-tab"><tr><th>Désignation</th><th>Qté</th><th>Unité</th><th>PU HT</th><th>Total</th><th></th></tr>${(c.lignes||[]).map((l,i)=>`<tr><td><input class="f" data-cmdl="${i}|designation" value="${esc(l.designation||'')}" ${ro?'disabled':''} style="min-width:160px"></td><td><input class="f af-n" type="number" step="any" data-cmdl="${i}|qte" value="${esc(l.qte||'')}" ${ro?'disabled':''}></td><td><input class="f" data-cmdl="${i}|unite" value="${esc(l.unite||'')}" ${ro?'disabled':''} style="width:60px"></td><td><input class="f af-n" type="number" step="0.01" data-cmdl="${i}|pu" value="${esc(l.pu||'')}" ${ro?'disabled':''}></td><td class="num">${nb((+l.qte||0)*(+l.pu||0))}</td><td>${ctx.canEdit?`<button class="btn sm" data-act="cmd" data-v="lrm|${i}" style="color:#9b2c22">✕</button>`:''}</td></tr>`).join('')}<tr class="tot"><td colspan="4">Total HT</td><td class="num">${nb(cmdTotal(c))}</td><td></td></tr></table></div>
      ${ctx.canEdit?`<div class="eq-acts" style="margin-top:6px"><button class="btn" data-act="cmd" data-v="ladd|">➕ Ligne</button></div>`:''}
      <label class="f" style="margin-top:6px">Notes</label><textarea class="f" data-cmdf="notes" ${ro?'disabled':''} style="min-height:48px">${esc(c.notes||'')}</textarea>
      <div class="eq-acts" style="margin-top:8px"><button class="btn" data-act="cmd" data-v="print|">🖨 Bon de commande</button>${ctx.canEdit?`<button class="btn" data-act="cmd" data-v="del|" style="color:#9b2c22">Supprimer</button>`:''}</div></div>`;}
export function cmdPrintHTML(c,sites){const s=(sites||[]).find(x=>x.id===c.site)||{};return A.docHTML({title:'Bon de commande '+c.num,kicker:'Achats · bon de commande',sub:esc(c.fournisseur||''),meta:[['Chantier',esc(s.name||c.site||'—')],['Affaire',esc(c.affaire||'—')],['Date',dFR(c.at)],['Livraison prévue',c.livraison?dFR(c.livraison):'—'],['Émis par',esc(c.by||'')]],
  body:`<p><b>Objet :</b> ${esc(c.objet||'—')}${c.refFournisseur?' · <b>Réf. :</b> '+esc(c.refFournisseur):''}${c.contact?' · <b>Contact :</b> '+esc(c.contact):''}</p><table class="em"><tr><th>Désignation</th><th>Quantité</th><th>Unité</th><th>PU HT</th><th>Total HT</th></tr>${(c.lignes||[]).map(l=>`<tr><td>${esc(l.designation||'')}</td><td>${nb(l.qte,0)}</td><td>${esc(l.unite||'')}</td><td>${nb(l.pu)}</td><td>${nb((+l.qte||0)*(+l.pu||0))}</td></tr>`).join('')}<tr><td colspan="4"><b>Total HT</b></td><td><b>${nb(cmdTotal(c))}</b></td></tr></table>${c.notes?`<div class="card soft">${esc(c.notes)}</div>`:''}<p>Livraison à l'adresse du chantier, bon de livraison obligatoire (il sera importé dans le Stock du chantier).</p>`,css:'table.em td:nth-child(n+2){text-align:right}',footLeft:'SCR · achats'});}
/* ── débours ── */
export function dbListHTML(ctx,mineOnly){const me=ctx.me;let L=mineOnly?dbDe(ctx.key):dbAll();if(!mineOnly&&CS.etat)L=L.filter(d=>d.etat===CS.etat);const sites=ctx.sites||[];const sname=id=>(sites.find(s=>s.id===id)||{}).name||'—';const nat=k=>(NATURES.find(n=>n[0]===k)||NATURES[NATURES.length-1])[1];
  const tot=L.reduce((s,d)=>s+(+d.montant||0),0);const aval=L.filter(d=>d.etat==='saisi');
  const row=d=>`<div class="eq-row"><span class="ic" style="width:32px;text-align:center;font-size:18px">${{carburant:'⛽',peage:'🛣',hebergement:'🛏',repas:'🍽',fourniture:'📦',outillage:'🔧',transport:'🚆'}[d.nature]||'🧾'}</span><span class="eq-grow"><span class="eq-t">${eur(d.montant)} · ${esc(nat(d.nature))} ${tag(d.etat,DB_ETATS)}</span><span class="eq-s">${fr(d.date)} · ${esc(sname(d.site))} · ${esc(d.name||'')}${d.moyen?' · '+esc(d.moyen):''}${d.commentaire?' · '+esc(d.commentaire):''}${d.justif?' · <a href="'+esc(d.justif)+'" target="_blank" rel="noopener">justificatif</a>':''}${d.validePar?' · '+esc(d.etat==='refuse'?'refusé':'validé')+' par '+esc(d.validePar):''}</span></span>${ctx.canValidate&&d.etat==='saisi'?`<span class="eq-acts" style="margin:0"><button class="btn sm primary" data-act="cmd" data-v="dbok|${esc(d.id)}">✓</button><button class="btn sm" data-act="cmd" data-v="dbno|${esc(d.id)}" style="color:#9b2c22">✕</button></span>`:ctx.canValidate&&d.etat==='valide'?`<button class="btn sm" data-act="cmd" data-v="dbremb|${esc(d.id)}">remboursé</button>`:''}${(mineOnly||ctx.canValidate)&&d.etat==='saisi'?`<button class="btn sm" data-act="cmd" data-v="dbrm|${esc(d.id)}" title="retirer">🗑</button>`:''}</div>`;
  return `${mineOnly?'':`<div class="eq-filtres"><button class="chip${CS.etat?'':' active'}" data-act="cmd" data-v="etat|">Tous</button>${DB_ETATS.map(e=>`<button class="chip${CS.etat===e[0]?' active':''}" data-act="cmd" data-v="etat|${e[0]}">${e[1]} <span class="eq-badge">${dbAll().filter(d=>d.etat===e[0]).length}</span></button>`).join('')}</div>`}
    <div class="ac-stats" style="margin-bottom:8px"><div class="ac-stat"><b>${eur(tot)}</b><small>${mineOnly?'mes débours':'total affiché'}</small></div><div class="ac-stat ${aval.length?'warn':''}"><b>${aval.length}</b><small>à valider</small></div></div>
    <div class="eq-acts" style="margin:0 0 8px"><button class="btn primary" data-act="cmd" data-v="dbnew|">➕ Débours</button></div>
    ${L.length?`<div class="card"><div class="eq-list">${L.map(row).join('')}</div></div>`:'<div class="ac-empty">Aucun débours.</div>'}
    <div class="hint">Un débours = une dépense avancée pour le chantier (carburant, péage, hébergement, repas, fourniture…) : saisie par la personne, validée par le conducteur / le bureau, puis remboursée. Joins le justificatif (photo ou lien).</div>`;}
const fr=d=>d?new Date(d+'T00:00:00').toLocaleDateString('fr-FR'):'';
export function dbForm(ctx){const sites=ctx.sites||[];const today=new Date().toISOString().slice(0,10);
  A.openModal(`<h3 style="margin-top:0">Nouveau débours</h3><div class="row" style="display:flex;gap:6px;flex-wrap:wrap"><div style="flex:1;min-width:120px"><label class="f">Date</label><input class="f" id="db-date" type="date" value="${today}"></div><div style="flex:1;min-width:120px"><label class="f">Montant TTC €</label><input class="f" id="db-montant" type="number" step="0.01" placeholder="0,00"></div></div>
    <div class="row" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"><div style="flex:1;min-width:140px"><label class="f">Nature</label><select class="f" id="db-nature">${NATURES.map(n=>`<option value="${n[0]}">${n[1]}</option>`).join('')}</select></div><div style="flex:1;min-width:140px"><label class="f">Chantier</label><select class="f" id="db-site"><option value="">—</option>${sites.map(s=>`<option value="${esc(s.id)}"${ctx.siteDefault===s.id?' selected':''}>${esc(s.name||s.id)}</option>`).join('')}</select></div></div>
    <div class="row" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"><div style="flex:1;min-width:140px"><label class="f">Payé avec</label><select class="f" id="db-moyen"><option>Carte SCR</option><option>Mes deniers (à rembourser)</option><option>Espèces (caisse chantier)</option></select></div><div style="flex:1;min-width:140px"><label class="f">Justificatif (lien / photo)</label><input class="f" id="db-justif" placeholder="https://… ou « ticket remis au chef »"></div></div>
    <label class="f" style="margin-top:6px">Commentaire</label><input class="f" id="db-com" placeholder="ex. plein du Master, 48 L">
    <div class="actions" style="margin-top:8px"><button class="btn primary block" id="db-ok">Enregistrer le débours</button><button class="btn block" data-close>Annuler</button></div>`);
  document.getElementById('db-ok').onclick=()=>{const g=id=>(document.getElementById(id)||{}).value||'';const m=parseFloat(String(g('db-montant')).replace(',','.'));if(!(m>0)){A.toast('Le montant');return;}if(!g('db-date')){A.toast('La date');return;}
    const id=ctx.key+'|'+Date.now().toString(36);regSet('debours',id,{key:ctx.key,name:ctx.name,date:g('db-date'),montant:Math.round(m*100)/100,nature:g('db-nature'),site:g('db-site')||null,moyen:g('db-moyen'),justif:g('db-justif').trim()||null,commentaire:g('db-com').trim()||null,etat:'saisi',at:new Date().toISOString()},{local:!String(ctx.key).includes('@')});
    A.closeModal();A.toast('Débours enregistré — en attente de validation');if(ctx.render)ctx.render();};}
export const dbTodo=()=>dbAll().filter(d=>d.etat==='saisi');
/* ── actions ── */
export function cmdAct(v,el,ctx){const sv=String(v);const pi=sv.indexOf('|');const k=pi<0?sv:sv.slice(0,pi),arg=pi<0?'':sv.slice(pi+1); /* l'identifiant d'un débours contient lui-même un « | » */const c=CS.cur?regGet('commande',CS.cur):null;const say=t=>A.toast&&A.toast(t);
  switch(k){case 'tab':CS.tab=arg;CS.etat='';break;case 'etat':CS.etat=arg;break;case 'open':CS.cur=arg;CS.tab='cmdfiche';break;case 'back':CS.cur=null;CS.tab='cmd';break;
    case 'new':{if(!ctx.canEdit)return;const num=cmdNextNum();regSet('commande',num,{num,etat:'brouillon',site:ctx.siteDefault||null,lignes:[{designation:'',qte:1,unite:'u',pu:''}],by:A.userName(),at:new Date().toISOString()});CS.cur=num;CS.tab='cmdfiche';break;}
    case 'del':{if(!ctx.canEdit||!c)return;if(!confirm('Supprimer '+c.num+' ?'))return;regSet('commande',c.num,{deleted:true,deletedAt:new Date().toISOString()});CS.cur=null;CS.tab='cmd';break;}
    case 'ladd':{if(!ctx.canEdit||!c)return;regSet('commande',c.num,{lignes:(c.lignes||[]).concat([{designation:'',qte:1,unite:'u',pu:''}])});break;}
    case 'lrm':{if(!ctx.canEdit||!c)return;regSet('commande',c.num,{lignes:(c.lignes||[]).filter((l,i)=>i!==+arg)});break;}
    case 'print':{if(!c)return;const w=window.open('','_blank');if(!w){say('Autorise la fenêtre pop-up pour imprimer');return;}w.document.write(cmdPrintHTML(c,ctx.sites));w.document.close();return;}
    case 'dbnew':{dbForm(ctx);return;}
    case 'dbok':case 'dbno':case 'dbremb':{if(!ctx.canValidate)return;const d=regGet('debours',arg);if(!d)return;regSet('debours',arg,k==='dbok'?{etat:'valide',validePar:A.userName(),valideAt:new Date().toISOString()}:k==='dbno'?{etat:'refuse',validePar:A.userName(),valideAt:new Date().toISOString()}:{etat:'rembourse',rembourseAt:new Date().toISOString()},{local:!String(d.key||'').includes('@')});break;}
    case 'dbrm':{const d=regGet('debours',arg);if(!d)return;if(!(ctx.canValidate||d.key===ctx.key))return;regSet('debours',arg,{deleted:true},{local:!String(d.key||'').includes('@')});break;}
    default:return;}
  if(ctx.render)ctx.render();}
export function cmdInput(el,ctx){const d=el.dataset;if(!ctx.canEdit){A.toast('Lecture seule');return true;}const c=CS.cur?regGet('commande',CS.cur):null;if(!c)return false;
  if(d.cmdf){regSet('commande',c.num,{[d.cmdf]:el.value===''?null:el.value});if(ctx.render&&(d.cmdf==='etat'||d.cmdf==='site'||d.cmdf==='fournisseur'))ctx.render();return true;}
  if(d.cmdl){const [i,k]=d.cmdl.split('|');const L=(c.lignes||[]).map((l,j)=>j===+i?Object.assign({},l,{[k]:k==='qte'||k==='pu'?(el.value===''?'':+el.value):el.value}):l);regSet('commande',c.num,{lignes:L});if(ctx.render&&(k==='qte'||k==='pu'))ctx.render();return true;}
  return false;}
export function cmdView(ctx){const tabs=[['cmd','Bons de commande'],['db','Débours']];const head=CS.tab==='cmdfiche'?`<button class="ac-back" data-act="cmd" data-v="back|">‹ Bons de commande</button>`:`<div class="eq-filtres">${tabs.map(([k,l])=>`<button class="chip${CS.tab===k?' active':''}" data-act="cmd" data-v="tab|${k}">${l}${k==='db'&&dbTodo().length?' <span class="eq-badge">'+dbTodo().length+'</span>':''}</button>`).join('')}</div>`;
  return head+(CS.tab==='cmdfiche'?cmdFicheHTML(ctx):CS.tab==='db'?dbListHTML(ctx,false):cmdListHTML(ctx));}
export const cmdReady=()=>regLoaded('commande')&&regLoaded('debours');
