// doe.js — onglet EXPORT (07/10/2026, Ethan : « un onglet export sur lequel on choisit ce que l'on veut exporter … surtout un carnet de
// soudure et manchonnage avec report sur plan, ce qui est aujourd'hui infâme à faire »). Tout est généré DANS le navigateur, sans serveur :
// documents HTML imprimables (→ PDF par « Imprimer »), plan des soudures numérotées à l'échelle (planches), plan interactif hors ligne,
// dossier zip (fflate) avec les photos classées par n° de soudure, les feuilles QSE, les modifications du tracé et le dossier administratif.
import {Zip,ZipPassThrough,ZipDeflate,strToU8} from 'fflate';
let A=null; // API fournie par app.js (state, NET, géométrie, TS, QSE…)
export function initDoe(api){A=api;}
const r2=v=>Math.round((+v||0)*100)/100;
const dFR=x=>x?new Date(x).toLocaleDateString('fr-FR'):'';
const dhFR=x=>x?new Date(x).toLocaleDateString('fr-FR')+' '+new Date(x).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'';
const slug=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^\w.-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60)||'x';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:1});
const STEP_NAME={1:'Soudure',2:'Fils + DH',3:'Manchon',4:'Moussage'};
const STEP_TAG={1:'1-soudure',2:'2-fils-DH',3:'3-manchon',4:'4-moussage',0:'0-autre'};
const PROC={tig:'TIG',cellulosique:'Cellulosique',cell:'Cellulosique'};
const EV_LABEL={soudee:'Soudée',manchonnee:'Manchonnée',controlee:'Contrôlée',controle:'Contrôle',a_reprendre:'À reprendre'};
const PAGES={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};
const polyLen=pts=>{let L=0;for(let i=1;i<pts.length;i++)L+=Math.hypot(pts[i][0]-pts[i-1][0],pts[i][1]-pts[i-1][1]);return L;};
const pathD=pts=>pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(2)+' '+p[1].toFixed(2)).join(' ');
// décalage d'une polyligne [x,y] (même algorithme que l'appli : normale moyenne, angles saillants bornés)
function offsetPoly(pts,off){if(!off||pts.length<2)return pts;const n=pts.length;const out=[];for(let i=0;i<n;i++){const p=pts[i];let tx=0,ty=0;if(i>0){tx+=p[0]-pts[i-1][0];ty+=p[1]-pts[i-1][1];}if(i<n-1){tx+=pts[i+1][0]-p[0];ty+=pts[i+1][1]-p[1];}const L=Math.hypot(tx,ty)||1;tx/=L;ty/=L;const nx=ty,ny=-tx;let sc=1;if(i>0&&i<n-1){const ax=p[0]-pts[i-1][0],ay=p[1]-pts[i-1][1],La=Math.hypot(ax,ay)||1;const dot=(ay/La)*nx+(-ax/La)*ny;sc=1/Math.max(.35,dot);}out.push([p[0]+nx*off*sc,p[1]+ny*off*sc]);}return out;}
// point et tangente à une abscisse le long d'une polyligne [x,y]
function alongPoly(pts,L){let d=0;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];const s=Math.hypot(b[0]-a[0],b[1]-a[1]);if(d+s>=L&&s>0){const t=(L-d)/s;return {p:[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t],t:[(b[0]-a[0])/s,(b[1]-a[1])/s]};}d+=s;}const n=pts.length;if(n<2)return {p:pts[0]||[0,0],t:[1,0]};const a=pts[n-2],b=pts[n-1];const s=Math.hypot(b[0]-a[0],b[1]-a[1])||1;return {p:b,t:[(b[0]-a[0])/s,(b[1]-a[1])/s]};}
const midOf=pls=>{const pts=pls.flat();if(!pts.length)return null;const L=polyLen(pts);return alongPoly(pts,L/2);};

/* ---------- 1. données normalisées du chantier (tout ce que les documents utilisent) ---------- */
export function doeData(){const NET=A.net();if(!NET||NET.id==='__vide')return null;const S=A.state;
  const sheets=Object.values(S.sheets).map(sh=>({id:sh.id,name:sh.name||'',ppm:sh.ppm||1,type:sh.type||'',drawing:sh.drawing||null,lines:(sh.lines||[]).slice()}));
  const lines=[],welds=[],people={};let nPhotos=0;
  const addP=(name,k,at)=>{if(!name)return;const p=people[name]=people[name]||{name,n:{1:0,2:0,3:0,4:0},first:null,last:null};p.n[k]=(p.n[k]||0)+1;const t=at?String(at):null;if(t){if(!p.first||t<p.first)p.first=t;if(!p.last||t>p.last)p.last=t;}};
  Object.values(S.lines).forEach(l=>{if(!l||!l.cond)return;const sh=S.sheets[l.sheetId];const ppm=(sh&&sh.ppm)||1;const M=v=>r2(v/ppm);
    let pts=(l.pts||[]).map(p=>[M(p.x),M(p.y)]);if(pts.length<2&&l.els&&l.els.length){pts=[];l.els.forEach(e=>(e.axis&&e.axis[0]||[]).forEach(q=>{const P=[M(q.x),M(q.y)];const last=pts[pts.length-1];if(!last||Math.hypot(last[0]-P[0],last[1]-P[1])>0.05)pts.push(P);}));} // import DXF : l'axe est recomposé depuis les éléments
    const L={id:l.id,name:l.name||l.id,dn:l.dnNum||(l.els&&l.els[0]&&l.els[0].dn)||'',sheet:l.sheetId,parent:l.parent||null,pts,len:0,conds:{},nW:0,nDoc:0};
    L.len=r2(l.length||polyLen(L.pts));
    ['A','R'].forEach(c=>{const cd=l.cond[c];if(!cd)return;
      const els=cd.els.map((e,i)=>({i,kind:e.kind,label:e.kindLabel||e.kind,dn:e.dn,dn2:e.dn2||null,m0:r2(e.m0),m1:r2(e.m1),len:r2(e.len),casing:r2(A.casingOf(e)),axis:(e.axis||[]).map(pl=>pl.map(p=>[M(p.x),M(p.y)]))}));
      const ids=[];cd.joints.forEach(j=>{const e=cd.els[j.idx];let q=null;try{q=A.jointPos(l,j.idx,c);}catch(x){}const pos=q?[M(q.x),M(q.y)]:(e&&e.to?[M(e.to.x),M(e.to.y)]:[0,0]);const tg=q?[q.tx,q.ty]:[1,0];
        const st=j.steps||{};const steps={};[1,2,3,4].forEach(n=>{const s=st[n];if(!s)return;steps[n]={done:!!s.done,by:s.by||'',at:s.at||null,proc:s.proc?(PROC[s.proc]||s.proc):'',type:s.type||'',cause:s.cause?A.ts.causeLabel(s.cause):'',press:!!s.press,dh:s.dh||null,photos:(s.photos||[]).filter(p=>typeof p==='string')};if(s.done)addP(s.by,n,s.at);});
        const events=(j.events||[]).map(ev=>({type:ev.type,label:EV_LABEL[ev.type]||ev.type,by:A.uname(ev.by),at:ev.at?new Date(ev.at).toISOString():null,data:ev.data||{},photos:(ev.photos||[]).filter(p=>typeof p==='string')}));
        if(!steps[1])events.filter(ev=>ev.type==='soudee').forEach(ev=>addP(ev.by,1,ev.at));if(!steps[3])events.filter(ev=>ev.type==='manchonnee').forEach(ev=>addP(ev.by,3,ev.at));
        const photos=[];const seen=new Set();const push=(src,step,at,by)=>{if(!src||seen.has(src))return;seen.add(src);photos.push({src,step,at:at||null,by:by||''});};
        [1,2,3,4].forEach(n=>{const s=steps[n];if(s)s.photos.forEach(p=>push(p,n,s.at,s.by));});events.forEach(ev=>ev.photos.forEach(p=>push(p,ev.type==='soudee'?1:ev.type==='manchonnee'?3:0,ev.at,ev.by)));(j.photos||[]).forEach(p=>{if(typeof p==='string')push(p,0,null,'');});
        photos.forEach((p,k)=>{p.file=`${slug(j.weldId)}_${STEP_TAG[p.step]||STEP_TAG[0]}_${p.at?String(p.at).slice(0,10):'sans-date'}_${k+1}.jpg`;});
        const doc=(j.status&&j.status!=='a_souder')||events.length>0||Object.values(steps).some(s=>s.done);nPhotos+=photos.length;
        const W={id:j.weldId,line:l.id,lineName:L.name,cond:c,idx:j.idx,pk:r2(j.m!==undefined&&j.m!==null?j.m:(e?e.m1:0)),dn:j.dn||(e&&e.dn)||L.dn,pos,tg,status:j.status||'a_souder',statusLabel:(A.STATUS[j.status]||{}).label||j.status||'',extra:!!j.extra,fc:!!j.fc,dev:+(j.dev||0),teeOut:!!j.teeOut,bypass:!!j.bypass,sleeveWith:j.sleeveWith||null,wire:j.wire||'',note:j.note||'',extru:j.extru?{cause:A.ts.causeLabel(j.extru.cause),by:j.extru.by||'',at:j.extru.at||null}:null,steps,events,photos,doc};
        welds.push(W);ids.push(W.id);L.nW++;if(doc)L.nDoc++;});
      L.conds[c]={els,joints:ids};});
    lines.push(L);});
  lines.sort((a,b)=>a.name.localeCompare(b.name,'fr',{numeric:true}));
  const ppmOf=lineId=>{const l=S.lines[lineId];const sh=l&&S.sheets[l.sheetId];return (sh&&sh.ppm)||1;};
  let ts=[];try{const T=A.ts.of();if(T)ts=T.items.filter(it=>it.etat!=='marche').map(it=>{let q=null;try{q=A.ts.pos(it);}catch(e){}const ppm=ppmOf(it.line);return {id:it.id,kind:it.kind,line:it.line,weldId:it.weldId||null,etat:it.etat,etatLabel:A.ts.et[it.etat]||it.etat,col:A.ts.col[it.etat]||'#888',short:A.ts.short(it),label:it.label||'',desig:it.desig||'',devis:it.ts||'',qty:A.ts.qtyTxt(it.qty||{}),pos:q?[r2(q.x/ppm),r2(q.y/ppm)]:null,at:it.at||null,by:it.by||'',photos:(it.photos||[]).filter(p=>typeof p==='string')};});}catch(e){console.warn(e);}
  const qse=((NET.qse&&NET.qse.docs)||[]).map(d=>({id:d.id,type:d.type,title:d.title||'',at:d.at,by:d.by||'',sigs:(d.sigs||[]).length}));
  const admin=((NET.admin&&NET.admin.docs)||[]).map(d=>({id:d.id,cat:d.cat,catLabel:(A.adminCats().find(c=>c[0]===d.cat)||[])[1]||d.cat,name:d.name,size:d.size||0,url:d.url||null,data:d.data||null,by:d.by||'',at:d.at}));
  const marche=NET.marche?{at:NET.marche.at,source:NET.marche.source||'',by:NET.marche.by||''}:null;
  return {site:{id:NET.id,name:NET.name||NET.id,supplier:NET.supplier||'',serie:NET.serie||'',client:NET.client||'',source:NET.source||''},at:new Date().toISOString(),by:A.userName(),sheets,lines,welds,people:Object.values(people).sort((a,b)=>a.name.localeCompare(b.name,'fr')),ts,qse,admin,marche,nPhotos,
    nDoc:welds.filter(w=>w.doc).length,nExtru:welds.filter(w=>w.extru).length};}
const weldsOf=(D,o)=>D.welds.filter(w=>o&&o.all?true:w.doc);
const sortW=(a,b)=>a.lineName.localeCompare(b.lineName,'fr',{numeric:true})||a.pk-b.pk||a.cond.localeCompare(b.cond);

/* ---------- 2. dessin du réseau d'une feuille (unités : mètres ; tailles papier données en mm via o.s = m par mm) ---------- */
// o : {s, fond, pk, ts, all, labels, glyphs, lineNames, grid}
export function planWorld(D,sheetId,o){const s=o.s||0.2;const mm=v=>v*s;const lines=D.lines.filter(l=>l.sheet===sheetId);const sh=D.sheets.find(x=>x.id===sheetId);
  let x0=1e15,y0=1e15,x1=-1e15,y1=-1e15;const bump=(x,y)=>{if(!isFinite(x)||!isFinite(y))return;x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);};
  lines.forEach(l=>{Object.values(l.conds).forEach(cd=>cd.els.forEach(e=>e.axis.forEach(pl=>pl.forEach(p=>bump(p[0],p[1])))));l.pts.forEach(p=>bump(p[0],p[1]));});
  if(x0>x1)return null;
  let g='';const W=D.welds.filter(w=>lines.some(l=>l.id===w.line));
  if(o.fond!==false&&sh&&sh.drawing&&A.drawingSVG){try{const r=A.drawingSVG(sh.drawing,{k:1,texts:false,colors:false,op:1,fillOp:1});if(r&&r.svg)g+=`<g class="fond" opacity=".45"${sh.ppm!==1?` transform="scale(${1/sh.ppm})"`:''}>${r.svg}</g>`;}catch(e){console.warn(e);}}
  // carroyage (coordonnées projetées) : croix tous les 100 m
  if(o.grid!==false&&(Math.abs(x0)>1e4||Math.abs(y0)>1e4)&&(x1-x0)<5000){const st=100;let gg='';for(let X=Math.floor(x0/st)*st;X<=x1+st;X+=st)for(let Y=Math.floor(y0/st)*st;Y<=y1+st;Y+=st){const c=mm(2.5);gg+=`<path d="M${X-c} ${Y}H${X+c}M${X} ${Y-c}V${Y+c}" stroke="#9a9a9a" stroke-width="${mm(.15)}"/>`;if(o.labels!==false)gg+=`<text x="${X+mm(.8)}" y="${Y-mm(.8)}" font-size="${mm(1.5)}" fill="#9a9a9a">${Math.round(X)} ; ${Math.round(-Y)}</text>`;}g+=`<g class="grid">${gg}</g>`;}
  // conduites (aller rouge / retour bleu), décalées de part et d'autre de l'axe
  const off=e=>Math.max(e.casing*.7,mm(.9));const wid=e=>Math.max(e.casing*.8,mm(.45));
  let pipes='',glyphs='',names='',pks='';
  lines.forEach(l=>{if(o.axisOnly){if(l.pts.length>1)pipes+=`<path d="${pathD(l.pts)}" stroke="#333" stroke-width="${mm(.9).toFixed(3)}" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`;}else ['A','R'].forEach(c=>{const cd=l.conds[c];if(!cd)return;const side=c==='A'?1:-1;const col=c==='A'?'#c8382f':'#2a5fb4';
    cd.els.forEach(e=>{const d=off(e)*side;const w=wid(e);e.axis.forEach(pl=>{if(pl.length<2)return;pipes+=`<path d="${pathD(offsetPoly(pl,d))}" stroke="${col}" stroke-width="${w.toFixed(3)}" fill="none" stroke-linecap="butt" stroke-linejoin="round" />`;});
      if(o.glyphs===false)return;const q=midOf(e.axis.map(pl=>offsetPoly(pl,d)));if(!q)return;const [px,py]=q.p,[tx,ty]=q.t;const nx=ty,ny=-tx;const a=mm(1.2),b=mm(.9);
      if(e.kind==='valve')glyphs+=`<path d="M${px-tx*a-nx*b} ${py-ty*a-ny*b}L${px+tx*a+nx*b} ${py+ty*a+ny*b}L${px+tx*a-nx*b} ${py+ty*a-ny*b}L${px-tx*a+nx*b} ${py-ty*a+ny*b}Z" fill="#111" stroke="#fff" stroke-width="${mm(.15)}"/>`;
      else if(e.kind==='reducer'){const b2=b*.45;glyphs+=`<path d="M${px-tx*a-nx*b} ${py-ty*a-ny*b}L${px+tx*a-nx*b2} ${py+ty*a-ny*b2}L${px+tx*a+nx*b2} ${py+ty*a+ny*b2}L${px-tx*a+nx*b} ${py-ty*a+ny*b}Z" fill="#fff" stroke="#111" stroke-width="${mm(.2)}"/>`;}
      else if(e.kind==='endcap')glyphs+=`<path d="M${px-nx*b*1.4} ${py-ny*b*1.4}L${px+nx*b*1.4} ${py+ny*b*1.4}" stroke="#111" stroke-width="${mm(.45)}"/>`;
      else if(e.kind==='tee'||e.kind==='teeout')glyphs+=`<rect x="${px-b*.7}" y="${py-b*.7}" width="${b*1.4}" height="${b*1.4}" fill="#111" transform="rotate(${(Math.atan2(ty,tx)*180/Math.PI).toFixed(1)} ${px} ${py})"/>`;});});
    if(o.lineNames!==false&&l.pts.length>1){const Lt=polyLen(l.pts);const at=[Math.min(3,Lt*.1)];const rep=mm(200);if(o.nameRepeat!==false)for(let m=rep;m<Lt-rep*.3;m+=rep)at.push(m); // nom au départ, puis répété (200 mm papier)
      at.forEach(m0=>{const q=alongPoly(l.pts,m0);const [px,py]=q.p;const nx=q.t[1],ny=-q.t[0];const d=mm(4.5);let ang=Math.atan2(q.t[1],q.t[0])*180/Math.PI;if(ang>90)ang-=180;if(ang<-90)ang+=180;
      names+=`<text x="${px+nx*d}" y="${py+ny*d}" font-size="${mm(2.6)}" font-weight="700" fill="#111" stroke="#fff" stroke-width="${mm(.6)}" paint-order="stroke" text-anchor="start" transform="rotate(${ang.toFixed(1)} ${px+nx*d} ${py+ny*d})">${esc(l.name)}${l.dn?' · DN'+esc(l.dn):''}</text>`;});}
    if(o.pk!==false&&l.pts.length>1){const Lt=polyLen(l.pts);const st=Lt>400?100:50;for(let m=st;m<Lt-5;m+=st){const q=alongPoly(l.pts,m);const [px,py]=q.p;const nx=q.t[1],ny=-q.t[0];const h=mm(2.6);pks+=`<path d="M${px-nx*h} ${py-ny*h}L${px+nx*h} ${py+ny*h}" stroke="#555" stroke-width="${mm(.18)}"/><text x="${px+nx*(h+mm(.6))}" y="${py+ny*(h+mm(.6))}" font-size="${mm(1.6)}" fill="#555" text-anchor="middle" dominant-baseline="middle">${m}</text>`;}}});
  g+=`<g class="pipes">${pipes}</g><g class="glyphs">${glyphs}</g>`;
  // soudures : pastille (couleur = avancement) + numéro du côté de sa conduite, en quinconce quand les soudures se touchent
  let dots='',labels='';const byCond={};W.forEach(w=>{(byCond[w.line+'|'+w.cond]=byCond[w.line+'|'+w.cond]||[]).push(w);});
  const r=mm(1.05),fs=mm(2);const half=o.all?()=>true:w=>true;
  if(o.dots!==false)Object.values(byCond).forEach(ws=>{ws.sort((a,b)=>a.pk-b.pk);let lastEnd=-1e9,level=0;ws.forEach(w=>{if(!half(w))return;const side=w.cond==='A'?1:-1;const e=(D.lines.find(l=>l.id===w.line)||{conds:{}}).conds[w.cond];const el=e&&e.els[w.idx];const d=off(el||{casing:.2})*side;
      const [px,py]=w.pos;const [tx,ty]=w.tg;const nx=ty,ny=-tx;const cx=px+nx*d,cy=py+ny*d;const colS=(A.STATUS[w.status]||{}).color||'#898781';const documented=w.doc;
      dots+=`<circle class="w" data-w="${esc(w.id)}" cx="${cx.toFixed(2)}" cy="${cy.toFixed(2)}" r="${r.toFixed(3)}" fill="${documented?colS:'#fff'}" stroke="${documented?'#111':'#888'}" stroke-width="${mm(.2)}"${documented?'':` stroke-dasharray="${mm(.4)} ${mm(.3)}"`}/>`;
      if(o.labels===false)return;const txt=String(w.id);const len=mm(1.15*txt.length);if(w.pk-lastEnd<len*1.1)level=(level+1)%3;else level=0;lastEnd=w.pk+len;
      const dd=Math.abs(d)+mm(2.3)+level*mm(2.7);const lx=px+nx*dd*side,ly=py+ny*dd*side;let ang=Math.atan2(ty,tx)*180/Math.PI;if(ang>90)ang-=180;if(ang<-90)ang+=180;
      labels+=`<text x="${lx.toFixed(2)}" y="${ly.toFixed(2)}" font-size="${fs}" font-weight="600" fill="${documented?'#111':'#888'}" stroke="#fff" stroke-width="${mm(.5)}" paint-order="stroke" text-anchor="middle" dominant-baseline="middle" transform="rotate(${ang.toFixed(1)} ${lx.toFixed(2)} ${ly.toFixed(2)})">${esc(txt)}</text>`;
      if(level)labels+=`<path d="M${cx.toFixed(2)} ${cy.toFixed(2)}L${lx.toFixed(2)} ${ly.toFixed(2)}" stroke="#888" stroke-width="${mm(.12)}"/>`;});});
  g+=`<g class="pk">${pks}</g><g class="names">${names}</g><g class="dots">${dots}</g><g class="lbl">${labels}</g>`;
  if(o.ts!==false&&D.ts.length){let t='';D.ts.forEach(it=>{if(!it.pos||!lines.some(l=>l.id===it.line))return;const [px,py]=it.pos;const R=mm(1.7);t+=`<circle cx="${px}" cy="${py}" r="${R}" fill="${it.col}" stroke="#fff" stroke-width="${mm(.25)}"/><text x="${px}" y="${py-R-mm(.6)}" font-size="${mm(1.9)}" font-weight="800" fill="${it.col}" stroke="#fff" stroke-width="${mm(.5)}" paint-order="stroke" text-anchor="middle">${esc(it.short)}</text>`;});g+=`<g class="ts">${t}</g>`;}
  const pad=mm(6);return {svg:g,bbox:[x0-pad,y0-pad,x1+pad,y1+pad],welds:W};}

/* ---------- 3. plan des soudures numérotées, imprimable à l'échelle (planches) ---------- */
// o : {scale:200, format:'A3'|'A4'|'A2'|'A1'|'A0'|'auto', fond, pk, ts, all}
export function planPrintHTML(D,o={}){const scale=+o.scale||200;const fmtP=o.format||'A3';const margin=8,cart=22,overlap=15;
  const planches={};const sheetsOut=[];let note='';
  D.sheets.forEach((sh,si)=>{const world=planWorld(D,sh.id,{s:scale/1000,fond:o.fond,pk:o.pk,ts:o.ts,all:o.all});if(!world)return;
    const [bx0,by0,bx1,by1]=world.bbox;const bw=bx1-bx0,bh=by1-by0;let s=scale/1000;let W,H,tiles=[];
    if(fmtP==='auto'){W=Math.ceil(bw/s+2*margin);H=Math.ceil(bh/s+2*margin+cart);const cap=5000;if(W>cap||H>cap){const s2=Math.max(bw/(cap-2*margin),bh/(cap-2*margin-cart));s=s2;const sc2=Math.ceil(s*1000/50)*50;s=sc2/1000;W=Math.ceil(bw/s+2*margin);H=Math.ceil(bh/s+2*margin+cart);note+=`Feuille « ${esc(sh.name)} » : une planche à l'échelle 1/${scale} dépasserait 5 m — ramenée à 1/${sc2}. `;}
      tiles.push({x:bx0,y:by0,w:bw,h:bh,n:1});}
    else{let [pw,ph]=PAGES[fmtP]||PAGES.A3;if(o.orient==='portrait'){W=Math.min(pw,ph);H=Math.max(pw,ph);}else{W=Math.max(pw,ph);H=Math.min(pw,ph);}
      const uw=W-2*margin,uh=H-2*margin-cart;const tw=uw*s,th=uh*s;const sx=(uw-overlap)*s,sy=(uh-overlap)*s;
      const cols=Math.max(1,Math.ceil((bw-tw)/sx)+1),rows=Math.max(1,Math.ceil((bh-th)/sy)+1);
      const totW=tw+(cols-1)*sx,totH=th+(rows-1)*sy;const ox=bx0-(totW-bw)/2,oy=by0-(totH-bh)/2; // centré sur le réseau
      const pts=[];D.lines.filter(l=>l.sheet===sh.id).forEach(l=>{Object.values(l.conds).forEach(cd=>cd.els.forEach(e=>e.axis.forEach(pl=>pl.forEach(p=>pts.push(p)))));});world.welds.forEach(w=>pts.push(w.pos));
      let n=0;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const x=ox+c*sx,y=oy+r*sy;const m=2;if(!pts.some(p=>p[0]>=x-m&&p[0]<=x+tw+m&&p[1]>=y-m&&p[1]<=y+th+m))continue;tiles.push({x,y,w:tw,h:th,n:++n,r,c});}
      if(!tiles.length)tiles.push({x:bx0,y:by0,w:tw,h:th,n:1});}
    const pref=D.sheets.length>1?(si+1)+'.':'';
    world.welds.forEach(w=>{const t=tiles.find(t=>w.pos[0]>=t.x&&w.pos[0]<=t.x+t.w&&w.pos[1]>=t.y&&w.pos[1]<=t.y+t.h);if(t)planches[w.id]=pref+t.n;});
    sheetsOut.push({sh,world,s,W,H,tiles,pref});});
  if(!sheetsOut.length)return {html:'',planches,nPages:0,note};
  const scTxt=s=>'1/'+Math.round(s*1000);const esc2=esc;
  const legend=(x,y)=>{const S=A.STATUS;const ks=Object.keys(S);let h=`<g font-family="Arial,Helvetica,sans-serif" font-size="2.6" fill="#111">`;ks.forEach((k,i)=>{h+=`<circle cx="${x+1.3+i*23}" cy="${y}" r="1.1" fill="${S[k].color}" stroke="#111" stroke-width=".2"/><text x="${x+3.6+i*23}" y="${y+.9}">${esc2(S[k].label)}</text>`;});
    const bx=x+ks.length*23+4;h+=`<path d="M${bx} ${y}h8" stroke="#c8382f" stroke-width="1.2"/><text x="${bx+9.5}" y="${y+.9}">aller</text><path d="M${bx+20} ${y}h8" stroke="#2a5fb4" stroke-width="1.2"/><text x="${bx+29.5}" y="${y+.9}">retour</text>`;
    h+=`<path d="M${bx+44} ${y-1.1}L${bx+47} ${y+1.1}L${bx+47} ${y-1.1}L${bx+44} ${y+1.1}Z" fill="#111"/><text x="${bx+48.5}" y="${y+.9}">vanne</text><path d="M${bx+60} ${y-1.1}L${bx+63} ${y-.5}L${bx+63} ${y+.5}L${bx+60} ${y+1.1}Z" fill="#fff" stroke="#111" stroke-width=".25"/><text x="${bx+64.5}" y="${y+.9}">réduction</text><rect x="${bx+80}" y="${y-1}" width="2" height="2" fill="#111"/><text x="${bx+83.5}" y="${y+.9}">té</text>`;
    if(D.ts.length)h+=`<circle cx="${bx+92}" cy="${y}" r="1.3" fill="#c9a227" stroke="#fff" stroke-width=".3"/><text x="${bx+94.5}" y="${y+.9}">modification (n° de devis / compris / mémoire)</text>`;return h+'</g>';};
  const cartouche=(W,H,title,sub,right)=>`<rect x="${margin}" y="${H-margin-cart}" width="${W-2*margin}" height="${cart}" fill="#fff" stroke="#111" stroke-width=".35"/>
    <g font-family="Arial,Helvetica,sans-serif" fill="#111"><text x="${margin+3}" y="${H-margin-cart+6}" font-size="4.2" font-weight="700">${esc2(D.site.name)}</text><text x="${margin+3}" y="${H-margin-cart+11.5}" font-size="3.2">${title}</text><text x="${margin+3}" y="${H-margin-cart+16}" font-size="2.8" fill="#444">${sub}</text>
    <text x="${W-margin-3}" y="${H-margin-cart+6}" font-size="3" text-anchor="end">${right}</text><text x="${W-margin-3}" y="${H-margin-cart+11}" font-size="2.8" text-anchor="end" fill="#444">édité le ${dFR(D.at)} par ${esc2(D.by)}</text><text x="${W-margin-3}" y="${H-margin-cart+16}" font-size="2.6" text-anchor="end" fill="#777">TRACÉ / RCU-COMPAGNON</text></g>${legend(margin+3,H-margin-4.2)}`;
  let pages='';let nPages=0;const W0=sheetsOut[0].W,H0=sheetsOut[0].H;
  sheetsOut.forEach(({sh,world,s,W,H,tiles,pref})=>{const mm=v=>v*s;const [bx0,by0,bx1,by1]=world.bbox;const uw=W-2*margin,uh=H-2*margin-cart;const defsId='w'+slug(sh.id);
    pages+=`<svg style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true"><defs><g id="${defsId}" font-family="Arial,Helvetica,sans-serif">${world.svg}</g></defs></svg>`;
    if(tiles.length>1){ // plan de découpage
      nPages++;const k=Math.min(uw/(bx1-bx0),uh/(by1-by0));const vw=uw/k,vh=uh/k;const vx=bx0-(vw-(bx1-bx0))/2,vy=by0-(vh-(by1-by0))/2;const ss=1/k;
      pages+=`<section class="pg"><svg width="${W}mm" height="${H}mm" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" fill="#fff"/><svg x="${margin}" y="${margin}" width="${uw}" height="${uh}" viewBox="${vx} ${vy} ${vw} ${vh}"><rect x="${vx}" y="${vy}" width="${vw}" height="${vh}" fill="#f7f6f1"/><g opacity=".9">${planWorld(D,sh.id,{s:ss*1.2,fond:o.fond,pk:false,ts:false,labels:false,glyphs:false,dots:false,axisOnly:true,nameRepeat:false,lineNames:true,grid:false,all:o.all}).svg}</g>
        ${tiles.map(t=>`<rect x="${t.x}" y="${t.y}" width="${t.w}" height="${t.h}" fill="#1c3d6b" fill-opacity=".06" stroke="#1c3d6b" stroke-width="${ss*.5}"/><text x="${t.x+t.w/2}" y="${t.y+t.h/2}" font-size="${ss*9}" font-weight="800" fill="#1c3d6b" fill-opacity=".55" text-anchor="middle" dominant-baseline="middle" font-family="Arial,Helvetica,sans-serif">${pref}${t.n}</text>`).join('')}</svg><rect x="${margin}" y="${margin}" width="${uw}" height="${uh}" fill="none" stroke="#111" stroke-width=".35"/>
        ${cartouche(W,H,'Plan des soudures numérotées — <tspan font-weight="700">plan de découpage</tspan> ('+tiles.length+' planches '+esc2(fmtP)+' à l\'échelle '+scTxt(s)+')',esc2(sh.name||''),'Découpage · '+esc2(fmtP))}</svg></section>`;}
    tiles.forEach(t=>{nPages++;const vw=uw*s,vh=uh*s;const vx=t.x-(vw-t.w)/2,vy=t.y-(vh-t.h)/2;
      pages+=`<section class="pg"><svg width="${W}mm" height="${H}mm" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" fill="#fff"/><svg x="${margin}" y="${margin}" width="${uw}" height="${uh}" viewBox="${vx} ${vy} ${vw} ${vh}"><rect x="${vx}" y="${vy}" width="${vw}" height="${vh}" fill="#fbfaf6"/><use href="#${defsId}"/></svg><rect x="${margin}" y="${margin}" width="${uw}" height="${uh}" fill="none" stroke="#111" stroke-width=".35"/>
        <g font-family="Arial,Helvetica,sans-serif" font-size="3" fill="#111">${t.r!==undefined&&tiles.length>1?['N','S','E','O'].map(dir=>{const nb=dir==='N'?tiles.find(q=>q.r===t.r-1&&q.c===t.c):dir==='S'?tiles.find(q=>q.r===t.r+1&&q.c===t.c):dir==='E'?tiles.find(q=>q.r===t.r&&q.c===t.c+1):tiles.find(q=>q.r===t.r&&q.c===t.c-1);if(!nb)return '';const x=dir==='E'?W-margin-2:dir==='O'?margin+2:W/2,y=dir==='N'?margin+4:dir==='S'?H-margin-cart-2:H/2-cart/2;return `<text x="${x}" y="${y}" text-anchor="${dir==='E'?'end':dir==='O'?'start':'middle'}" fill="#1c3d6b" font-weight="700">${dir==='N'?'▲':dir==='S'?'▼':dir==='E'?'▶':'◀'} planche ${pref}${nb.n}</text>`;}).join(''):''}</g>
        ${(()=>{const bm=[1,2,5,10,20,50,100,200].find(v=>v/s>=15)||200;const bw=bm/s;return `<g font-family="Arial,Helvetica,sans-serif"><rect x="${margin+uw-bw-10}" y="${margin+uh-9}" width="${bw+8}" height="7.5" fill="#fff" fill-opacity=".92" stroke="#111" stroke-width=".25"/><rect x="${margin+uw-bw-6}" y="${margin+uh-4.6}" width="${bw}" height="1.3" fill="#111"/><rect x="${margin+uw-bw-6}" y="${margin+uh-4.6}" width="${bw/2}" height="1.3" fill="#fff" stroke="#111" stroke-width=".2"/><text x="${margin+uw-bw-6}" y="${margin+uh-5.6}" font-size="2.3">0</text><text x="${margin+uw-6}" y="${margin+uh-5.6}" font-size="2.3" text-anchor="end">${bm} m</text></g>`;})()}
        ${cartouche(W,H,'Plan des soudures numérotées — <tspan font-weight="700">planche '+pref+t.n+' / '+tiles.length+'</tspan> · échelle '+scTxt(s)+' sur '+esc2(fmtP==='auto'?'une planche':fmtP),esc2(sh.name||'')+' · report du carnet de soudage et manchonnage · n° = n° de soudure (pastille = avancement)','Planche '+pref+t.n+' / '+tiles.length)}</svg></section>`;});});
  const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Plan des soudures numérotées — ${esc(D.site.name)}</title>
  <style>@page{size:${W0}mm ${H0}mm;margin:0}html,body{margin:0;padding:0;background:#777}.pg{width:${W0}mm;height:${H0}mm;overflow:hidden;position:relative;background:#fff;margin:0 auto 6mm;page-break-after:always;break-after:page}.pg svg{display:block}.bar{position:fixed;top:8px;right:8px;z-index:9;display:flex;gap:6px;align-items:center;background:#fff;padding:8px 10px;border-radius:10px;box-shadow:0 4px 16px rgba(0,0,0,.3);font:13px system-ui,sans-serif}.bar button{padding:8px 14px;font-weight:700;cursor:pointer}@media print{.bar{display:none}.pg{margin:0}body{background:#fff}}</style></head><body>
  <div class="bar"><span>${nPages} page${nPages>1?'s':''} · ${esc(fmtP==='auto'?'une planche':fmtP)} · 1/${scale}${note?' · '+esc(note):''}</span><button onclick="print()">🖨 Imprimer / enregistrer en PDF</button></div>${pages}</body></html>`;
  return {html,planches,nPages,note};}

/* ---------- 4. carnet de soudage et manchonnage (imprimable) ---------- */
// o : {all, photos:'all'|'last'|'none', photoSrc:(p,w)=>url, planches:{}, planTitle}
export function carnetHTML(D,o={}){const ws=weldsOf(D,o).slice().sort(sortW);const src=o.photoSrc||((p)=>p.src);const planches=o.planches||{};const esc2=esc;
  const stepTxt=(w,n)=>{const s=w.steps[n];if(!s||!s.done){const ev=w.events.find(e=>(n===1&&e.type==='soudee')||(n===3&&e.type==='manchonnee'));if(ev)return `<b>${dFR(ev.at)}</b><br><span class="dim">${esc2(ev.by)}</span>${n===1&&ev.data.procede?'<br>'+esc2(PROC[ev.data.procede]||ev.data.procede):''}${n===3&&ev.data.manchon==='extrude'?'<br><span class="hot">extrudé</span>':''}`;return '';}
    let x=`<b>${dFR(s.at)}</b><br><span class="dim">${esc2(s.by)}</span>`;if(n===1&&s.proc)x+='<br>'+esc2(s.proc);
    if(n===2&&s.dh){const d=s.dh;x+='<br>'+[d.meas!=null&&d.meas!==''?'R '+esc2(fmt(d.meas))+' Ω':'',d.expected!=null&&d.expected!==''?'att. '+esc2(fmt(d.expected))+' Ω':'',d.iso!=null?'iso '+esc2(fmt(d.iso))+' MΩ':''].filter(Boolean).join(' · ');}
    if(n===3){x+='<br>'+(s.type==='extrude'?`<span class="hot">extrudé</span>${s.cause?' — '+esc2(s.cause):''}`:'manchon rétracté')+(s.press?' · pression ✓':'');}return x;};
  const obs=w=>[w.extra?'soudure supplémentaire':'',w.fc?'fausse coupe'+(w.dev?' '+fmt(w.dev)+'°':''):'',w.teeOut?'sortie de té':'',w.sleeveWith?'même manchon que '+esc2(w.sleeveWith):'',w.wire==='inversion'?'<span class="hot">inversion de fils</span>':'',w.status==='a_reprendre'?'<span class="hot">à reprendre</span>':'',w.note?esc2(w.note):''].filter(Boolean).join(' · ');
  const lines=D.lines.filter(l=>ws.some(w=>w.line===l.id));
  const miniPlan=l=>{const pts=l.pts;if(pts.length<2)return '';let x0=1e15,y0=1e15,x1=-1e15,y1=-1e15;D.lines.filter(x=>x.sheet===l.sheet).forEach(L2=>L2.pts.forEach(p=>{x0=Math.min(x0,p[0]);y0=Math.min(y0,p[1]);x1=Math.max(x1,p[0]);y1=Math.max(y1,p[1]);}));if(x0>x1)return '';const pad=Math.max(4,(x1-x0)*.06,(y1-y0)*.06);x0-=pad;y0-=pad;x1+=pad;y1+=pad;
    return `<svg viewBox="${x0} ${y0} ${x1-x0} ${y1-y0}" class="mini">${D.lines.filter(x=>x.sheet===l.sheet).map(L2=>`<path d="${pathD(L2.pts)}" stroke="${L2.id===l.id?'#c8382f':'#b9b6ad'}" stroke-width="${L2.id===l.id?2.4:1.2}" vector-effect="non-scaling-stroke" fill="none"/>`).join('')}${ws.filter(w=>w.line===l.id).map(w=>`<circle cx="${w.pos[0]}" cy="${w.pos[1]}" r="${Math.max(.3,(x1-x0)*.006)}" fill="${(A.STATUS[w.status]||{}).color||'#888'}"/>`).join('')}</svg>`;};
  const phBlock=w=>{if(o.photos==='none'||!w.photos.length)return '';let ph=w.photos;if(o.photos==='last'){const seen={};ph=ph.slice().reverse().filter(p=>{if(seen[p.step])return false;seen[p.step]=1;return true;}).reverse();}
    return `<div class="phs"><div class="phh"><b>${esc2(w.id)}</b> · ${esc2(w.lineName)} · ${w.cond==='A'?'aller':'retour'} · PK ${fmt(w.pk)} m${planches[w.id]?' · planche '+esc2(planches[w.id]):''}</div>${ph.map(p=>`<figure><img src="${esc2(src(p,w))}" loading="lazy"><figcaption>${esc2(STEP_NAME[p.step]||'photo')}${p.at?' · '+dhFR(p.at):''}${p.by?' · '+esc2(p.by):''}</figcaption></figure>`).join('')}</div>`;};
  const totML=D.lines.reduce((t,l)=>t+(l.len||0),0);const nMan=ws.filter(w=>w.status==='manchonnee').length;
  const css=`body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;margin:0;color:#111;font-size:11px}.pg{padding:12mm 12mm 10mm}h1{font-size:22px;margin:0 0 4px}h2{font-size:15px;margin:0 0 6px;border-bottom:2px solid #111;padding-bottom:3px;page-break-after:avoid}h3{font-size:12.5px;margin:10px 0 4px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #c9c9c9;padding:3px 5px;text-align:left;vertical-align:top}th{background:#f1f0eb;font-size:10.5px}tr{page-break-inside:avoid}td.n,th.n{text-align:right}.dim{color:#666}.hot{color:#b3261e;font-weight:700}.muted{color:#666;font-size:10.5px}.cover{min-height:168mm;display:flex;flex-direction:column;justify-content:space-between}td.id{white-space:nowrap}.kpi{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.kpi div{border:1px solid #ccc;border-radius:8px;padding:8px 12px;min-width:90px}.kpi b{display:block;font-size:20px}.mini{width:100%;max-height:60mm;background:#f6f5f0;border-radius:6px;border:1px solid #ddd;margin:4px 0 8px}.phs{border:1px solid #ddd;border-radius:6px;padding:5px 6px;margin:6px 0;page-break-inside:avoid;display:flex;flex-wrap:wrap;gap:6px;align-items:flex-start}.phh{width:100%;font-size:11px}figure{margin:0;width:48mm}figure img{width:48mm;height:36mm;object-fit:cover;border-radius:4px;border:1px solid #ddd;display:block}figcaption{font-size:9px;color:#555;margin-top:2px}.brk{page-break-before:always;break-before:page}.bar{position:fixed;top:8px;right:8px;z-index:9;background:#fff;padding:8px 10px;border-radius:10px;box-shadow:0 4px 16px rgba(0,0,0,.3)}.bar button{padding:8px 14px;font-weight:700;cursor:pointer}@page{size:A4 landscape;margin:0}@media print{.bar{display:none}}`;
  let body=`<section class="pg cover"><div><div class="muted">TRACÉ / RCU-COMPAGNON · ${esc2(D.site.supplier||'')}${D.site.serie?' · série '+esc2(D.site.serie):''}</div><h1>Carnet de soudage et manchonnage</h1><div style="font-size:16px;font-weight:700">${esc2(D.site.name)}</div>${D.site.client?`<div>Client : ${esc2(D.site.client)}</div>`:''}
    <div class="kpi"><div><b>${D.lines.length}</b>ligne${D.lines.length>1?'s':''}</div><div><b>${fmt(totML)}</b>ml d'axe</div><div><b>${ws.length}</b>soudure${ws.length>1?'s':''} ${o.all?'au total':'documentées'}${o.all?'':' / '+D.welds.length}</div><div><b>${nMan}</b>manchonnée${nMan>1?'s':''}</div><div><b>${ws.filter(w=>w.extru).length}</b>manchon${ws.filter(w=>w.extru).length>1?'s':''} extrudé${ws.filter(w=>w.extru).length>1?'s':''}</div><div><b>${ws.reduce((t,w)=>t+w.photos.length,0)}</b>photos</div></div>
    <h3>Comment lire ce carnet</h3><div style="max-width:170mm">Une ligne par soudure, classée par ligne du réseau puis par PK (abscisse en mètres depuis le départ de la ligne), aller (A) et retour (R). Chaque soudure porte son <b>n°</b> : c'est le même n° qui figure sur le <b>${esc2(o.planTitle||'plan des soudures numérotées')}</b>${Object.keys(planches).length?' (colonne « Planche » = planche du plan où la trouver)':''} et qui nomme les <b>photos</b> (dossier Photos / ligne / n° de soudure). Les étapes : ① soudure (cordon), ② raccordement des fils de détection d'humidité (DH) avec la mesure, ③ manchon (rétracté ou extrudé, test de pression), ④ moussage.</div>
    ${D.marche?`<div class="muted" style="margin-top:8px">Tracé marché figé le ${dFR(D.marche.at)}${D.marche.by?' par '+esc2(D.marche.by):''} ; les modifications (TS, compris au forfait, pour mémoire) font l'objet du document « Modifications du tracé ».</div>`:''}</div>
    <div><h3>Intervenants</h3><table style="width:auto"><tr><th>Nom</th><th class="n">Soudures</th><th class="n">Fils + DH</th><th class="n">Manchons</th><th class="n">Moussages</th><th>Première intervention</th><th>Dernière</th></tr>${D.people.map(p=>`<tr><td>${esc2(p.name)}</td><td class="n">${p.n[1]||0}</td><td class="n">${p.n[2]||0}</td><td class="n">${p.n[3]||0}</td><td class="n">${p.n[4]||0}</td><td>${dFR(p.first)}</td><td>${dFR(p.last)}</td></tr>`).join('')||'<tr><td colspan="7" class="dim">aucune étape enregistrée</td></tr>'}</table>
    <div class="muted" style="margin-top:10px">Édité le ${dhFR(D.at)} par ${esc2(D.by)} — généré par l'application de suivi de chantier TRACÉ / RCU-COMPAGNON à partir des fiches de soudure saisies sur le terrain (horodatage et auteur de chaque étape).</div></div></section>`;
  lines.forEach(l=>{const lw=ws.filter(w=>w.line===l.id);
    body+=`<section class="pg brk"><h2>${esc2(l.name)}${l.dn?' — DN'+esc2(l.dn):''} <span class="dim" style="font-weight:400;font-size:12px">· ${fmt(l.len)} ml · ${lw.length} soudure${lw.length>1?'s':''}${l.parent?' · antenne de '+esc2((D.lines.find(x=>x.id===l.parent)||{}).name||l.parent):''}</span></h2>${miniPlan(l)}
     <table><tr><th>N°</th><th>Cond.</th><th class="n">PK (m)</th><th>DN</th>${Object.keys(planches).length?'<th>Planche</th>':''}<th>① Soudure</th><th>② Fils + DH</th><th>③ Manchon</th><th>④ Moussage</th><th>Statut</th><th class="n">Photos</th><th>Observations</th></tr>
     ${lw.map(w=>`<tr><td class="id"><b>${esc2(w.id)}</b></td><td>${w.cond==='A'?'aller':'retour'}</td><td class="n">${fmt(w.pk)}</td><td>${esc2(w.dn||'')}</td>${Object.keys(planches).length?`<td>${esc2(planches[w.id]||'—')}</td>`:''}<td>${stepTxt(w,1)}</td><td>${stepTxt(w,2)}</td><td>${stepTxt(w,3)}</td><td>${stepTxt(w,4)}</td><td>${esc2(w.statusLabel)}</td><td class="n">${w.photos.length||''}</td><td>${obs(w)}</td></tr>`).join('')}</table></section>`;
    if(o.photos!=='none'&&lw.some(w=>w.photos.length))body+=`<section class="pg brk"><h2>${esc2(l.name)} — photos</h2>${lw.map(phBlock).join('')}</section>`;});
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Carnet de soudage et manchonnage — ${esc(D.site.name)}</title><style>${css}</style></head><body><div class="bar"><button onclick="print()">🖨 Imprimer / enregistrer en PDF</button></div>${body}</body></html>`;}

/* ---------- 5. plan interactif hors ligne (un seul fichier HTML, photos par chemin relatif ou URL) ---------- */
export function viewerHTML(D,o={}){const src=o.photoSrc||((p)=>p.src);const esc2=esc;
  // niveaux de détail pré-dessinés (le fichier doit marcher hors ligne, sans le moteur de l'appli) : loin = axes + noms ; puis 1/1000, 1/400, 1/200, 1/80 avec les n°
  const LODS=[1,.4,.2,.08];
  const worlds=D.sheets.map(sh=>{const base=planWorld(D,sh.id,{s:.2,fond:o.fond,pk:true,ts:true,all:true});if(!base)return null;const [x0,y0,x1,y1]=base.bbox;const ext=Math.max(x1-x0,y1-y0,10);
    const fond=o.fond!==false&&sh.drawing&&A.drawingSVG?(()=>{try{const r=A.drawingSVG(sh.drawing,{k:1,texts:false,colors:false,op:1,fillOp:1});return r&&r.svg?`<g opacity=".45"${sh.ppm!==1?` transform="scale(${1/sh.ppm})"`:''}>${r.svg}</g>`:'';}catch(e){return '';}})():'';
    const far=planWorld(D,sh.id,{s:ext/600,fond:false,pk:false,ts:false,labels:false,glyphs:false,lineNames:true,nameRepeat:false,grid:false,all:true});
    const lods=LODS.map(sv=>({s:sv,svg:(planWorld(D,sh.id,{s:sv,fond:false,pk:true,ts:true,all:true,grid:sv>=.2})||{}).svg||''}));
    return {id:sh.id,name:sh.name,bbox:base.bbox,fond,far:far?far.svg:'',lods};}).filter(Boolean);
  const data={site:D.site,at:D.at,by:D.by,lines:D.lines.map(l=>({id:l.id,name:l.name,dn:l.dn,sheet:l.sheet,len:l.len,nW:l.nW,nDoc:l.nDoc})),welds:D.welds.map(w=>({...w,photos:w.photos.map(p=>({...p,src:src(p,w)}))})),ts:D.ts,status:Object.fromEntries(Object.entries(A.STATUS).map(([k,v])=>[k,{label:v.label,color:v.color}])),stepName:STEP_NAME};
  const json=JSON.stringify(data).replace(/<\/script/gi,'<\\/script');
  const css=`*{box-sizing:border-box}html,body{margin:0;height:100%;font:13px system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#111;background:#ecebe5}#top{display:flex;gap:8px;align-items:center;padding:6px 10px;background:#0b0b0b;color:#fff;flex-wrap:wrap}#top b{font-size:14px}#top input,#top select{padding:5px 8px;border-radius:8px;border:1px solid #444;font-size:13px}#top label{display:inline-flex;align-items:center;gap:4px;font-size:12px;white-space:nowrap}#wrap{display:flex;height:calc(100% - 44px)}#map{flex:1;position:relative;overflow:hidden;background:#f4f3ee;touch-action:none}#map svg{width:100%;height:100%;display:block;cursor:grab}#map svg.drag{cursor:grabbing}#side{width:360px;max-width:45%;overflow:auto;background:#fff;border-left:1px solid #ccc;padding:10px}#side h2{font-size:16px;margin:0 0 6px}#side h3{font-size:13px;margin:12px 0 4px;border-bottom:1px solid #ddd;padding-bottom:2px}#side table{border-collapse:collapse;width:100%;font-size:12px}#side td,#side th{border:1px solid #ddd;padding:3px 5px;text-align:left;vertical-align:top}#side th{background:#f1f0eb}.ph{display:flex;flex-wrap:wrap;gap:6px}.ph figure{margin:0;width:105px}.ph img{width:105px;height:78px;object-fit:cover;border-radius:5px;border:1px solid #ddd;display:block;cursor:zoom-in}.ph figcaption{font-size:10px;color:#555}.tag{display:inline-block;border-radius:999px;padding:1px 8px;color:#fff;font-weight:700;font-size:11px}.hot{color:#b3261e;font-weight:700}.dim{color:#666}.row{cursor:pointer}.row:hover{background:#f6f5f0}circle.w{cursor:pointer}circle.w.sel{stroke:#1c3d6b!important;stroke-width:.6px!important}circle.w.hid{display:none}.hint{color:#aaa;font-size:11.5px}#zoomb{position:absolute;right:10px;top:10px;display:flex;flex-direction:column;gap:4px}#zoomb button{width:34px;height:34px;border-radius:8px;border:1px solid #999;background:#fff;font-size:18px;cursor:pointer}@media(max-width:700px){#wrap{flex-direction:column}#side{width:100%;max-width:none;height:45%;border-left:0;border-top:1px solid #ccc}}`;
  const js=`const D=${json};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dFR=x=>x?new Date(x).toLocaleDateString('fr-FR'):'';const dhFR=x=>x?new Date(x).toLocaleDateString('fr-FR')+' '+new Date(x).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'';const fmt=n=>Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:1});
const WORLDS=${JSON.stringify(worlds).replace(/<\/script/gi,'<\\/script')};let cur=0;const byId={};D.welds.forEach(w=>byId[w.id]=w);let sel=null;const svg=$('#svg');let vb=[0,0,100,100];
function show(i){cur=i;const W=WORLDS[i];$('#fond').innerHTML=W.fond||'';$('#far').innerHTML=W.far;$('#lods').innerHTML=W.lods.map((L,k)=>'<g class="lod" data-s="'+L.s+'" style="display:none">'+L.svg+'</g>').join('');const [x0,y0,x1,y1]=W.bbox;const r=svg.clientWidth/Math.max(1,svg.clientHeight);let w=x1-x0,h=y1-y0;if(w/h<r)w=h*r;else h=w/r;vb=[x0-(w-(x1-x0))/2,y0-(h-(y1-y0))/2,w,h];apply();}
// niveau de détail : le plus fin dont les n° restent lisibles (police 2 mm·s·k ≥ 9 px) ; en dessous de k = 4,5 px/m : vue d'ensemble sans n°
function apply(){svg.setAttribute('viewBox',vb.join(' '));const k=svg.clientWidth/vb[2];const lods=[...document.querySelectorAll('#lods .lod')];let pick=null;lods.forEach(g=>{const sv=+g.dataset.s;if(2*sv*k>=9&&(pick===null||sv<+pick.dataset.s))pick=g;});lods.forEach(g=>g.style.display=g===pick?'':'none');$('#far').style.display=pick?'none':'';ring();applyFilter();}
let drag=null;svg.addEventListener('pointerdown',e=>{svg.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,vb:vb.slice(),moved:false};svg.classList.add('drag');});
svg.addEventListener('pointermove',e=>{if(!drag)return;const k=svg.clientWidth/vb[2];const dx=(e.clientX-drag.x)/k,dy=(e.clientY-drag.y)/k;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)>3)drag.moved=true;vb=[drag.vb[0]-dx,drag.vb[1]-dy,drag.vb[2],drag.vb[3]];svg.setAttribute('viewBox',vb.join(' '));});
svg.addEventListener('pointerup',e=>{const moved=drag&&drag.moved;drag=null;svg.classList.remove('drag');if(!moved){const c=e.target.closest&&e.target.closest('circle.w');if(c)select(c.dataset.w);}apply();});
svg.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.clientX,e.clientY,e.deltaY<0?1/1.25:1.25);},{passive:false});
function zoomAt(cx,cy,f){const r=svg.getBoundingClientRect();const px=vb[0]+(cx-r.left)/r.width*vb[2],py=vb[1]+(cy-r.top)/r.height*vb[3];vb=[px-(px-vb[0])*f,py-(py-vb[1])*f,vb[2]*f,vb[3]*f];apply();}
$('#zin').onclick=()=>{const r=svg.getBoundingClientRect();zoomAt(r.left+r.width/2,r.top+r.height/2,1/1.5);};$('#zout').onclick=()=>{const r=svg.getBoundingClientRect();zoomAt(r.left+r.width/2,r.top+r.height/2,1.5);};$('#zfit').onclick=()=>show(cur);
// pincement (deux doigts)
const pts=new Map();svg.addEventListener('pointerdown',e=>pts.set(e.pointerId,[e.clientX,e.clientY]));svg.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;const prev=[...pts.values()];pts.set(e.pointerId,[e.clientX,e.clientY]);if(pts.size===2){drag=null;const cur2=[...pts.values()];const d0=Math.hypot(prev[0][0]-prev[1][0],prev[0][1]-prev[1][1]),d1=Math.hypot(cur2[0][0]-cur2[1][0],cur2[0][1]-cur2[1][1]);if(d0>0&&d1>0)zoomAt((cur2[0][0]+cur2[1][0])/2,(cur2[0][1]+cur2[1][1])/2,d0/d1);}});['pointerup','pointercancel'].forEach(t=>svg.addEventListener(t,e=>pts.delete(e.pointerId)));
function center(w,k){const [x,y]=w.pos;const kk=k||Math.max(svg.clientWidth/vb[2],6);const vw=svg.clientWidth/kk,vh=svg.clientHeight/kk;vb=[x-vw/2,y-vh/2,vw,vh];apply();}
function ring(){let r=document.getElementById('selring');if(!sel){if(r)r.remove();return;}const w=byId[sel];if(!w)return;if(!r){r=document.createElementNS('http://www.w3.org/2000/svg','circle');r.id='selring';r.setAttribute('fill','none');r.setAttribute('stroke','#1c3d6b');r.setAttribute('stroke-width','3');r.setAttribute('vector-effect','non-scaling-stroke');r.style.pointerEvents='none';document.getElementById('inner').appendChild(r);}const k=svg.clientWidth/vb[2];r.setAttribute('cx',w.pos[0]);r.setAttribute('cy',w.pos[1]);r.setAttribute('r',(13/k).toFixed(3));}
function select(id,noCenter){sel=id;const w=byId[id];document.querySelectorAll('circle.w.sel').forEach(c=>c.classList.remove('sel'));if(!w){panelHome();return;}const si=WORLDS.findIndex(W=>W.id===(D.lines.find(l=>l.id===w.line)||{}).sheet);if(si>=0&&si!==cur)show(si);document.querySelectorAll('circle.w[data-w="'+CSS.escape(id)+'"]').forEach(c=>c.classList.add('sel'));if(!noCenter)center(w);ring();panelWeld(w);}
function stepRow(w,n){const s=w.steps[n];const name=D.stepName[n];if(!s||!s.done){const ev=w.events.find(e=>(n===1&&e.type==='soudee')||(n===3&&e.type==='manchonnee'));return '<tr><td>'+n+' '+name+'</td><td>'+(ev?dhFR(ev.at)+'<br><span class=dim>'+esc(ev.by)+'</span>':'<span class=dim>—</span>')+'</td><td>'+(ev&&ev.data&&ev.data.manchon==='extrude'?'<span class=hot>extrudé</span>':'')+'</td></tr>';}
  let det='';if(n===1&&s.proc)det=esc(s.proc);if(n===2&&s.dh){const d=s.dh;det=[d.meas!=null&&d.meas!==''?'R mesuré '+fmt(d.meas)+' Ω':'',d.expected!=null&&d.expected!==''?'attendu '+fmt(d.expected)+' Ω':'',d.iso!=null?'isolement '+fmt(d.iso)+' MΩ':'',d.closure?esc(d.closure):''].filter(Boolean).join(' · ');}if(n===3)det=(s.type==='extrude'?'<span class=hot>manchon extrudé</span>'+(s.cause?' — '+esc(s.cause):''):'manchon rétracté')+(s.press?' · test de pression ✓':'');
  return '<tr><td>'+n+' '+name+'</td><td>'+dhFR(s.at)+'<br><span class=dim>'+esc(s.by)+'</span></td><td>'+det+'</td></tr>';}
function panelWeld(w){const st=D.status[w.status]||{label:w.status,color:'#888'};const L=D.lines.find(l=>l.id===w.line)||{};const obs=[w.extra?'soudure supplémentaire':'',w.fc?'fausse coupe'+(w.dev?' '+fmt(w.dev)+'°':''):'',w.teeOut?'sortie de té':'',w.sleeveWith?'même manchon que '+esc(w.sleeveWith):'',w.wire==='inversion'?'<span class=hot>inversion de fils</span>':w.wire==='raccorde'?'fils raccordés':'',w.note?esc(w.note):''].filter(Boolean);
  const ts=D.ts.filter(t=>t.weldId===w.id);
  $('#side').innerHTML='<div class=hint><a href="#" id="back">← réseau</a></div><h2>'+esc(w.id)+' <span class=tag style="background:'+st.color+'">'+esc(st.label)+'</span></h2><div>'+esc(w.lineName)+' · <b>'+(w.cond==='A'?'aller':'retour')+'</b> · PK <b>'+fmt(w.pk)+' m</b>'+(w.dn?' · DN'+esc(w.dn):'')+'</div>'
   +'<h3>Étapes</h3><table><tr><th>Étape</th><th>Quand · qui</th><th>Détail</th></tr>'+[1,2,3,4].map(n=>stepRow(w,n)).join('')+'</table>'
   +(obs.length?'<h3>Observations</h3><div>'+obs.join(' · ')+'</div>':'')
   +(ts.length?'<h3>Modifications</h3>'+ts.map(t=>'<div><span class=tag style="background:'+t.col+'">'+esc(t.etatLabel)+'</span> '+(t.devis?'devis '+esc(t.devis)+' · ':'')+esc(t.desig||t.label)+(t.qty?' <span class=dim>('+esc(t.qty)+')</span>':'')+'</div>').join(''):'')
   +'<h3>Photos ('+w.photos.length+')</h3>'+(w.photos.length?'<div class=ph>'+w.photos.map(p=>'<figure><a href="'+esc(p.src)+'" target="_blank" rel="noopener"><img src="'+esc(p.src)+'" loading="lazy" alt=""></a><figcaption>'+esc(D.stepName[p.step]||'photo')+(p.at?' · '+dhFR(p.at):'')+(p.by?' · '+esc(p.by):'')+'</figcaption></figure>').join('')+'</div>':'<div class=dim>aucune</div>')
   +'<h3>Ligne — '+esc(L.name||'')+'</h3>'+lineList(w.line);
  $('#back').onclick=e=>{e.preventDefault();panelHome();};bindRows();}
function lineList(id){const ws=D.welds.filter(w=>w.line===id).sort((a,b)=>a.pk-b.pk||a.cond.localeCompare(b.cond));return '<table><tr><th>N°</th><th>Cond.</th><th>PK</th><th>Statut</th></tr>'+ws.map(w=>'<tr class=row data-w="'+esc(w.id)+'"'+(w.id===sel?' style="background:#eef3fb"':'')+'><td><b>'+esc(w.id)+'</b></td><td>'+(w.cond==='A'?'A':'R')+'</td><td>'+fmt(w.pk)+'</td><td><span class=tag style="background:'+((D.status[w.status]||{}).color||'#888')+'">'+esc((D.status[w.status]||{}).label||'')+'</span></td></tr>').join('')+'</table>';}
function bindRows(){document.querySelectorAll('#side .row').forEach(r=>r.onclick=()=>select(r.dataset.w));}
function panelHome(){sel=null;ring();document.querySelectorAll('circle.w.sel').forEach(c=>c.classList.remove('sel'));const n=D.welds.length,d=D.welds.filter(w=>w.doc).length;
  $('#side').innerHTML='<h2>'+esc(D.site.name)+'</h2><div class=dim>'+n+' soudures · '+d+' documentées · export du '+dhFR(D.at)+' par '+esc(D.by)+'</div><div class=hint style="margin:6px 0">Touche une soudure sur le plan (ou une ligne du tableau) : fiche complète, étapes horodatées, photos. Molette / pincement pour zoomer, glisser pour déplacer.</div>'
   +'<h3>Lignes</h3><table><tr><th>Ligne</th><th>DN</th><th>ml</th><th>Soudures</th></tr>'+D.lines.map(l=>'<tr class=row data-l="'+esc(l.id)+'"><td><b>'+esc(l.name)+'</b></td><td>'+esc(l.dn||'')+'</td><td>'+fmt(l.len)+'</td><td>'+l.nDoc+' / '+l.nW+'</td></tr>').join('')+'</table>'
   +'<h3>Avancement</h3>'+Object.entries(D.status).map(([k,v])=>{const c=D.welds.filter(w=>w.status===k).length;return c?'<div><span class=tag style="background:'+v.color+'">'+esc(v.label)+'</span> '+c+'</div>':'';}).join('')
   +(D.ts.length?'<h3>Modifications ('+D.ts.length+')</h3>'+D.ts.map(t=>'<div><span class=tag style="background:'+t.col+'">'+esc(t.etatLabel)+'</span> '+(t.devis?'devis '+esc(t.devis)+' · ':'')+esc(t.desig||t.label)+'</div>').join(''):'');
  document.querySelectorAll('#side [data-l]').forEach(r=>r.onclick=()=>{const l=D.lines.find(x=>x.id===r.dataset.l);const ws=D.welds.filter(w=>w.line===l.id);$('#side').innerHTML='<div class=hint><a href="#" id="back">← réseau</a></div><h2>'+esc(l.name)+'</h2><div class=dim>DN'+esc(l.dn||'')+' · '+fmt(l.len)+' ml · '+ws.length+' soudures</div>'+lineList(l.id);$('#back').onclick=e=>{e.preventDefault();panelHome();};bindRows();if(ws.length){const xs=ws.map(w=>w.pos[0]),ys=ws.map(w=>w.pos[1]);const x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys);const r=svg.clientWidth/svg.clientHeight;let w=Math.max(10,x1-x0)*1.3,h=Math.max(10,y1-y0)*1.3;if(w/h<r)w=h*r;else h=w/r;vb=[(x0+x1)/2-w/2,(y0+y1)/2-h/2,w,h];apply();}});}
function applyFilter(){const st=$('#fst').value;document.querySelectorAll('circle.w').forEach(c=>{const w=byId[c.dataset.w];c.classList.toggle('hid',!!(w&&st!=='all'&&w.status!==st));});}
$('#fst').onchange=applyFilter;$('#q').onkeydown=e=>{if(e.key!=='Enter')return;const v=$('#q').value.trim().toUpperCase();let id=Object.keys(byId).find(k=>k.toUpperCase()===v)||Object.keys(byId).find(k=>k.toUpperCase().replace(/\\D/g,'')===v.replace(/\\D/g,'')&&v.replace(/\\D/g,''));if(id)select(id);else alert('Soudure introuvable : '+v);};
const fsel=$('#fsh');WORLDS.forEach((W,i)=>{const o=document.createElement('option');o.value=i;o.textContent=W.name||('feuille '+(i+1));fsel.appendChild(o);});fsel.style.display=WORLDS.length>1?'':'none';fsel.onchange=()=>show(+fsel.value);
Object.entries(D.status).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.label;$('#fst').appendChild(o);});
window.addEventListener('resize',apply);show(0);panelHome();window.VIEW={select,show,data:D};`;
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plan interactif — ${esc2(D.site.name)}</title><style>${css}</style></head><body>
  <div id="top"><b>${esc2(D.site.name)}</b><span class="hint">plan interactif · ${D.welds.length} soudures · ${dFR(D.at)}</span><input id="q" placeholder="n° de soudure ↵" size="14"><select id="fst"><option value="all">tous les statuts</option></select><select id="fsh" style="display:none"></select></div>
  <div id="wrap"><div id="map"><svg id="svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" font-family="Arial,Helvetica,sans-serif"><g id="inner"><g id="fond"></g><g id="far"></g><g id="lods"></g></g></svg><div id="zoomb"><button id="zin" title="zoom +">＋</button><button id="zout" title="zoom −">−</button><button id="zfit" title="tout voir">⤢</button></div></div><div id="side"></div></div>
  <script>${js}</script></body></html>`;}

/* ---------- 6. CSV / JSON ---------- */
export function weldsCSV(D,o={}){const ws=weldsOf(D,o).slice().sort(sortW);const rows=[['N°','Ligne','Conduite','PK (m)','DN','Statut','Soudure le','Soudeur','Procédé','Fils + DH le','Par','R mesuré (Ω)','R attendu (Ω)','Isolement (MΩ)','Manchon le','Manchonneur','Manchon','Cause extrusion','Test pression','Moussage le','Par','Fausse coupe (°)','Soudure supplémentaire','Même manchon que','Fils','Photos','Note']];
  ws.forEach(w=>{const s=n=>w.steps[n]||{};const d=s(2).dh||{};rows.push([w.id,w.lineName,w.cond==='A'?'aller':'retour',w.pk,w.dn||'',w.statusLabel,dhFR(s(1).at),s(1).by||'',s(1).proc||'',dhFR(s(2).at),s(2).by||'',d.meas??'',d.expected??'',d.iso??'',dhFR(s(3).at),s(3).by||'',s(3).done?(s(3).type==='extrude'?'extrudé':'rétracté'):'',s(3).cause||'',s(3).press?'oui':'',dhFR(s(4).at),s(4).by||'',w.fc?w.dev:'',w.extra?'oui':'',w.sleeveWith||'',w.wire,w.photos.map(p=>p.file).join(' | '),w.note]);});
  return '﻿'+rows.map(r=>r.map(v=>{const x=String(v??'');return /[;"\n]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x;}).join(';')).join('\r\n');}

/* ---------- 7. dossier DOE (zip) ---------- */
const b64ToU8=d=>{const i=d.indexOf(',');const b=atob(d.slice(i+1));const u=new Uint8Array(b.length);for(let k=0;k<b.length;k++)u[k]=b.charCodeAt(k);return u;};
async function fetchBytes(src){if(!src)throw new Error('vide');if(src.startsWith('data:'))return b64ToU8(src);const r=await fetch(src);if(!r.ok)throw new Error('HTTP '+r.status);return new Uint8Array(await r.arrayBuffer());}
async function pool(items,n,fn){let i=0;const workers=Array.from({length:Math.min(n,items.length)},async()=>{while(i<items.length){const k=i++;await fn(items[k],k);}});await Promise.all(workers);}
const extOf=(name,fallback)=>{const m=/\.([a-z0-9]{2,5})$/i.exec(name||'');return m?'.'+m[1].toLowerCase():fallback;};
// o : {parts:{carnet,plan,photos,viewer,ts,qse,admin,data}, all, photos, scale, format, orient, fond, pk, ts, onProgress(p), sink(chunk,final)}
export async function zipDOE(D,o={}){const P=Object.assign({carnet:true,plan:true,photos:true,viewer:true,ts:true,qse:true,admin:true,data:true},o.parts||{});const prog=o.onProgress||(()=>{});const chunks=[];let total=0;
  const zip=new Zip((err,chunk,final)=>{if(err){console.warn(err);return;}total+=chunk.length;if(o.sink)o.sink(chunk,final);else chunks.push(chunk);});
  const addText=(name,txt)=>{const f=new ZipDeflate(name,{level:6});zip.add(f);f.push(strToU8(txt),true);};const addBin=(name,u8)=>{const f=new ZipPassThrough(name);zip.add(f);f.push(u8,true);};
  const root=`DOE_${slug(D.site.name)}_${D.at.slice(0,10)}/`;const ws=weldsOf(D,o);const report={photosOk:0,photosKo:0,adminOk:0,adminKo:0,files:[]};
  const photoPath=(p,w)=>`02_Photos/${slug(w.lineName)}/${slug(w.id)}/${p.file}`;
  const relFromDoc=(p,w)=>'../'+photoPath(p,w); // depuis 01_Carnet/ ou 03_Plan_interactif/
  let planches={};let planR=null;
  if(P.plan){planR=planPrintHTML(D,{scale:o.scale,format:o.format,orient:o.orient,fond:o.fond,pk:o.pk,ts:o.ts,all:o.all});planches=planR.planches;if(planR.html){addText(root+'01_Carnet/Plan_soudures_numerotees.html',planR.html);report.files.push('01_Carnet/Plan_soudures_numerotees.html');}}
  if(P.carnet){addText(root+'01_Carnet/Carnet_soudage_manchonnage.html',carnetHTML(D,{all:o.all,photos:P.photos?(o.photos||'all'):'none',photoSrc:P.photos?relFromDoc:undefined,planches,planTitle:'plan des soudures numérotées (fichier Plan_soudures_numerotees.html)'}));report.files.push('01_Carnet/Carnet_soudage_manchonnage.html');}
  if(P.viewer){addText(root+'03_Plan_interactif/Plan_interactif.html',viewerHTML(D,{fond:o.fond,photoSrc:P.photos?relFromDoc:undefined}));report.files.push('03_Plan_interactif/Plan_interactif.html');}
  if(P.ts){let h='';try{h=A.ts.exportHTML();}catch(e){console.warn(e);}if(h){addText(root+'04_Modifications/Modifications_du_trace.html',h);report.files.push('04_Modifications/Modifications_du_trace.html');}}
  if(P.qse){const NET=A.net();((NET.qse&&NET.qse.docs)||[]).forEach((d,i)=>{try{const h=A.qseSheetHTML(d);if(h){const n=`05_QSE/${String(i+1).padStart(2,'0')}_${slug(d.title||d.type)}.html`;addText(root+n,h);report.files.push(n);}}catch(e){console.warn(e);}});}
  if(P.data){addText(root+'donnees/soudures.csv',weldsCSV(D,o));const light={...D,sheets:D.sheets.map(s=>({id:s.id,name:s.name,ppm:s.ppm,type:s.type,lines:s.lines})),welds:ws.map(w=>({...w,photos:w.photos.map(p=>({...p,src:undefined,path:photoPath(p,w)}))})),admin:D.admin.map(a=>({...a,data:undefined}))};addText(root+'donnees/doe.json',JSON.stringify(light));report.files.push('donnees/soudures.csv','donnees/doe.json');}
  // photos (le gros du volume) : 4 téléchargements en parallèle, JPEG stockés tels quels
  if(P.photos){const jobs=[];ws.forEach(w=>{let ph=w.photos;if(o.photos==='last'){const seen={};ph=ph.slice().reverse().filter(p=>{if(seen[p.step])return false;seen[p.step]=1;return true;}).reverse();}ph.forEach(p=>jobs.push({p,w}));});let done=0;prog({done:0,total:jobs.length,label:'photos'});
    await pool(jobs,4,async({p,w})=>{try{const u8=await fetchBytes(p.src);addBin(root+photoPath(p,w),u8);report.photosOk++;}catch(e){report.photosKo++;p.missing=true;}done++;prog({done,total:jobs.length,label:'photos'});});}
  if(P.admin&&D.admin.length){let done=0;prog({done:0,total:D.admin.length,label:'dossier administratif'});
    await pool(D.admin,3,async a=>{try{const u8=await fetchBytes(a.url||a.data);const ext=extOf(a.name,a.url&&/\.pdf(\?|$)/i.test(a.url)?'.pdf':'');const base=slug(a.name.replace(/\.[a-z0-9]{2,5}$/i,''));addBin(root+`06_Dossier_administratif/${slug(a.catLabel)}/${base}${ext}`,u8);report.adminOk++;}catch(e){report.adminKo++;a.missing=true;}done++;prog({done,total:D.admin.length,label:'dossier administratif'});});}
  // sommaire
  const li=(href,txt,sub)=>`<li><a href="${esc(href)}">${esc(txt)}</a>${sub?` <span class="dim">— ${sub}</span>`:''}</li>`;
  let idx=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>DOE — ${esc(D.site.name)}</title><style>body{font-family:system-ui,sans-serif;margin:28px auto;max-width:860px;color:#111;line-height:1.45}h1{margin:0 0 4px}.dim{color:#666}li{margin:6px 0}.box{border:1px solid #ccc;border-radius:10px;padding:10px 14px;margin:12px 0;background:#faf9f5}code{background:#eee;padding:1px 5px;border-radius:4px}</style></head><body><h1>Dossier des ouvrages exécutés — ${esc(D.site.name)}</h1><div class="dim">Réseau de chaleur pré-isolé · ${esc(D.site.supplier||'')}${D.site.serie?' · série '+esc(D.site.serie):''} · généré le ${dhFR(D.at)} par ${esc(D.by)} avec TRACÉ / RCU-COMPAGNON</div>
  <div class="box"><b>${D.lines.length}</b> ligne${D.lines.length>1?'s':''} · <b>${ws.length}</b> soudure${ws.length>1?'s':''}${o.all?'':' documentées (sur '+D.welds.length+')'} · <b>${report.photosOk}</b> photo${report.photosOk>1?'s':''}${report.photosKo?` · <span style="color:#b3261e">${report.photosKo} photo${report.photosKo>1?'s':''} non récupérée${report.photosKo>1?'s':''} (hors connexion au moment de l'export ?)</span>`:''}${D.nExtru?` · ${D.nExtru} manchon${D.nExtru>1?'s':''} extrudé${D.nExtru>1?'s':''}`:''}${D.ts.length?` · ${D.ts.length} modification${D.ts.length>1?'s':''} du tracé`:''}</div>
  <h2>Contenu</h2><ul>${P.carnet?li('01_Carnet/Carnet_soudage_manchonnage.html','Carnet de soudage et manchonnage','une ligne par soudure, étapes horodatées, DH, photos ; ouvrir puis « Imprimer » → enregistrer en PDF'):''}${P.plan&&planR&&planR.html?li('01_Carnet/Plan_soudures_numerotees.html','Plan des soudures numérotées',(planR.nPages+' page'+(planR.nPages>1?'s':'')+' · '+esc(o.format==='auto'?'une planche':(o.format||'A3'))+' · 1/'+(o.scale||200)+' ; ouvrir puis « Imprimer » → PDF (le format de page est déjà réglé)'+(planR.note?' · '+esc(planR.note):''))):''}${P.photos?li('02_Photos/','Photos','classées par ligne puis par n° de soudure ; nom = n° de soudure _ étape _ date'):''}${P.viewer?li('03_Plan_interactif/Plan_interactif.html','Plan interactif','le plan comme dans l\'application : touche une soudure → sa fiche et ses photos ; fonctionne hors ligne depuis ce dossier'):''}${P.ts&&report.files.some(f=>f.startsWith('04_'))?li('04_Modifications/Modifications_du_trace.html','Modifications du tracé','tracé marché figé, écarts, TS / compris au forfait / pour mémoire'):''}${P.qse&&report.files.some(f=>f.startsWith('05_'))?li('05_QSE/','QSE','accueils chantier, quarts d\'heure sécurité, documents émargés ('+report.files.filter(f=>f.startsWith('05_')).length+')'):''}${P.admin&&D.admin.length?li('06_Dossier_administratif/','Dossier administratif',report.adminOk+' document'+(report.adminOk>1?'s':'')+(report.adminKo?' · <span style="color:#b3261e">'+report.adminKo+' non récupéré'+(report.adminKo>1?'s':'')+'</span>':'')):''}${P.data?li('donnees/soudures.csv','Données','soudures.csv (Excel, séparateur « ; ») et doe.json (pour un autre logiciel)'):''}</ul>
  <h2>Obtenir les PDF</h2><div>Les documents sont fournis en HTML (vectoriel, à l'échelle) : ouvrir le fichier dans Chrome ou Edge, bouton <b>🖨 Imprimer</b>, destination <b>Enregistrer au format PDF</b>. Pour le plan, le format de page (${esc(o.format==='auto'?'une seule planche à la taille du réseau':(o.format||'A3'))}) et l'échelle (1/${o.scale||200}) sont déjà dans le document : ne pas cocher « ajuster à la page ».</div>
  <h2>Intervenants</h2><table border="1" cellpadding="4" style="border-collapse:collapse"><tr><th>Nom</th><th>Soudures</th><th>Fils + DH</th><th>Manchons</th><th>Moussages</th><th>Du</th><th>Au</th></tr>${D.people.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.n[1]||0}</td><td>${p.n[2]||0}</td><td>${p.n[3]||0}</td><td>${p.n[4]||0}</td><td>${dFR(p.first)}</td><td>${dFR(p.last)}</td></tr>`).join('')}</table>
  ${D.admin.length?`<h2>Pièces du dossier administratif</h2><ul>${D.admin.map(a=>`<li>${esc(a.catLabel)} — ${esc(a.name)} <span class="dim">(${esc(a.by)} · ${dFR(a.at)})${a.missing?' · <span style="color:#b3261e">non récupéré</span>':''}</span></li>`).join('')}</ul>`:''}
  </body></html>`;addText(root+'Lisez-moi.html',idx);report.files.push('Lisez-moi.html');
  zip.end();const blob=o.sink?null:new Blob(chunks,{type:'application/zip'});return {blob,size:total,report,name:`DOE_${slug(D.site.name)}_${D.at.slice(0,10)}.zip`,root};}

/* ---------- 8. onglet Export ---------- */
const OPT_DEF={all:false,photos:'all',scale:200,format:'A3',orient:'paysage',fond:true,pk:true,ts:true,parts:{carnet:true,plan:true,photos:true,viewer:true,ts:true,qse:true,admin:true,data:true}};
export function doeOpts(){const S=A.state;if(!S.doeOpts)S.doeOpts=JSON.parse(JSON.stringify(OPT_DEF));return S.doeOpts;}
function openHTML(html){const w=window.open('about:blank');if(!w){A.toast('Autorise l\'ouverture de fenêtres pour l\'export');return false;}w.document.write(html);w.document.close();return true;}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1500);}
const sizeTxt=n=>n>1024*1024*1024?(n/1024/1024/1024).toFixed(2)+' Go':n>1024*1024?(n/1024/1024).toFixed(1)+' Mo':Math.round(n/1024)+' Ko';
export function renderExport(){const el=document.getElementById('exportview');if(!el)return;const D=doeData();const o=doeOpts();
  if(!D){el.innerHTML='<h2 class="vt">Export</h2><div class="card muted">Aucun chantier ouvert.</div>';return;}
  const ck=(k,lab,sub,n)=>`<label class="doeCk"><input type="checkbox" data-part="${k}" ${o.parts[k]?'checked':''}><span><b>${lab}</b>${n!==undefined?` <span class="dim">(${n})</span>`:''}<br><span class="hint">${sub}</span></span></label>`;
  const nPh=weldsOf(D,o).reduce((t,w)=>t+w.photos.length,0);const est=nPh*0.3;
  el.innerHTML=`<h2 class="vt">Export — ${esc(D.site.name)}</h2>
  <div class="hint" style="margin-bottom:8px">Tout est fabriqué ici, dans l'appli, à partir des fiches de soudure saisies sur le terrain. Les documents sortent en HTML prêts à imprimer (→ PDF en un clic dans Chrome / Edge), le plan est vectoriel et à l'échelle.</div>
  <div class="card"><h3 style="margin-top:0">📁 Dossier DOE complet (zip)</h3>
   <div class="doeParts">${ck('carnet','Carnet de soudage et manchonnage','une ligne par soudure : qui, quand, procédé, fils + DH, manchon (rétracté / extrudé), moussage, observations ; renvoi à la planche du plan')}${ck('plan','Plan des soudures numérotées','le tracé avec chaque soudure et son n°, en planches à l\'échelle (format et échelle ci-dessous)')}${ck('photos','Photos classées par n° de soudure','dossier Photos / ligne / n° de soudure ; nom = n° _ étape _ date',nPh)}${ck('viewer','Plan interactif hors ligne','un fichier .html : le plan comme ici, touche une soudure → sa fiche et ses photos')}${ck('ts','Modifications du tracé','tracé marché figé, écarts, TS / compris / pour mémoire',D.ts.length)}${ck('qse','QSE','accueils chantier, quarts d\'heure, documents émargés (feuilles d\'émargement)',D.qse.length)}${ck('admin','Dossier administratif','les documents déposés dans l\'onglet Dossier, classés par catégorie',D.admin.length)}${ck('data','Données','soudures.csv (Excel) + doe.json')}</div>
   <div class="doeOpts"><div><label class="f">Soudures</label><select class="f" data-opt="all"><option value="0" ${!o.all?'selected':''}>documentées seulement (${D.nDoc})</option><option value="1" ${o.all?'selected':''}>toutes (${D.welds.length})</option></select></div>
    <div><label class="f">Photos</label><select class="f" data-opt="photos"><option value="all" ${o.photos==='all'?'selected':''}>toutes</option><option value="last" ${o.photos==='last'?'selected':''}>la dernière de chaque étape</option><option value="none" ${o.photos==='none'?'selected':''}>aucune</option></select></div>
    <div><label class="f">Plan : format</label><select class="f" data-opt="format">${['A4','A3','A2','A1','A0','auto'].map(f=>`<option value="${f}" ${o.format===f?'selected':''}>${f==='auto'?'une seule planche (taille du réseau)':f}</option>`).join('')}</select></div>
    <div><label class="f">Échelle</label><select class="f" data-opt="scale">${[100,200,250,500,1000].map(s=>`<option value="${s}" ${+o.scale===s?'selected':''}>1/${s}</option>`).join('')}</select></div>
    <div><label class="f">Orientation</label><select class="f" data-opt="orient"><option value="paysage" ${o.orient!=='portrait'?'selected':''}>paysage</option><option value="portrait" ${o.orient==='portrait'?'selected':''}>portrait</option></select></div>
    <div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;padding-top:16px"><label><input type="checkbox" data-opt="fond" ${o.fond?'checked':''}> fond de plan</label><label><input type="checkbox" data-opt="pk" ${o.pk?'checked':''}> PK</label><label><input type="checkbox" data-opt="ts" ${o.ts?'checked':''}> modifications sur le plan</label></div></div>
   <div class="hint" style="margin:6px 0">Taille estimée : ~${sizeTxt(est*1024*1024)} (${nPh} photo${nPh>1?'s':''} × ~300 Ko) + quelques Mo de documents. Les photos sont téléchargées depuis le serveur : reste connecté pendant la fabrication.</div>
   <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><button class="btn primary" id="doeZip">📁 Fabriquer le dossier DOE</button><div id="doeProg" class="hint" style="flex:1"></div></div></div>
  <div class="card"><h3 style="margin-top:0">À la carte</h3><div style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn" id="doeCarnet">📕 Carnet de soudage (imprimable)</button><button class="btn" id="doePlan">🗺 Plan des soudures numérotées (imprimable)</button><button class="btn" id="doeViewer">🧭 Plan interactif (.html)</button><button class="btn" id="doeTs">📝 Modifications du tracé</button><button class="btn" id="doeCsv">⤓ CSV soudures</button></div>
   <div class="hint" style="margin-top:6px">Le carnet et le plan s'ouvrent dans un nouvel onglet avec un bouton « Imprimer / enregistrer en PDF ». Le plan interactif se télécharge ; seul, il affiche les photos depuis le serveur (connexion) — dans le dossier DOE, elles sont à côté et tout marche hors ligne.</div></div>
  <div class="card"><h3 style="margin-top:0">Ce que contient ce chantier</h3><div class="kv" style="font-size:12.5px"><span><b>${D.lines.length}</b> ligne${D.lines.length>1?'s':''}</span><span><b>${D.nDoc}</b> soudure${D.nDoc>1?'s':''} documentée${D.nDoc>1?'s':''} / ${D.welds.length}</span><span><b>${D.nPhotos}</b> photo${D.nPhotos>1?'s':''}</span><span><b>${D.nExtru}</b> manchon${D.nExtru>1?'s':''} extrudé${D.nExtru>1?'s':''}</span><span><b>${D.ts.length}</b> modification${D.ts.length>1?'s':''}</span><span><b>${D.qse.length}</b> doc${D.qse.length>1?'s':''} QSE</span><span><b>${D.admin.length}</b> pièce${D.admin.length>1?'s':''} au dossier</span></div>
   ${D.people.length?`<table class="rc" style="margin-top:8px"><tr><th style="text-align:left">Intervenant</th><th>Soudures</th><th>Fils + DH</th><th>Manchons</th><th>Moussages</th><th>Du</th><th>Au</th></tr>${D.people.map(p=>`<tr><td style="text-align:left">${esc(p.name)}</td><td>${p.n[1]||0}</td><td>${p.n[2]||0}</td><td>${p.n[3]||0}</td><td>${p.n[4]||0}</td><td>${dFR(p.first)}</td><td>${dFR(p.last)}</td></tr>`).join('')}</table>`:'<div class="hint" style="margin-top:6px">Aucune étape enregistrée pour l\'instant : le carnet sera vide.</div>'}
   <div class="hint" style="margin-top:8px">À venir avec le dossier chantier (comptes et accès) : habilitations de l'entreprise et du personnel, fiches techniques, accueils — tout ce qui sera déposé au dossier partira dans le DOE au même endroit.</div></div>`;
  el.querySelectorAll('[data-part]').forEach(cb=>cb.onchange=()=>{o.parts[cb.dataset.part]=cb.checked;});
  el.querySelectorAll('[data-opt]').forEach(x=>x.onchange=()=>{const k=x.dataset.opt;if(x.type==='checkbox')o[k]=x.checked;else if(k==='all')o.all=x.value==='1';else if(k==='scale')o.scale=+x.value;else o[k]=x.value;renderExport();});
  const fresh=()=>doeData();
  el.querySelector('#doeCarnet').onclick=()=>{const d=fresh();const pr=o.parts.plan?planPrintHTML(d,o):null;openHTML(carnetHTML(d,{all:o.all,photos:o.photos,planches:pr?pr.planches:{}}));};
  el.querySelector('#doePlan').onclick=()=>{const d=fresh();const r=planPrintHTML(d,o);if(!r.html){A.toast('Rien à dessiner');return;}openHTML(r.html);if(r.note)A.toast(r.note);};
  el.querySelector('#doeViewer').onclick=()=>{const d=fresh();download(`Plan_interactif_${slug(d.site.name)}.html`,new Blob([viewerHTML(d,{fond:o.fond})],{type:'text/html;charset=utf-8'}));A.toast('Plan interactif téléchargé (fichier .html)');};
  el.querySelector('#doeTs').onclick=()=>A.ts.export();
  el.querySelector('#doeCsv').onclick=()=>{const d=fresh();download(`soudures_${slug(d.site.name)}.csv`,new Blob([weldsCSV(d,o)],{type:'text/csv;charset=utf-8'}));};
  el.querySelector('#doeZip').onclick=async()=>{const b=el.querySelector('#doeZip');const pg=el.querySelector('#doeProg');if(b.disabled)return;b.disabled=true;b.textContent='⏳ Fabrication…';const d=fresh();const reset=()=>{b.disabled=false;b.textContent='📁 Fabriquer le dossier DOE';};
    // gros dossier (> 300 Mo estimés) : écriture directe sur le disque au fil de l'eau (Chrome / Edge), sinon tout en mémoire puis téléchargement
    let ws=null;const estMB=weldsOf(d,o).reduce((t,w)=>t+w.photos.length,0)*0.3;
    if(o.parts.photos&&o.photos!=='none'&&estMB>300&&window.showSaveFilePicker){try{const h=await window.showSaveFilePicker({suggestedName:`DOE_${slug(d.site.name)}_${d.at.slice(0,10)}.zip`,types:[{description:'Dossier DOE (zip)',accept:{'application/zip':['.zip']}}]});ws=await h.createWritable();}catch(e){if(e&&e.name==='AbortError'){pg.textContent='Export annulé.';reset();return;}ws=null;}}
    let q=Promise.resolve();const sink=ws?(chunk,final)=>{q=q.then(()=>ws.write(chunk)).then(()=>final?ws.close():null).catch(e=>console.warn(e));}:null;
    try{const t0=Date.now();const r=await zipDOE(d,{...o,sink,onProgress:p=>{pg.textContent=`${p.label} : ${p.done} / ${p.total}`;}});await q;pg.innerHTML=`✓ ${esc(r.name)} — ${sizeTxt(r.size)} en ${Math.round((Date.now()-t0)/1000)} s · ${r.report.photosOk} photo${r.report.photosOk>1?'s':''}${r.report.photosKo?` <span style="color:#d03b3b">· ${r.report.photosKo} non récupérée${r.report.photosKo>1?'s':''}</span>`:''}${ws?' · écrit sur le disque':''}`;if(!ws)download(r.name,r.blob);A.toast('Dossier DOE prêt : '+r.name);}
    catch(e){console.warn(e);pg.textContent='Échec : '+(e&&e.message||e);A.toast('Échec de la fabrication du dossier');}
    reset();};}
