// flotte.js — PARC VÉHICULES (nuit du 09 au 10/10/2026, Ethan : « tout un gros volet flotte, je te mets un Excel de notre suivi de parc véhicules »).
// Source : « Suivi entretien parc de véhicules SCR » (146 véhicules : agence, n°, immatriculation, marque, type, modèle, conducteur, énergie, CO2, 1re immat,
// contrat d'entretien, acquisition / location, restitution, contrôle technique (dernier / prochain), kilométrages, vidange, courroie, pneus, interventions, loyers)
// + « Fiche contrôle véhicule » (propreté, essuie-glaces, plaquettes, pneus, feux, autres, accrocs, remarques, signature du responsable).
// Données : registre kind « vehicule », id = immatriculation. Droit flotte.manage (gérer) ; chacun voit « mon véhicule » (conducteur = lui).
import {regAll,regGet,regSet,regLoad,regLoaded} from './reg.js';
let A=null;
export function initFlotte(api){A=api;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dFR=x=>x?new Date(x).toLocaleDateString('fr-FR'):'';
const nb=x=>(+x||0).toLocaleString('fr-FR');
const days=x=>{if(!x)return null;const t=Date.parse(x);if(!isFinite(t))return null;return Math.round((t-Date.now())/864e5);};
export const TYPES_V=['Soudeur','Manchon','tuyauteur/Pelleur','Benne','CDC','Fonction','Polyvalent','Aménagement','Essais','Autre'];
export const AGENCES=['OUEST','IDF','SUD','SUD OUEST','SCR','RCTP'];
export const CTRL_ITEMS=[['proprete','Propreté'],['essuie','Essuie-glaces'],['plaquettes','Plaquettes de frein'],['pneus','Pneus'],['feux','Feux'],['trousse','Trousse de secours BTP'],['extincteur','Extincteur'],['kit','Kit anti-pollution'],['docs','Documents de bord (carte grise, assurance, CT)'],['autres','Autres']];
export const flotteLoad=()=>regLoad(['vehicule']);
export const vehAll=()=>regAll('vehicule').filter(v=>v&&v.immat).sort((a,b)=>String(a.agence||'').localeCompare(String(b.agence||''))||String(a.immat).localeCompare(String(b.immat)));
export const vehGet=id=>regGet('vehicule',id);
export const vehSet=(id,patch)=>regSet('vehicule',id,patch);
// alertes d'un véhicule : CT (dépassé / ≤ 30 j / ≤ 60 j), vidange (km), contrat d'entretien, restitution de location
export function vehAlertes(v){const L=[];const ct=days(v.ctProchain);if(v.ctProchain!==undefined&&v.ctProchain!==null&&v.ctProchain!==''){if(ct!==null&&ct<0)L.push({k:'ct',sev:'bad',t:'Contrôle technique dépassé depuis '+(-ct)+' j'});else if(ct!==null&&ct<=30)L.push({k:'ct',sev:'bad',t:'Contrôle technique dans '+ct+' j'});else if(ct!==null&&ct<=60)L.push({k:'ct',sev:'warn',t:'Contrôle technique dans '+ct+' j'});}
  else if(!v.ctProchain&&v.immat1&&days(v.immat1)<-4*365)L.push({k:'ct',sev:'warn',t:'Date du prochain contrôle technique inconnue'});
  if(v.cadenceVidange&&v.km!==undefined&&v.km!==null&&v.kmVidange!==undefined&&v.kmVidange!==null&&v.kmVidange!==''){const d=(+v.km)-(+v.kmVidange);if(d>=+v.cadenceVidange)L.push({k:'vid',sev:'warn',t:'Vidange à faire ('+nb(d)+' km depuis la dernière, cadence '+nb(v.cadenceVidange)+')'});}
  if(v.cadenceCourroie&&v.km&&v.kmCourroie!==undefined&&v.kmCourroie!==null&&v.kmCourroie!==''){if((+v.km)-(+v.kmCourroie)>=+v.cadenceCourroie)L.push({k:'cour',sev:'warn',t:'Courroie à remplacer'});}
  const cf=days(v.contratFin);if(cf!==null&&cf<=60)L.push({k:'contrat',sev:cf<0?'bad':'warn',t:cf<0?'Contrat d\'entretien échu':'Contrat d\'entretien dans '+cf+' j'});
  const rs=days(v.restitution);if(rs!==null&&rs<=60&&rs>-3650&&v.dureeLoc)L.push({k:'loc',sev:cf<0?'bad':'warn',t:rs<0?'Restitution de location dépassée':'Restitution de location dans '+rs+' j'});
  (v.signalements||[]).filter(s=>!s.done).forEach(s=>L.push({k:'sig',sev:'warn',t:'Signalement : '+String(s.text||'').slice(0,60)+(s.by?' ('+s.by+')':'')}));
  return L;}
export const vehDe=(acc)=>{if(!acc)return [];const name=String(acc.name||'').trim().toLowerCase();const key=(acc.email||'').toLowerCase();return vehAll().filter(v=>(v.conducteurKey&&key&&v.conducteurKey===key)||(name&&String(v.conducteur||'').trim().toLowerCase()===name)||(name&&String(v.conducteur||'').trim().toLowerCase().split(/\s+/).sort().join(' ')===name.split(/\s+/).sort().join(' ')));};
/* ── vues ── */
const FS={view:'list',cur:null,agence:'',type:'',q:'',alert:false};
export const flotteState=()=>FS;
function filtered(){let L=vehAll();if(FS.agence)L=L.filter(v=>String(v.agence||'').toUpperCase()===FS.agence);if(FS.type)L=L.filter(v=>String(v.type||'').toLowerCase()===FS.type.toLowerCase());if(FS.alert)L=L.filter(v=>vehAlertes(v).length);const q=FS.q.trim().toLowerCase();if(q)L=L.filter(v=>[v.immat,v.marque,v.modele,v.conducteur,v.agence,v.type,v.n].some(x=>String(x||'').toLowerCase().includes(q)));return L;}
export function flotteListHTML(canEdit){const all=vehAll();const L=filtered();const al=all.map(v=>({v,a:vehAlertes(v)}));const bad=al.filter(x=>x.a.some(y=>y.sev==='bad')).length,warn=al.filter(x=>x.a.length&&!x.a.some(y=>y.sev==='bad')).length;const ctSoon=al.filter(x=>x.a.some(y=>y.k==='ct')).length;const vid=al.filter(x=>x.a.some(y=>y.k==='vid')).length;
  const row=({v,a})=>`<button class="ac-row fl-row" data-act="fl" data-v="open|${esc(v.immat)}"><span class="ic" style="background:${a.some(x=>x.sev==='bad')?'#fdeae7':a.length?'#fff4d6':'#e6f5ec'};font-size:17px">${/benne/i.test(v.type)?'🚛':/fonction|cdc/i.test(v.type)?'🚗':'🚐'}</span><span class="tx"><b>${esc(v.immat)} · ${esc(v.marque||'')} ${esc(v.modele||'')}</b><small>${esc(v.agence||'')} · ${esc(v.type||'')}${v.conducteur?' · '+esc(v.conducteur):' · <span style="color:#7a5200">sans conducteur</span>'}${v.km?' · '+nb(v.km)+' km':''}</small><small>${a.length?a.map(x=>`<span class="eq-tag" style="color:${x.sev==='bad'?'#9b2c22':'#7a5200'}">${esc(x.t)}</span>`).join(' '):'<span class="eq-tag" style="color:#15673a">✓ rien à signaler</span>'}${v.ctProchain?' · CT '+dFR(v.ctProchain):''}</small></span><span class="chev">›</span></button>`;
  return `<div class="ac-stats" style="margin-bottom:8px"><div class="ac-stat"><b>${all.length}</b><small>véhicules</small></div><div class="ac-stat ${bad?'bad':''}"><b>${bad}</b><small>alertes bloquantes</small></div><div class="ac-stat ${warn?'warn':''}"><b>${warn}</b><small>à surveiller</small></div><div class="ac-stat ${ctSoon?'warn':''}"><b>${ctSoon}</b><small>CT à passer</small></div><div class="ac-stat ${vid?'warn':''}"><b>${vid}</b><small>vidanges</small></div></div>
    <div class="eq-filtres"><button class="chip${FS.agence?'':' active'}" data-act="fl" data-v="ag|">Toutes agences</button>${AGENCES.filter(a=>all.some(v=>String(v.agence||'').toUpperCase()===a)).map(a=>`<button class="chip${FS.agence===a?' active':''}" data-act="fl" data-v="ag|${a}">${a} <span class="eq-badge">${all.filter(v=>String(v.agence||'').toUpperCase()===a).length}</span></button>`).join('')}<button class="chip${FS.alert?' active':''}" data-act="fl" data-v="alert|">⚠ alertes</button></div>
    <div class="eq-filtres"><button class="chip${FS.type?'':' active'}" data-act="fl" data-v="type|">Tous types</button>${TYPES_V.filter(t=>all.some(v=>String(v.type||'').toLowerCase()===t.toLowerCase())).map(t=>`<button class="chip${FS.type===t?' active':''}" data-act="fl" data-v="type|${t}">${t}</button>`).join('')}</div>
    <div class="row" style="display:flex;gap:6px;margin:6px 0"><input class="f" data-flin="q" value="${esc(FS.q)}" placeholder="🔍 immatriculation, marque, conducteur…" style="flex:1">${canEdit?`<button class="btn primary" data-act="fl" data-v="new|">➕ Véhicule</button>`:''}</div>
    ${L.length?L.map(v=>row(al.find(x=>x.v.immat===v.immat)||{v,a:vehAlertes(v)})).join(''):'<div class="ac-empty">Aucun véhicule'+(all.length?' pour ce filtre':' — passe le SQL d\'import du parc (sql/flotte_import_2026.sql) ou ajoute un véhicule')+'.</div>'}
    <div class="hint" style="margin-top:8px">Alertes calculées : contrôle technique (≤ 60 j, ≤ 30 j, dépassé), vidange (km depuis la dernière ≥ cadence), courroie, contrat d'entretien et restitution de location (≤ 60 j), signalements des conducteurs.</div>`;}
export function flotteFicheHTML(canEdit,people){const v=vehGet(FS.cur);if(!v)return '<div class="card"><div class="eq-s">Véhicule introuvable.</div></div>';const al=vehAlertes(v);const ro=!canEdit;
  const F=(k,l,type,extra)=>`<div><label class="f">${l}</label>${type==='select'?`<select class="f" data-flf="${k}" ${ro?'disabled':''}>${extra}</select>`:type==='textarea'?`<textarea class="f" data-flf="${k}" ${ro?'disabled':''} style="min-height:48px">${esc(v[k]||'')}</textarea>`:`<input class="f" data-flf="${k}" type="${type||'text'}" value="${esc(v[k]===undefined||v[k]===null?'':v[k])}" ${ro?'disabled':''}>`}</div>`;
  const ctrls=(v.controles||[]).slice().reverse();
  return `<div class="card af-head"><div class="af-num">${esc(v.agence||'')} · n° ${esc(v.n||'—')} · ${esc(v.type||'')}</div><h2 class="vt" style="margin:2px 0 4px">${esc(v.immat)} <span class="hint">· ${esc(v.marque||'')} ${esc(v.modele||'')}</span></h2>
      <div class="kv" style="font-size:12.5px"><span>${v.conducteur?'🧑 '+esc(v.conducteur):'sans conducteur'}</span><span>${v.km?nb(v.km)+' km':''}</span><span>${v.energie?esc(v.energie):''}</span><span>${v.immat1?'1re immat. '+dFR(v.immat1):''}</span></div>
      ${al.length?`<div style="margin-top:8px">${al.map(x=>`<div class="${x.sev==='bad'?'warnbox':'warnbox'}" style="margin-top:4px;${x.sev==='bad'?'background:#fdeae7;color:#9b2c22;border-color:#f0b6ad':''}">${esc(x.t)}</div>`).join('')}</div>`:'<div class="okbox" style="margin-top:8px">✓ Rien à signaler sur ce véhicule.</div>'}</div>
    <div class="card eq-form"><h3>Fiche</h3><div class="row af-grid">${F('agence','Agence','select',['','OUEST','IDF','SUD','SUD OUEST','SCR','RCTP'].map(a=>`<option value="${a}"${String(v.agence||'')===a?' selected':''}>${a||'—'}</option>`).join(''))}${F('n','N°')}${F('type','Type','select',[''].concat(TYPES_V).map(t=>`<option value="${t}"${String(v.type||'').toLowerCase()===t.toLowerCase()?' selected':''}>${t||'—'}</option>`).join(''))}${F('marque','Marque')}${F('modele','Modèle')}${F('energie','Énergie')}${F('cv','CV','number')}${F('co2','Rejet CO2','number')}${F('immat1','1re immatriculation','date')}${F('acquisition','Acquisition / location','date')}${F('dureeLoc','Durée location (mois)','number')}${F('restitution','Date de restitution','date')}${F('entretien','Contrat d\'entretien (prestataire)')}${F('contratMois','Contrat (mois)','number')}${F('contratFin','Échéance contrat','date')}${F('ctDernier','Dernier contrôle technique','date')}${F('ctProchain','Prochain contrôle technique','date')}${F('km','Kilométrage actuel','number')}${F('kmFinAnnee','Km fin d\'année précédente','number')}${F('contratKm','Contrat location (km)','number')}${F('cadenceVidange','Cadence vidange (km)','number')}${F('kmVidange','Km dernière vidange','number')}${F('cadenceCourroie','Cadence courroie (km)','number')}${F('kmCourroie','Km dernière courroie','number')}${F('pneus','État des pneus')}${F('taillePneu','Taille pneu')}${F('loyerHT','Loyer HT €/mois','number')}</div>
      <label class="f" style="margin-top:6px">Conducteur <span class="dim">(nom libre ou personne de l'annuaire)</span></label><div class="row" style="display:flex;gap:6px"><input class="f" data-flf="conducteur" value="${esc(v.conducteur||'')}" ${ro?'disabled':''} style="flex:1"><select class="f" data-flf="conducteurKey" ${ro?'disabled':''} style="flex:1"><option value="">— annuaire —</option>${(people||[]).map(p=>`<option value="${esc((p.email||'').toLowerCase()||p.id)}"${v.conducteurKey===((p.email||'').toLowerCase()||p.id)?' selected':''}>${esc(p.name||p.email)}</option>`).join('')}</select></div>
      <label class="f" style="margin-top:6px">Remarques sur l'état général</label><textarea class="f" data-flf="remarques" ${ro?'disabled':''} style="min-height:48px">${esc(v.remarques||'')}</textarea>
      <label class="f" style="margin-top:6px">Commentaires</label><input class="f" data-flf="commentaires" value="${esc(v.commentaires||'')}" ${ro?'disabled':''}>
      ${canEdit?`<div class="eq-acts" style="margin-top:8px"><button class="btn" data-act="fl" data-v="del|" style="color:#9b2c22">Sortir du parc</button></div>`:''}</div>
    <div class="card"><h3>Contrôles visuels <span class="hint">· fiche de contrôle véhicule</span></h3>${ctrls.length?ctrls.map(c=>`<div class="eq-vrow"><div class="eq-row"><span class="eq-grow"><span class="eq-t">${dFR(c.at)} · ${esc(c.by||'')}${c.km?' · '+nb(c.km)+' km':''}</span><span class="eq-s">${CTRL_ITEMS.map(([k,l])=>c.items&&c.items[k]?`${l} : <b>${esc(c.items[k])}</b>`:'').filter(Boolean).join(' · ')}${c.accrocs?' · accrocs : '+esc(c.accrocs):''}${c.remarques?' · '+esc(c.remarques):''}</span></span></div></div>`).join(''):'<div class="eq-s">Aucun contrôle enregistré.</div>'}
      ${canEdit?`<div class="eq-acts" style="margin-top:6px"><button class="btn primary" data-act="fl" data-v="ctrl|">➕ Contrôle visuel</button></div>`:''}</div>
    <div class="card"><h3>Interventions</h3>${(v.interventions||[]).length?`<ul style="font-size:12.5px;padding-left:18px;margin:4px 0">${(v.interventions||[]).map(i=>`<li>${esc(typeof i==='string'?i:(i.text||''))}</li>`).join('')}</ul>`:'<div class="eq-s">Aucune intervention notée.</div>'}${canEdit?`<div class="row" style="display:flex;gap:6px;margin-top:6px"><input class="f" id="fl-interv" placeholder="description, date, km et coût" style="flex:1"><button class="btn" data-act="fl" data-v="intadd|">Ajouter</button></div>`:''}</div>
    <div class="card"><h3>Signalements des conducteurs</h3>${(v.signalements||[]).length?(v.signalements||[]).slice().reverse().map(s=>`<div class="eq-row"><span class="eq-grow"><span class="eq-t">${esc(s.text||'')}${s.done?' <span class="eq-tag" style="color:#15673a">✓ traité</span>':''}</span><span class="eq-s">${esc(s.by||'')} · ${dFR(s.at)}</span></span>${canEdit&&!s.done?`<button class="btn sm" data-act="fl" data-v="sigok|${esc(s.id)}">✓ traité</button>`:''}</div>`).join(''):'<div class="eq-s">Aucun signalement.</div>'}</div>`;}
export function controleForm(immat){const v=vehGet(immat);if(!v)return;
  A.openModal(`<h3 style="margin-top:0">Contrôle visuel — ${esc(v.immat)} <span class="hint">· ${esc(v.marque||'')} ${esc(v.modele||'')}</span></h3>
    <label class="f">Kilométrage relevé</label><input class="f" id="flc-km" type="number" value="${esc(v.km||'')}">
    ${CTRL_ITEMS.map(([k,l])=>`<div class="ct-item"><div class="ct-lab">${l}</div><div class="ct-seg">${['OK','À revoir','HS','NV'].map(e=>`<button type="button" data-flc="${k}" data-e="${e}" class="${e==='OK'?'c':e==='HS'?'nc':''}">${e}</button>`).join('')}</div></div>`).join('')}
    <label class="f" style="margin-top:6px">Accrocs</label><input class="f" id="flc-accrocs" placeholder="rayures, bosses…"><label class="f" style="margin-top:6px">Remarques</label><textarea class="f" id="flc-rem" style="min-height:48px"></textarea>
    <div class="actions" style="margin-top:8px"><button class="btn primary block" id="flc-ok">Enregistrer le contrôle</button><button class="btn block" data-close>Annuler</button></div>`);
  const ST={};document.querySelectorAll('#modal [data-flc]').forEach(b=>b.onclick=()=>{ST[b.dataset.flc]=b.dataset.e;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x.dataset.e===b.dataset.e));});
  document.getElementById('flc-ok').onclick=()=>{if(!Object.keys(ST).length){A.toast('Coche au moins un point');return;}const km=+document.getElementById('flc-km').value||null;const c={id:'C'+Date.now().toString(36),at:new Date().toISOString(),by:A.userName(),km,items:ST,accrocs:document.getElementById('flc-accrocs').value.trim(),remarques:document.getElementById('flc-rem').value.trim()};
    const patch={controles:(v.controles||[]).concat([c])};if(km)patch.km=km;vehSet(v.immat,patch);A.closeModal();A.toast('Contrôle enregistré');if(A.rerender)A.rerender();};}
export function flotteAct(v,el,ctx){const [k,arg]=String(v).split('|');const cur=FS.cur?vehGet(FS.cur):null;const canEdit=ctx.canEdit;
  switch(k){case 'ag':FS.agence=arg;break;case 'type':FS.type=arg;break;case 'alert':FS.alert=!FS.alert;break;case 'open':FS.cur=arg;FS.view='fiche';break;case 'back':FS.view='list';FS.cur=null;break;
    case 'new':{if(!canEdit)return;const im=prompt('Immatriculation (ex. GT-648-SE)');if(!im)return;const immat=im.trim().toUpperCase();if(vehGet(immat)){A.toast('Ce véhicule existe déjà');FS.cur=immat;FS.view='fiche';break;}vehSet(immat,{immat,agence:'OUEST',at:new Date().toISOString(),by:A.userName()});FS.cur=immat;FS.view='fiche';break;}
    case 'del':{if(!canEdit||!cur)return;if(!confirm('Sortir '+cur.immat+' du parc ?'))return;regSet('vehicule',cur.immat,{deleted:true,deletedAt:new Date().toISOString()});FS.view='list';FS.cur=null;break;}
    case 'ctrl':{if(!canEdit||!cur)return;controleForm(cur.immat);return;}
    case 'intadd':{if(!canEdit||!cur)return;const t=(document.getElementById('fl-interv')||{}).value||'';if(!t.trim())return;vehSet(cur.immat,{interventions:(cur.interventions||[]).concat([{text:t.trim(),at:new Date().toISOString(),by:A.userName()}])});break;}
    case 'sigok':{if(!canEdit||!cur)return;vehSet(cur.immat,{signalements:(cur.signalements||[]).map(s=>s.id===arg?Object.assign({},s,{done:true,doneAt:new Date().toISOString()}):s)});break;}
    case 'signal':{const immat=arg;const vv=vehGet(immat);if(!vv)return;const t=prompt('Signaler un problème sur '+immat+' (panne, voyant, pneu, accroc…)');if(!t)return;vehSet(immat,{signalements:(vv.signalements||[]).concat([{id:'S'+Date.now().toString(36),text:t.trim(),at:new Date().toISOString(),by:A.userName()}])},{});A.toast('Signalement envoyé au responsable flotte');break;}
    default:return;}
  if(ctx.render)ctx.render();}
export function flotteInput(el,ctx){const d=el.dataset;if(d.flin==='q'){FS.q=el.value;if(ctx.render)ctx.render();return true;}if(!d.flf)return false;if(!ctx.canEdit){A.toast('Lecture seule : droit « Flotte » nécessaire');return true;}const v=FS.cur?vehGet(FS.cur):null;if(!v)return false;
  const num=['cv','co2','dureeLoc','contratMois','km','kmFinAnnee','contratKm','cadenceVidange','kmVidange','cadenceCourroie','kmCourroie','loyerHT'].includes(d.flf);vehSet(v.immat,{[d.flf]:el.value===''?null:(num?+el.value:el.value)});if(d.flf==='conducteurKey'&&el.value){const p=(ctx.people||[]).find(x=>((x.email||'').toLowerCase()||x.id)===el.value);if(p)vehSet(v.immat,{conducteur:p.name||p.email});}if(ctx.render)ctx.render();return true;}
export function flotteView(ctx){return FS.view==='fiche'&&FS.cur?`<button class="ac-back" data-act="fl" data-v="back|">‹ Parc véhicules</button>`+flotteFicheHTML(ctx.canEdit,ctx.people):`<h2 class="vt">Parc véhicules <span class="hint">· flotte</span></h2>`+flotteListHTML(ctx.canEdit);}
// carte « mon véhicule » (Mon espace) : CT, vidange, signaler un problème
export function monVehiculeHTML(acc){const L=vehDe(acc);if(!L.length)return '';return L.map(v=>{const al=vehAlertes(v);return `<div class="card"><h3>🚐 Mon véhicule <span class="hint">· ${esc(v.immat)} · ${esc(v.marque||'')} ${esc(v.modele||'')}</span></h3><div class="eq-s">${v.ctProchain?'Contrôle technique : <b>'+dFR(v.ctProchain)+'</b>':'Contrôle technique : date inconnue'}${v.km?' · '+nb(v.km)+' km':''}${v.cadenceVidange?' · vidange tous les '+nb(v.cadenceVidange)+' km':''}</div>${al.length?al.map(x=>`<div class="warnbox" style="margin-top:4px">${esc(x.t)}</div>`).join(''):'<div class="okbox" style="margin-top:6px">✓ Rien à signaler.</div>'}<div class="eq-acts" style="margin-top:8px"><button class="btn" data-act="fl" data-v="signal|${esc(v.immat)}">⚠ Signaler un problème</button></div><div class="hint" style="margin-top:4px">Trousse de secours, extincteur et kit anti-pollution doivent être à bord ; carnet d'entretien chez le responsable flotte.</div></div>`;}).join('');}
export const flotteReady=()=>regLoaded('vehicule');
