// prevention.js — CONTENUS QSE de l'accueil (nuit du 09 au 10/10/2026, demande d'Ethan : « vas-y à fond pour rajouter des petites parties prévention »).
// · ACCUEIL_CHANTIER_Q : les 10 points de l'accueil chantier, mot pour mot (Ethan, 09/10 soir).
// · PREVENTION : petits modules de prévention cohérents pour un chantier de réseau de chaleur (RCU, tubes acier pré-isolés) — chaque module se DÉROULE
//   en entier avant de pouvoir cliquer « Lu », puis la personne valide le point correspondant. Textes écrits pour SCR : à relire / amender par le QHSE.
// · ACCUEIL_ENTREPRISE_Q : questionnaire d'accueil « nouvel arrivant » (embauché / intérimaire) — PROVISOIRE, Ethan cherche encore son formulaire.
// · CONTROLE_DEF : la trame « Contrôle chantier SCR » (fichier Contrôle chantier SCR – Angers 07/07/2026) dématérialisée.
export const ACCUEIL_CHANTIER_Q=[
 'J’ai pris connaissance du PPSPS, je l’ai compris et j’ai signé la fiche d’émargement',
 'J’ai présenté mes Pass prévention (aptitudes, attestations de formation, carte BTP, QR code)',
 'Mes équipements et EPI ont été contrôlés et sont conformes',
 'On m’a présenté les plans, la DICT et les points d’attention réseaux',
 'Je connais les horaires de travail, les référents du chantier et les contacts secours',
 'Je sais comment réagir en cas d’accident et j’ai compris mon droit de retrait',
 'J’ai compris les consignes incendie (risques hors emprise, protection des réseaux). Je sais où sont les extincteurs et couvertures antifeu',
 'Je connais les règles d’hygiène : sanitaires, eau, savon, essuie-mains, pauses repas',
 'J’ai compris les consignes de stationnement, de barriérage, de clôture et de zone d’emprise',
 'J’ai compris le fonctionnement de la base vie et du stockage (tubes, consommables, produits chimiques), la gestion des déchets, l’organisation des engins et du carburant'];
// modules de prévention rattachés aux points (1 = PPSPS lui-même, 2 = pièces de la personne : pas de module)
export const ACCUEIL_MODULES={3:['epi'],4:['reseaux','tranchee'],5:['referents'],6:['accident'],7:['incendie'],8:['hygiene'],9:['circulation','levage'],10:['basevie','chimie']};
// 10/10 (retour Ethan) : au point 4 « juste le lien vers la DICT » — les modules réseaux / tranchées restent proposés mais ne bloquent pas le point
export const ACCUEIL_MODULES_OPT={4:true};
const L=(...items)=>'<ul>'+items.map(x=>'<li>'+x+'</li>').join('')+'</ul>';
const P=t=>'<p>'+t+'</p>';
const H=t=>'<h3>'+t+'</h3>';
const OK=t=>'<div class="pv-ok"><b>Ce que tu valides</b>'+t+'</div>';
export const PREVENTION={
 epi:{title:'EPI et tenue de travail sur un chantier RCU',html:
  P('Sur un chantier de réseau de chaleur on soude, on meule, on manutentionne des tubes acier de plusieurs centaines de kilos, on travaille en tranchée et au bord de la circulation. Les EPI ne sont pas une option : ils sont contrôlés à l’accueil et à chaque contrôle chantier.')+
  H('La tenue de base, pour tout le monde, tout le temps')+L('Casque, lunettes de protection, gants adaptés à la tâche, chaussures de sécurité S3 montantes, vêtements haute visibilité classe 2 minimum (classe 3 sur voirie ouverte), tenue de travail complète (manches longues, pas de vêtement flottant).','Protections auditives dès qu’on meule, tronçonne ou qu’un groupe tourne à côté.','Trousse de secours BTP et extincteur dans chaque véhicule — tu vérifies qu’ils sont là.')+
  H('Soudeur')+L('Masque de soudeur avec filtre adapté, casque pare-face pour le meulage, gants de soudeur en cuir, tablier ou veste cuir, guêtres si besoin.','Jamais de meulage sans pare-face : les éclats et les étincelles partent dans les yeux ET hors emprise.')+
  H('Manchonneur')+L('Lunettes et gants pour la mousse polyuréthane et les résines (voir le module produits chimiques), gants anti-chaleur pour le rétreint, protection respiratoire si l’espace est confiné ou peu ventilé.')+
  H('Chauffeur d’engin / pelleur')+L('Gilet HV, casque hors cabine, chaussures S3 ; talkie-walkie pour la communication avec le tuyauteur en fouille.')+
  H('État des EPI')+L('Un EPI abîmé se remplace : tu le signales à ton chef de chantier, il n’y a pas de débat.','Casque : pas plus de 5 ans ni après un choc. Harnais : vérification avant chaque usage et par une personne compétente une fois par an.')+
  OK(P('Mes EPI sont complets, en bon état, contrôlés avec mon chef de chantier, et je les porte en permanence dans l’emprise.'))},
 reseaux:{title:'Réseaux enterrés, DICT et marquage-piquetage',html:
  P('Nos tranchées croisent du gaz, de l’électricité, des télécoms, de l’eau et parfois d’autres réseaux de chaleur. Toucher un réseau, c’est un accident grave possible (explosion, électrisation, ébouillantage) et un arrêt de chantier.')+
  H('Avant de creuser')+L('La DICT (déclaration d’intention de commencement de travaux) et les réponses des exploitants sont au dossier administratif du chantier (catégorie DT / DICT) : tu dois y avoir accès et savoir où elles sont.','Le marquage-piquetage au sol (code couleur : jaune gaz, rouge électricité, vert télécom, bleu eau, violet chauffage) doit être présent et lisible avant toute fouille.','Toute personne qui intervient à proximité des réseaux a son AIPR (opérateur, encadrant ou concepteur).')+
  H('Pendant la fouille')+L('Zone d’incertitude des plans (classe A 40 cm, B 1,5 m, C au-delà) : à l’approche d’un réseau on passe aux techniques douces (pelle à main, aspiratrice) et on dégage le réseau à la main.','Jamais d’engin à moins de 50 cm d’un réseau sensible sans l’avoir dégagé.','Le pelleur travaille avec un tuyauteur au sol qui guide : communication talkie-walkie, gestes convenus.')+
  H('Si un réseau est touché ou endommagé')+L('STOP : on arrête tout, on éloigne tout le monde, on ne touche à rien, on n’essaie pas de réparer.','Gaz : pas de flamme, pas d’étincelle, pas de téléphone dans la zone, on coupe les moteurs, on appelle le 18/112 puis l’exploitant (n° d’urgence sur la DICT) et le conducteur de travaux.','Électricité : on ne s’approche pas du câble, on ne touche pas l’engin s’il est en contact (le conducteur saute pieds joints hors de la cabine sans toucher le sol et l’engin en même temps).','Même un simple frottement de gaine se déclare : c’est le constat contradictoire avec l’exploitant qui protège l’entreprise et toi.')+
  OK(P('J’ai vu les plans et la DICT du chantier, je connais le code couleur et les points d’attention réseaux, et je sais que l’on s’arrête au moindre doute.'))},
 tranchee:{title:'Tranchées et travaux en fouille',html:
  P('Un éboulement, c’est quelques secondes et plusieurs centaines de kilos de terre : la plupart des accidents mortels en tranchée arrivent dans des fouilles de moins de 2 m que l’on croyait stables.')+
  H('Règles de la fouille')+L('Au-delà de 1,30 m de profondeur (ou dès que le terrain est douteux, humide, remanié, en bord de voirie) : blindage ou talutage, pas de discussion.','Les déblais et les tubes sont stockés à au moins 1 m du bord ; pas de charge en bord de fouille, pas d’engin qui circule le long de la lèvre.','Accès et sortie par échelle fixée, dépassant d’1 m, une tous les 20 m : on ne saute pas dans la fouille, on ne grimpe pas sur le blindage.','Passerelles pour franchir la tranchée, garde-corps ou barriérage continu côté public.')+
  H('Travailler dans la fouille')+L('Jamais seul : quelqu’un voit toujours la personne en fouille.','On vérifie le blindage et les parois après la pluie, après un passage d’engin, à chaque reprise.','On ne reste pas dans la fouille pendant les mouvements de l’engin ou la descente d’un tube.','Eau dans la fouille : pompage et vérification des parois avant de redescendre.')+
  H('Spécifique RCU')+L('Les tubes sont posés sur lit de sable, les manchons se font dans des niches : la niche élargit la fouille et affaiblit les parois — elle se blinde aussi.','Le poste de soudure en fouille : ventilation (fumées), câbles et flexibles sortis de la zone de passage, retour de masse au plus près de la soudure.')+
  OK(P('Je ne descends dans une tranchée que si elle est blindée ou talutée, accessible par échelle, sans charge en bord de fouille, et jamais pendant les mouvements d’engin.'))},
 referents:{title:'Horaires, référents du chantier et contacts secours',html:
  P('Les horaires de chantier sont transmis par le responsable d’exploitation et peuvent changer selon la saison. Sur ce chantier, tes référents sont indiqués ci-dessous (fiche chantier de l’appli) ; en cas de doute, c’est le chef de chantier qui tranche.')+
  '<div class="pv-ref">{{REFERENTS}}</div>'+
  H('Contacts secours')+L('<b>18</b> pompiers · <b>15</b> SAMU · <b>112</b> numéro d’urgence européen · <b>114</b> par SMS (sourds et malentendants).','Le point de rencontre des secours (PR) et le point de rassemblement sont à la base vie, sauf consigne contraire du chef de chantier — demande-les si ce n’est pas clair.','Les SST du chantier sont identifiés par le logo sur le casque ou la tenue.','Les numéros d’urgence des exploitants de réseaux sont sur les réponses de DICT (dossier administratif).')+
  OK(P('Je connais mes horaires, je sais qui sont mon chef de chantier et mon conducteur de travaux, et comment joindre les secours depuis ce chantier.'))},
 accident:{title:'En cas d’accident — et le droit de retrait',html:
  P('La feuille « En cas d’accident » est connue de tous et reste dans le véhicule. Ce qui compte : protéger, alerter, secourir — et prévenir le conducteur de travaux dans les plus brefs délais (annuaire de chantier).')+
  H('Accident bénin')+L('Les gestes de premiers secours sont faits par un SST du chantier avec la trousse de secours.','Le conducteur de travaux est prévenu ; la victime et le secouriste décident de la suite (médecin, retour au poste).','L’accident bénin est inscrit au registre par le responsable QHSE — même une coupure.')+
  H('Accident grave')+L('Protéger la zone, premiers secours par le SST.','Le SST appelle le 18 / 112 et donne le point de rencontre (PR) le plus proche ; une personne est envoyée au PR pour guider les secours.','Prévenir le conducteur de travaux ; la victime est prise en charge par les secours, le SST reste à leur disposition.','Analyse d’accident et rapport par le QHSE ; client, CARSAT, inspection du travail et OPPBTP informés.')+
  H('Ce que tu dois faire dans tous les cas')+L('Signaler tout accident, même bénin, et toute situation dangereuse à ton chef de chantier le jour même (sous 24 h maximum pour la déclaration).','Accident de trajet : même règle.')+
  H('Droit d’alerte et de retrait')+L('Si tu as un motif raisonnable de penser qu’une situation présente un danger grave et imminent pour ta vie ou ta santé, tu te retires de la situation et tu préviens ta hiérarchie immédiatement.','Le retrait ne doit pas créer un nouveau danger pour les autres.','Personne ne peut te sanctionner pour avoir exercé ce droit de bonne foi : c’est écrit dans le règlement intérieur (article 2.1.1).')+
  OK(P('Je sais protéger, alerter (18 / 112, PR) et prévenir le conducteur ; je sais que je peux et je dois me retirer d’une situation de danger grave et imminent.'))},
 incendie:{title:'Prévention incendie sur un chantier RCU',html:
  P('Souder et meuler en tranchée, à côté de gaines en polyéthylène, de mousse polyuréthane, de bouteilles de gaz et parfois d’un réseau gaz voisin : le risque incendie est permanent et il sort facilement de l’emprise (haies, voitures en stationnement, bâtiments, caves).')+
  H('Points chauds')+L('Avant de souder ou meuler : regarder autour — herbes sèches, haie, palissade bois, véhicule, gaine PE, mousse, carburant, bouteilles. On dégage ou on protège.','Écran pare-étincelles ou couverture antifeu entre le point chaud et ce qui peut brûler ; on meule dans le sens qui renvoie les étincelles vers le fond de fouille, jamais vers la rue.','Un extincteur à portée de main (pas dans le camion garé 50 m plus loin) : ABC 6 kg sur le poste, 2 kg dans chaque cabine.','Surveillance 30 minutes après la fin du point chaud (un feu couve dans la mousse ou le paillis).','Permis feu quand le client ou le PPSPS l’impose (bâtiment, chaufferie, site industriel).')+
  H('Gaz et bouteilles')+L('Bouteilles debout, arrimées, à l’ombre, robinets fermés hors utilisation, détendeurs et anti-retours en bon état, flexibles contrôlés.','Pas de stockage de bouteilles dans la fouille ni dans un véhicule fermé au soleil.')+
  H('Mousse PU, résines, gaines PE')+L('La mousse polyuréthane et ses composants sont inflammables : on ne mousse pas à côté d’un point chaud et on ne soude pas sur un manchon fraîchement moussé.','Les chutes de gaine PE et les emballages partent au tri le jour même : moins de combustible dans l’emprise.')+
  H('Réseaux voisins')+L('Un réseau gaz marqué au sol change tout : pas de point chaud sans dégagement du réseau et accord du chef de chantier ; détection en cas de doute.','Fuite de gaz : stop, éloignement, pas de flamme ni d’étincelle, 18 / 112, exploitant.')+
  H('Si ça prend')+L('Donner l’alerte, attaquer le départ de feu avec l’extincteur SI c’est sans risque, sinon évacuer vers le point de rassemblement et appeler le 18.','Ne jamais arroser un feu de métal ou une installation électrique sous tension.')+
  OK(P('Je sais où sont les extincteurs et la couverture antifeu de mon poste, je protège les abords avant chaque point chaud et je surveille après.'))},
 hygiene:{title:'Hygiène, base vie et pauses',html:
  P('Le chantier dispose de sanitaires, d’eau, de savon et d’essuie-mains : c’est une obligation, pas un confort. Les repas se prennent à la base vie (ou dans son véhicule) — jamais ailleurs : ni dans la fouille, ni sur l’emprise, ni dans les locaux du client.')+
  L('Lavage des mains avant de manger, après la mousse, les résines, les graisses et après la fouille.','Eau potable disponible, en quantité, protégée du soleil ; vigilance canicule (pauses à l’ombre, boire régulièrement).','Sanitaires propres : c’est l’affaire de tous ; signale tout manque (eau, savon, papier) au chef de chantier.','Pause repas aux horaires fixés ; pas d’alcool, pas de stupéfiants sur le chantier ni dans les véhicules (règlement intérieur, articles 2.2.2 et 2.2.3).','Interdiction de fumer ou de vapoter près des produits inflammables et pendant les opérations de découpe, soudage, manchonnage et manutention.','En grand déplacement : hébergement en dur obligatoire (jamais la nuit dans le véhicule ou la base vie), à moins de 30 km du chantier.')+
  OK(P('Je sais où sont les sanitaires, l’eau et la base vie, et je respecte les règles d’hygiène et de pause du chantier.'))},
 circulation:{title:'Stationnement, barriérage, clôture et zone d’emprise',html:
  P('Nos chantiers sont en ville, sur ou le long de voies ouvertes : la circulation (voitures, bus, vélos, piétons) est le premier risque exporté. L’emprise est le périmètre dans lequel on a le droit de travailler ; en dehors, on est un piéton comme les autres.')+
  H('Emprise et clôture')+L('Clôture ou barriérage continu, lesté, signalétique à jour (panneaux, feux, déviation piétonne) : on remet en place ce qu’on déplace, tous les soirs on referme.','Les piétons gardent toujours un cheminement protégé ; les vélos aussi (pistes cyclables coupées = itinéraire balisé).','Rien ne dépasse de l’emprise : tubes, déblais, câbles de soudure, flexibles.')+
  H('Stationnement et engins')+L('Véhicules garés dans l’emprise ou à la base vie, en marche arrière, prêts à partir ; jamais sur le cheminement piéton ni devant une sortie de secours.','Positionnement des engins : stabilisateurs sortis, zone de giration dégagée, personne dans le rayon d’action, communication pelleur ↔ sol par talkie-walkie.','Manœuvres de camions et de semi-remorques guidées par une personne au sol en gilet HV, de préférence avec barrières prêtées par le TP pour couper les arrivées.')+
  H('Travail hors emprise = opération à part')+L('Déchargement improvisé sur voie publique, transfert de tubes, intervention sur un autre front : on s’arrête, on prévient le chef de chantier et on balise AVANT.')+
  OK(P('Je travaille dans l’emprise, je referme et je rebalise, je gare mon véhicule au bon endroit et je guide les manœuvres.'))},
 levage:{title:'Levage et manutention des tubes',html:
  P('Un tube DN250 pré-isolé de 12 m pèse plusieurs centaines de kilos ; un coude, une vanne pré-isolée aussi. Le levage (pelle avec crochet, grue auxiliaire, chariot) est l’un des moments les plus dangereux de la journée.')+
  L('Autorisation de conduite et CACES à jour pour qui lève (R482 engins, R489 chariot, R490 grue auxiliaire).','Élingues et sangles contrôlées (étiquette lisible, pas de coupure), adaptées à la charge, points de levage en bon état ; jamais d’élingage sur l’isolation seule.','Zone d’exclusion sous la charge : personne dessous, personne entre la charge et un obstacle fixe.','Guidage à la longe (corde), jamais à la main directement : moins de risque de pincement et de choc.','Déchargement de camion : plan de déchargement, calage des tubes, cales et chandelles, pas de dépose sur un terrain en pente sans butée.','Stockage : tubes calés, hauteur limitée, pas au bord de la fouille, protégés des UV et de l’eau selon les consignes fournisseur.')+
  OK(P('Je ne me tiens jamais sous une charge, je guide à la longe et je ne lève qu’avec du matériel contrôlé et une autorisation de conduite.'))},
 basevie:{title:'Base vie, stockage, déchets, engins et carburant',html:
  P('La base vie et les conteneurs de stockage sont le point de départ et d’arrivée de la journée : rangés, fermés, propres, ils évitent les vols, les chutes et les pollutions.')+
  H('Stockage')+L('Tubes et pièces : calés, repérés par DN, à l’abri des chocs ; les manchons et consommables (fils, kits DH, bouchons) rangés dans le conteneur fermé à clé.','Produits chimiques (mousse PU, résines, nettoyants, carburant) : sur rétention, étiquetés, fiches de données de sécurité disponibles, à l’écart des points chauds.','Accès base vie : clôture fermée, signalétique, verrouillage le soir.')+
  H('Déchets')+L('Tri à la source : métal, gaine PE et mousse, bois, emballages, DIB, déchets dangereux (aérosols, bidons de résine) — chacun dans sa benne ou son sac.','Mise en sac des déchets légers pour éviter les envols hors emprise ; benne couverte ou filet.','Rotation des bennes anticipée avec le chef de chantier.')+
  H('Engins et carburant')+L('Plein des engins au bidon homologué ou à la cuve sur rétention, moteur arrêté, pas de téléphone, kit anti-pollution à portée (absorbant).','Groupe électrogène : mise à la terre, câbles protégés, pas de carburant stocké à côté.','Clés des engins jamais sur le contact ; engins garés dans l’emprise, godet au sol.')+
  OK(P('Je sais où et comment ranger les tubes, les consommables et les produits chimiques, comment trier les déchets et comment faire le plein en sécurité.'))},
 chimie:{title:'Produits chimiques : mousse PU, résines et gaz',html:
  P('Le manchonnage utilise des composants de mousse polyuréthane (polyol + isocyanate), des résines, des nettoyants ; la soudure utilise des gaz. Ces produits brûlent, irritent, sensibilisent — les protections sont simples si on les applique à chaque fois.')+
  L('Lire l’étiquette et la fiche de données de sécurité (FDS) avant la première utilisation : elles sont au dossier du chantier ou dans le conteneur.','Gants nitrile ou néoprène (pas de cuir pour la mousse), lunettes, manches longues ; protection respiratoire si l’air ne circule pas (niche, regard, local).','Ne jamais mousser à côté d’un point chaud ni fumer en manipulant ; refermer les bidons.','Projection dans l’œil : rincer 15 minutes à l’eau claire et consulter ; sur la peau : essuyer sans frotter, laver à l’eau et au savon.','Déversement : absorbant du kit anti-pollution, pas d’eau dans les égouts, bidons souillés en déchet dangereux.','Les composants isocyanates peuvent déclencher asthme et allergies : tout symptôme respiratoire ou cutané se signale au chef et au médecin du travail.')+
  OK(P('Je connais les produits que je manipule, je porte gants et lunettes adaptés, je sais réagir à une projection ou un déversement.'))},
};
// accueil « nouvel arrivant » (entreprise) — PROVISOIRE (Ethan : « il me reste à trouver le formulaire ») : à ajuster dans Exploitation → Documents d'entreprise
export const ACCUEIL_ENTREPRISE_Q=[
 'L’entreprise SCR (réseaux de chaleur en acier pré-isolé), son organisation (direction, exploitation, conducteurs de travaux, chefs de chantier) et mon secteur m’ont été présentés.',
 'J’ai reçu, lu et signé le règlement intérieur ; la politique santé-sécurité de l’entreprise m’a été expliquée.',
 'Mon contrat ou ma mission, mes horaires, le fonctionnement des grands déplacements (4 cas) et de l’hébergement m’ont été expliqués.',
 'Mes EPI m’ont été remis (casque, lunettes, gants, chaussures S3, vêtements haute visibilité, protections auditives, masque et cuir de soudeur si soudeur) et je sais les entretenir et les faire remplacer.',
 'Mon aptitude médicale est à jour et j’ai transmis mes habilitations et formations (AIPR, CACES, qualifications soudeur, SST, habilitation électrique, carte BTP). Intérimaire : mon agence les a transmises à SCR.',
 'Les consignes générales de sécurité m’ont été expliquées : droit d’alerte et de retrait, interdiction alcool / stupéfiants, téléphone au poste, interdiction de fumer près des produits inflammables.',
 'Je sais quoi faire en cas d’accident ou d’incident (SST, 18 / 112, prévenir le conducteur de travaux, déclaration sous 24 h).',
 'Les règles d’utilisation du véhicule de service m’ont été présentées (permis, documents de bord, contrôle visuel, trousse de secours, extincteur, kit anti-pollution, usage strictement professionnel).',
 'L’application TRACÉ m’a été présentée : pointage, fiches de soudure, accueil chantier, documents à signer, mon espace.',
 'Je sais à qui m’adresser : chef de chantier, conducteur de travaux, responsable d’exploitation, service RH.'];
// trame « Contrôle chantier SCR » (enjeux : moyens pour travailler en sécurité, moyens pour l'avancement, respect des consignes et bonnes pratiques)
export const CONTROLE_DEF=[
 ['Base vie / conteneurs de stockage',[['bv_rang','Rangement base vie'],['bv_dech','Tri et conditionnement des déchets'],['bv_chim','Stockage des produits chimiques sur rétention'],['bv_stock','État des stocks'],['bv_acces','Accès base vie, clôture, verrouillage, signalétique']]],
 ['Chantier',[['ch_clot','Clôture du chantier, signalétique'],['ch_emprise','Respect de la zone d’emprise'],['ch_place','Espace de travail (place suffisante)'],['ch_veh','Positionnement des véhicules et engins'],['ch_tranchee','Conformité tranchée (blindage, état de la tranchée, présence de réseau, fond de fouille)'],['ch_carbu','Gestion du carburant (achat, stockage)'],['ch_sanit','Accessibilité sanitaires']]],
 ['Équipe',[['eq_accueil','Accueils chantier, PPSPS'],['eq_plans','Plans à jour'],['eq_trousse','Trousse de secours'],['eq_epi','Port des EPI (complets, portés, état)'],['eq_tenue','Tenue de travail complète, état'],['eq_equip','Équipements de travail (état, conformes, rangés sans risques)'],['eq_echelle','Montée / descente tranchée conforme (échelles conformes, fixées et utilisées)'],['eq_levage','Opérations de levage sécurisées, conformes'],['eq_talkie','Communication pelleur (talkie-walkie)'],['eq_rang','Rangement zone de travail, tri des déchets et mise en sac (risques d’envols)'],['eq_consignes','Respect des consignes'],['eq_zone','Travail dans la zone d’emprise'],['eq_terre','Mise à la terre des groupes électrogènes'],['eq_extinct','Présence extincteur'],['eq_antifeu','Présence / utilisation protection antifeu'],['eq_itopo','Rapports i-topo et / ou perches à jour'],['eq_soud','Contrôle de la dernière soudure (visuel qualité soudure, identification)'],['eq_manchon','Contrôles du dernier manchon (continuité, isolation, étanchéité)'],['eq_export','Absence de risques exportés hors emprise (projections d’étincelles, envols de déchets, déversement…)'],['eq_docveh','Documents véhicules']]]];
export const CONTROLE_ETATS={C:'Conforme',NC:'Non conforme',NA:'Non applicable',NV:'Non vu'};
// ── QUARTS D'HEURE SÉCURITÉ (10/10, retour Ethan : « dématérialiser de la même manière que l'accueil chantier : partie prévention, petit questionnaire, émargement ») ──
// EXEMPLES écrits par moi pour un chantier RCU, en attendant la base SCR (Ethan la remet) : chaque sujet = texte à dérouler en entier + 3 questions à confirmer + signature.
// Un sujet importé dans la base (registre, kind « qhstopic », même forme {id,title,html,qs}) remplace l'exemple de même id.
export const QHS_TOPICS=[
 {id:'qhs_reseaux',title:'Travaux à proximité des réseaux enterrés',exemple:true,html:
  P('Un coup de godet dans une conduite de gaz, un câble HTA ou une fibre : c’est l’accident le plus fréquent et le plus grave de nos chantiers de tranchée. Il se prévient AVANT de creuser, pas pendant.')+
  H('Avant de creuser')+L('DICT à jour pour la zone, réponses des exploitants lues par le chef de chantier, plans sur le chantier et consultés — pas « dans le camion ».','Marquage au sol des réseaux (code couleur : jaune gaz, rouge électricité, bleu eau, vert télécom, orange chauffage urbain) refait s’il a disparu.','Zone d’incertitude : sondage manuel ou aspiratrice, jamais le godet à dents dans les 50 cm autour d’un réseau sensible.')+
  H('Pendant')+L('Le pelleur ne creuse que si quelqu’un regarde la fouille : communication à la voix ou au talkie, arrêt immédiat au moindre doute (grillage avertisseur, sable, fourreau).','Un réseau mis à nu se protège et se signale au chef de chantier, qui prévient l’exploitant si nécessaire.','Réseau touché = chantier à l’arrêt, personne dans la fouille, périmètre, appel du chef puis de l’exploitant (gaz : 112 et évacuation large, pas de flamme ni d’étincelle).')+
  OK(P('Je ne creuse jamais sans DICT ni marquage, je sonde à la main près des réseaux sensibles et j’arrête tout au moindre doute.')),
  qs:['Je sais où sont les plans et le marquage des réseaux sur ce chantier.','Je sais qu’on sonde à la main dans la zone d’incertitude, jamais au godet à dents.','Je sais quoi faire si un réseau est touché : arrêt, périmètre, chef de chantier, exploitant.']},
 {id:'qhs_pointschauds',title:'Points chauds : soudage, meulage, incendie',exemple:true,html:
  P('Souder et meuler, c’est projeter des étincelles à plusieurs mètres, à côté d’isolant polyuréthane, de mousse, de carburant, de haies, de bâches : nos chantiers sont des chantiers à permis feu.')+
  L('Avant chaque point chaud : zone dégagée sur 10 m (isolant, chiffons, bidons, végétation sèche), extincteur à portée de main, couverture antifeu sur ce qui ne peut pas bouger.','Pendant : un regard sur les abords, pas seulement sur le cordon ; en tranchée, attention aux fourreaux et câbles voisins.','Après : surveillance des abords pendant 2 heures (une braise dans l’isolant se réveille tard), ronde avant de quitter le chantier.','Bouteilles de gaz debout, attachées, détendeurs et flexibles contrôlés, pas de bouteille dans la fouille.')+
  OK(P('Je prépare la zone, j’ai l’extincteur à portée de main, et je surveille après le point chaud.')),
  qs:['Je sais où est l’extincteur de mon poste et je l’ai vérifié.','Je dégage et protège les abords avant de souder ou meuler.','Je surveille les abords après le point chaud, avant de quitter le chantier.']},
 {id:'qhs_levage',title:'Manutention et levage des tubes pré-isolés',exemple:true,html:
  P('Un tube pré-isolé de 12 m, c’est plusieurs centaines de kilos qui roulent, basculent et pincent. Les accidents de levage sont rares mais ils sont graves : mains, pieds, et parfois bien pire.')+
  L('Qui lève a son autorisation de conduite et son CACES à jour ; élingues et sangles contrôlées, adaptées à la charge, jamais sur l’isolation seule.','Personne sous la charge, personne entre la charge et un obstacle fixe ; on guide à la longe, pas à la main.','Déchargement de camion : plan de déchargement, calage immédiat, tubes jamais posés au bord de la fouille ni en pente sans butée.','Manutention manuelle : à deux minimum sur les pièces longues, jambes fléchies, gants, chaussures S3 — et on refuse ce qui est trop lourd.')+
  OK(P('Je ne me tiens jamais sous une charge, je guide à la longe et je cale les tubes dès qu’ils sont posés.')),
  qs:['Je ne passe jamais sous une charge ni entre la charge et un obstacle.','Je guide les tubes à la longe, pas à la main.','Je cale les tubes dès la pose et jamais au bord de la fouille.']},
];
