// qhs_scr.js — LES 12 QUARTS D'HEURE SÉCURITÉ SCR (« Annexe 5 — Le Guide Sécurité — 12 Quart d'Heure Sécurité », 24 pages, remis par Ethan le 10/10/2026),
// dématérialisés tels quels : contexte, objectifs, chiffres clés, VRAI / FAUX (avec la bonne réponse), notions clés, conséquences, engagement (slogan).
// Dans l'appli : sujet déroulé en entier → quiz VRAI / FAUX (la bonne réponse s'affiche après chaque réponse) → « Je m'engage » : signature au doigt + retour de l'échange.
// L'animateur (chef de chantier / conducteur qui déclenche) peut clore la séance : retour animateur + signature. Texte repris du document SCR, sans réécriture.
const T=(id,n,title,slogan,o)=>Object.assign({id,n,title,slogan,scr:true},o);
export const QHS_SCR=[
 T('scr01',1,'Ensevelissement','Je descends dans une fouille',{
  contexte:'Les éboulements surviennent lorsque la cohésion du terrain n’est pas garantie. Des facteurs aggravent ce phénomène : vibrations, surcharge, hygrométrie et température. Les métiers du Réseau de Chauffage Urbain sont particulièrement exposés au risque d’éboulement, notamment lors de travaux en tranchée. Même dans une tranchée de faible profondeur, il ne faut pas sous-évaluer les risques. Quelle que soit la taille de la tranchée, les conséquences peuvent être graves.',
  objectifs:['Travailler dans une fouille sécurisée','Revenir sur les règles clés pour éviter tout risque d’ensevelissement'],
  chiffres:['1 m³ de terre qui s’effondre dans une fouille équivaut à une charge de 1,6 tonne sur le corps'],
  vf:[['Lorsque la fouille n’est pas profonde, il n’y a pas de risque ?','F'],['Un blindage est adapté en fonction de la profondeur et de la nature du terrain ?','V'],['Une paroi dressée à la verticale peut garantir la sécurité des salariés ?','F'],['Un examen du blindage doit être effectué par une personne compétente ?','V']],
  notions:[['Même peu profonde, une fouille est risquée',['Même en dessous de 1,30 mètre, une vigilance doit être apportée. Les fouilles en tranchée de plus de 1,30 mètre de profondeur et d’une largeur égale ou inférieure aux deux tiers de la profondeur doivent, lorsque leurs parois sont verticales ou sensiblement verticales, être blindées, étrésillonnées ou étayées.']],
   ['Le blindage doit être contrôlé avant chaque intervention',['Un examen visuel du blindage doit être effectué avant chaque descente dans la tranchée :','Absence ou blindage non correctement posé = je ne descends pas dans la tranchée, je préviens ma hiérarchie et l’entreprise responsable de la sécurisation de la fouille présente sur le chantier.','Je descends dans la tranchée quand elle est sécurisée.']]],
  fin:['Les conséquences humaines : asphyxie, blessures, décès. En plus de séquelles importantes, ces accidents peuvent être à l’origine de traumatismes psychologiques pour les victimes et toute l’équipe qui travaille sur le chantier.','Quelle que soit la durée d’ensevelissement, la victime doit être emmenée rapidement aux urgences afin de suivre des examens en milieu médical.']}),
 T('scr02',2,'Écrasement','J’évite les écrasements',{
  contexte:'S’écraser un doigt avec de l’outillage est une blessure malheureusement courante dans les métiers du réseau de chaleur urbain. Mais sur un chantier, on peut aussi être écrasé par un élément lourd lors de sa pose : tube, masse en mouvement… La vigilance et quelques mesures de prévention limitent beaucoup les risques.',
  objectifs:['Manipuler avec précaution tous types d’objets','Revenir sur les règles clés pour éviter tout risque d’écrasement'],
  chiffres:['En France en 2020, sur 590 000 accidents du travail, 50 % font suite à des manutentions'],
  vf:[['La méconnaissance des règles d’usage est un facteur déclencheur ?','V'],['Le collaborateur désigne lui-même sa zone de sécurité en présence de charges en mouvement ?','F'],['Vérifier les moyens de levage réduit les risques d’écrasement ?','V'],['La prise en compte des éléments extérieurs à risques se fait seulement au jour le jour ?','F']],
  notions:[['Connaître l’utilisation des moyens de levage',['La connaissance des notices d’utilisation des appareils de levage par exemple, permet d’anticiper le potentiel accident de ces phases à risques. De plus, pour prévenir ce risque, mieux vaut ne pas guider la charge avec ses mains mais utiliser quand cela est possible une corde et conserver ainsi une distance de sécurité.']],
   ['Vérifier en amont les éléments extérieurs à risques',['La prise en compte des éléments extérieurs soudains, type rafale de vent, heurt avec structure existante, balan naturel des appareils de levage, etc. doit faire partie intégrante de la réflexion en amont afin d’anticiper et de maîtriser ce risque notamment par des consignes précises lors de la préparation de ces tâches.']]],
  instructions:['Zone de sécurité : présence des collaborateurs interdite dans la tranchée lors du bardage des tubes, à proximité des zones de chargement / déchargement des tubes, à proximité des tubes lors de leur transport.','Je suis autorisé à descendre pour finaliser le guidage en vue de l’accostage et le soudage des tubes.','Je respecte les règles d’élingage et levage : crochet et élingue adaptés et en bon état.'],
  fin:['Je guide la charge à distance à l’aide d’un lien.']}),
 T('scr03',3,'Chute d’objet','Prévenir d’une chute d’objet',{
  contexte:'Charge qui se détache, échelle mal fixée, bord de fouille encombré… Des objets peuvent tomber accidentellement, lors de manutentions, sur les lieux de stockage, autour des postes de travail et chuter sur les collaborateurs.',
  objectifs:['Travailler dans un environnement propre et rangé.','Éviter les blessures suite à la chute d’un objet.'],
  chiffres:['45 000 blessures en France','Les chutes d’objets ou d’équipement ont causé 4 % de toutes les blessures au travail.'],
  vf:[['Si j’ai chaud, j’enlève mon casque ?','F'],['Je stocke mes coudes à un mètre du bord de la fouille ?','V'],['Je pose mes outils là où je le souhaite ?','F'],['Un objet qui tombe d’un mètre ne peut pas me blesser ?','F']],
  notions:[['Maintenir sa zone de travail rangée',['Le maintien de la propreté et de l’ordre est essentiel pour éviter de futurs accidents. Une fois utilisés, les outils doivent être retirés et stockés. De même, les déchets ou débris doivent être supprimés.']],
   ['Prévenir pour réduire le risque',['Bien arrimer les matériaux qui sont entreposés sur le chantier.','Éviter d’empiler des matériaux sur une trop grande hauteur ou de manière instable.','Sécuriser les zones de stockage.']],
   ['Sécuriser les zones à risques',['Il est impératif de sécuriser les zones où des risques peuvent se produire : s’assurer que le blindage de la fouille dépasse de quelques centimètres, éloigner de 40 cm du bord de fouille tous types de matériels et outils, ne pas être présent sous les charges en mouvement…']]],
  fin:['Les EPI (casque, chaussures) ne peuvent protéger qu’une faible charge ou limiter les dommages causés par une charge plus lourde.']}),
 T('scr04',4,'Coupure','Je me protège des coupures',{
  contexte:'Lors des activités de pose du réseau de chaleur urbain, vous pouvez vous couper avec l’outillage, le matériel et même avec les matériaux (partie saillante). De la petite coupure au sectionnement de membre, ce risque est omniprésent sur nos chantiers.',
  objectifs:['Contrôler la conformité de son matériel','Utiliser et entretenir correctement son matériel'],
  chiffres:['45 % des accidents de la vie courante sont dus à des coupures.'],
  vf:[['Je n’utilise pas de gants quand j’utilise un objet tranchant ?','F'],['Une coupure peut provoquer la mort ?','V'],['Pour faciliter la découpe je peux enlever le carter de protection ?','F'],['Je vérifie l’état de mon disque avant chaque utilisation ?','V']],
  notions:[['Coupure lors de manutention manuelle',['La manutention manuelle est une des principales causes de coupure. En soulevant ou en portant des matériaux sans gants on risque de se couper. Même à l’arrêt, les lames de scie, de cutter, restent coupantes. Si les blessures engendrées sont moins importantes qu’avec une machine, le risque de se couper reste important.']],
   ['Les coupures graves et sectionnements',['Le matériel électroportatif est à l’origine de graves accidents du travail. Les membres supérieurs sont les plus touchés : coupures profondes, sectionnement d’un doigt, lésion d’un nerf.','Une coupure mal placée, touchant une artère, peut s’avérer mortelle.']],
   ['J’adapte ma position au travail',['De sérieux risques de se couper profondément avec une machine électroportative existent. Certaines précautions sont à prendre. Faites attention à votre position lorsque vous travaillez. Privilégiez une posture droite avec la machine en face de soi. Veillez à ne pas vous trouver en face de la pièce que vous coupez afin d’éviter d’éventuelles projections.']],
   ['Vérifier l’état de ses disques',['Avant chaque utilisation je vérifie le disque de ma meuleuse afin d’éviter qu’il éclate et que les morceaux viennent se planter dans votre œil, couper une partie du corps…','Dans tous les cas je porte un casque de soudeur quand j’utilise ma meuleuse.']]]}),
 T('scr05',5,'Chute de hauteur','Je me protège des chutes',{
  contexte:'Concernant notre activité de réseau de chauffage les chutes de hauteur sont principalement liées au dénivelé des tranchées. Elles peuvent être dues à une inattention ou à du matériel inadapté ou mal fixé. Des chutes peuvent arriver, même si la tranchée est peu profonde ou peu large, et entraîner des blessures.',
  objectifs:['Analyser la situation de travail et vérifier si toutes les solutions ont été envisagées pour éliminer le danger à la source.'],
  chiffres:['En France, les chutes de hauteur sont la deuxième cause de mortalité au travail ainsi que d’incapacité permanente identifiées.'],
  vf:[['La tranchée n’est pas large, je peux sauter au-dessus sans passer par la passerelle ?','F'],['Une fois installées, je n’ai plus à vérifier les protections mises en place ?','F'],['Je vérifie avant chaque descente si l’échelle est bien fixée ?','V'],['Je fais suivre mon échelle sur ma zone de travail ?','V']],
  notions:[['Il est obligatoire de traverser une tranchée via une passerelle',['Il est important pour la sécurité d’utiliser une passerelle afin de traverser la tranchée même si cette dernière ne semble pas large : en cas de chute elle pourrait engendrer des blessures (entorses, hématomes…).']],
   ['Utiliser l’échelle comme moyen d’accès',['Il faut obligatoirement utiliser l’échelle pour accéder au fond de fouille. Il est impératif de vérifier avant chaque montée et/ou descente si cette dernière est bien fixée et ne présente aucune anomalie de structure. Si l’échelle est non conforme je préviens mon supérieur hiérarchique afin de me mettre en conformité.','Échelle fixée par une corde.']]]}),
 T('scr06',6,'Incendie','Je prends en compte le risque d’incendie',{
  contexte:'Les incendies sur nos chantiers sont peu fréquents mais leurs conséquences peuvent être très lourdes aussi bien pour les collaborateurs que pour l’entreprise. Comment prévenir ce risque, notamment lors de nos interventions proches des réseaux sensibles.',
  objectifs:['Être prêt à contenir les départs d’incendies','Protéger les ouvriers en cas d’incendie'],
  chiffres:['En France, 30 % des incendies déclarés ont pour origine des travaux par points chauds : soudage, meulage'],
  vf:[['J’isole tous les éléments inflammables ?','V'],['Les extincteurs n’ont pas de date de validité ?','F'],['En cas d’incendie j’alerte en premier lieu les pompiers ?','V'],['Une couverture anti-feu n’est pas nécessaire quand on soude ou manchonne ?','VF']],
  notions:[['Isoler tous les éléments inflammables',['Les bouteilles de gaz ne doivent jamais être à proximité d’une zone de travail.','Par ailleurs, si le compagnon soude ou chauffe des éléments en métaux, il doit s’assurer que rien à côté de lui ne puisse prendre feu.']],
   ['Prévoir des extincteurs',['Sur le chantier, vous devez avoir obligatoirement un extincteur à proximité immédiate de votre zone de travail. Il faut veiller à sa bonne place : ne pas encombrer les zones de circulations piétonnes, ne pas risquer une chute dans le fond de fouille, l’avoir à portée de main en cas d’incendie.','Je vérifie régulièrement la date de validité de mon extincteur : si elle est dépassée je préviens ma hiérarchie afin de le remplacer.']],
   ['Appeler les pompiers en cas d’incendie',['Si un incendie survient sur le chantier, il faut contacter les pompiers dans les plus brefs délais ainsi que sa hiérarchie. De plus, pour que les pompiers puissent agir en conséquence, il est important de leur donner le maximum d’informations à savoir : l’adresse du chantier, la nature du feu et l’ampleur des flammes, la nature du comburant.']],
   ['Couverture anti-feu',['Pour toutes interventions à proximité d’un réseau gaz (et tout autre réseau sensible) je mets OBLIGATOIREMENT en place une couverture anti-feu.']]],
  fin:['Voici quelques règles à suivre qui permettent d’évacuer les lieux de l’incendie sur le chantier en toute sécurité : cesser le travail en cours immédiatement ; éteindre tous les appareils électriques ; ne jamais revenir en arrière, quelle qu’en soit la raison ; garder son calme et bien suivre les instructions de la direction, de l’équipe d’évacuation et/ou des services de secours ; rejoindre un point sécurisé.']}),
 T('scr07',7,'Anoxie / asphyxie','Je prends en compte le risque d’asphyxie',{
  contexte:'Travailler dans certains lieux confinés comme une chambre à vannes peut conduire à un risque d’asphyxie ou d’anoxie. De plus, la présence de certains gaz comme le monoxyde de carbone peut entraîner un décès en très peu de temps.',
  objectifs:['Identifier les espaces confinés','Anticiper et préparer l’intervention'],
  chiffres:['Une personne sur cinq pense être alertée par l’odeur en cas d’émanation de monoxyde de carbone, alors que ce gaz ne dégage aucune odeur.'],
  vf:[['Dans un espace clos je mesure constamment la qualité de l’air ?','V'],['Dans un espace peu ventilé je peux travailler seul ?','F'],['Je porte mon capteur 4 gaz en toutes circonstances ?','V'],['En cas de symptômes j’attends la fin d’intervention avant de le signaler ?','F']],
  notions:[['Prendre en compte l’environnement',['Avant chaque intervention dans un lieu confiné : je sécurise ma zone de travail (balisage et signalisation) ; je m’assure que les moyens d’accès à l’espace confiné soient conformes et sécurisés ; je vérifie la qualité de l’air avant de pénétrer ; je mets en place le système de ventilation.']],
   ['Ne jamais intervenir seul',['Dans une fouille peu ventilée, il est interdit d’intervenir seul, il faut toujours intervenir à plusieurs afin d’être alerté rapidement en cas de problème.']],
   ['J’évacue en cas de symptômes',['Lors de votre descente dans une fouille il est impératif de porter votre capteur 4 gaz, ce dernier vous préviendra en cas de taux anormalement élevé d’un gaz dans la fouille. Si votre capteur vous le signale, stoppez votre activité et remontez le signaler à votre chef de chantier.']]],
  fin:['Les effets d’une intoxication au gaz CO. À très faible concentration dans l’air, il diminue l’apport d’oxygène aux organes du corps, car le monoxyde de carbone se fixe 200 fois mieux que l’oxygène sur le noyau de l’hémoglobine. Les premiers symptômes apparaissent dès 0,02 % de concentration de gaz CO dans l’air.','Définitions — Asphyxie : suspension de la respiration liée à une déficience en oxygène. Anoxie : différence défavorable entre les besoins en oxygène et les apports.']}),
 T('scr08',8,'Blessure aggravée','Je diminue les risques de blessures',{
  contexte:'Nous constatons trop souvent des accidents dus au non-port des EPI, qu’ils soient bénins ou graves : coupures, projection dans les yeux, chutes d’objets, blessures liées aux outillages / engins, chute (de personne) de hauteur, etc.',
  objectifs:['Toujours porter ses EPI','Savoir réagir en cas d’accident'],
  chiffres:['En France, le nombre d’accidents de travail avec arrêts liés à un traumatisme représente plus de 4 % du total et 10 % des morts dans le milieu.'],
  vf:[['Je descends de ma pelle, je n’ai pas besoin de porter mon casque ?','F'],['Je me dois de respecter les règles de sécurité pour me protéger et protéger mes collègues ?','V'],['Je quitte le chantier, je ne remets pas le balisage de sécurité en place ?','F'],['En cas de blessure qui me semble anodine je ne préviens pas ?','F']],
  notions:[['EPI obligatoire',['Vous devez porter vos Équipements de Protection Individuelle et vos vêtements de travail en toutes circonstances et sur toute la durée de présence sur le chantier : casque, chaussures de sécurité, vêtements haute visibilité…','En fonction des activités, les EPI doivent être adaptés : je meule = je mets un masque de soudure, bouchons d’oreilles et gants ; je soude = j’ai des vêtements anti-feu et mon casque de soudure…','Casque obligatoire.']],
   ['Réaction en cas d’accident',['Le salarié a lui aussi l’obligation de prendre soin de sa santé, de sa sécurité et de celles de toutes les personnes concernées par ses actes. Il encourt des sanctions disciplinaires lorsqu’il ne porte pas les équipements de protection individuelle qui lui ont été fournis par l’employeur.']],
   ['Balisages et signalisations',['Lorsque je quitte le chantier je m’assure que le chantier soit bien balisé et que la signalisation est en place.','Au cours du chantier si je repère des zones de dangers mal balisées ou mal signalées, alors je mets en place le balisage si je possède l’équipement nécessaire, sinon je préviens ma hiérarchie.']]]}),
 T('scr09',9,'Circulation / accident','Je fais attention à ma conduite',{
  contexte:'Si certaines précautions sont sans doute déjà ancrées dans vos gestes quotidiens, d’autres, tout aussi essentielles, échappent peut-être à votre vigilance. Là est le danger ! Aucun facteur de risque ne doit être négligé.',
  objectifs:['Rouler en sécurité','Zéro accident dans l’entreprise'],
  chiffres:['En 2019, sur 21 165 accidents, 38 % des accidents ont impliqué un usager en trajet domicile-travail ou trajet professionnel.'],
  vf:[['Je reçois un appel en étant conducteur, je peux décrocher ?','F'],['Je peux rattraper mon retard en roulant plus vite ?','F'],['J’effectue un long trajet sans vérifier la pression des pneus ?','F'],['L’alcool et les stupéfiants sont interdits ?','V']],
  notions:[['Ne pas téléphoner au volant',['Téléphoner au volant est strictement interdit. Il met en danger tous les utilisateurs de la route. De plus l’utilisation du téléphone au volant est une infraction passible de 135 € d’amende et d’un retrait de 3 points sur le permis de conduire.','Quand je téléphone je suis à l’arrêt.']],
   ['Respecter le code de la route',['Respecter le code de la route permet : de conserver votre permis et donc votre travail ; de conduire en toute sécurité pour vous et les autres ; de ne pas surconsommer ; de véhiculer une bonne image de l’entreprise ; d’éviter l’usure prématurée de nos véhicules.','N’oubliez pas que notre logo est sur votre camion, votre comportement sur la route reflète l’image de l’entreprise.']],
   ['Alcool et stupéfiants sont interdits',['La drogue et l’alcool au volant ont plusieurs conséquences : provoquer une somnolence ; une diminution de l’attention du conducteur et de ses réflexes ; une mauvaise coordination de ses mouvements ; des troubles de sa vision, des hallucinations ; une sous-estimation du danger.','Il est strictement interdit de prendre le volant après avoir consommé de l’alcool et/ou des stupéfiants.']],
   ['Veiller à l’entretien de son véhicule',['En tant que conducteur d’un véhicule SCR je dois : prendre soin de mon véhicule ; m’assurer que les entretiens périodiques sont à jour (vidange, contrôle technique…) ; avant chaque départ, vérifier la pression des pneus, les niveaux, la propreté et le rangement de mon véhicule ; le nettoyer lorsque cela est nécessaire ; prévenir ma hiérarchie en cas d’avaries (accrochage, vol, dégradation).']]]}),
 T('scr10',10,'Travail isolé','J’adopte la bonne conduite quand je travaille seul',{
  contexte:'Travailler seul multiplie les contraintes de travail et augmente la difficulté de secourir lorsqu’un incident ou un accident survient. Il est nécessaire d’identifier les situations de travail isolé et d’évaluer les risques auxquels les collaborateurs concernés peuvent être exposés.',
  objectifs:['Limiter le travail isolé','Rappeler l’équipement à avoir sur le chantier lorsque je suis seul'],
  chiffres:['En France, 43 % des accidents du travail graves non mortels surviennent lorsque la personne est seule'],
  vf:[['Travailler seul n’est pas dangereux pour moi ?','F'],['Je préviens mes collègues de ma zone d’intervention et j’active mon application PTI si je pars travailler seul ?','V']],
  notions:[['Travailler seul peut être dangereux',['Un travailleur isolé ne peut compter que sur lui-même. En cas de difficultés, ses décisions peuvent être inadaptées et se révéler dangereuses. De plus, quand un accident survient, l’isolement peut être un facteur d’aggravation, le travailleur accidenté pouvant avoir des difficultés à être secouru.']],
   ['Prévenir en cas de travail isolé',['J’utilise l’application Beepiz qui va me permettre de contrôler trois paramètres : immobilité, chute et perte de verticalité.','Je renseigne mon identité et celle de la personne qui me supervise. L’opérateur devra juste l’ouvrir et la laisser active le temps de son intervention isolée.','En cas d’immobilité, de chute ou de perte de verticalité une notification contenant les coordonnées GPS précises sera directement envoyée à la personne enregistrée, qui pourra alors déclencher directement les secours ou faire intervenir un membre de l’équipe.']]],
  fin:['Même seul je porte mes EPI et mes vêtements de travail.']}),
 T('scr11',11,'Hydraulique / électrique','J’anticipe le risque explosion / électrique',{
  contexte:'Les réseaux enterrés de conduites, canalisations, transportant sous pression des fluides (eau, hydrocarbures) et des gaz (vapeur, gaz naturel) ou renfermant des câbles électriques, comportent durant leur construction tout comme durant leur exploitation, des risques d’accidents dont certains peuvent être gravissimes lors de leur pose ou réparation, à la fois pour les travailleurs, la population avoisinante et l’environnement…',
  objectifs:['S’assurer de travailler en sécurité à proximité des réseaux sous tension, sous pression'],
  chiffres:['En France, 43 % des accidents survenant lors d’opérations nécessitant une consignation sont dus à une absence ou à une erreur de cette dernière. Contre seulement 2 % dus à un travail isolé.'],
  vf:[],
  notions:[['1 · Identifiez',['Les différentes sources d’énergie, les risques potentiels ainsi que les points de contrôle (manomètre, jauge, cadran, voyant…).']],
   ['2 · Informez',['Tous les salariés concernés.']],
   ['3 · Séparation',['Des sources d’énergie de l’installation : mise hors tension, fermeture de vannes…']],
   ['4 · Condamnation',['Verrouillage par un dispositif personnalisé et difficilement neutralisable : visible de l’extérieur et réversible uniquement par un outil spécifique à chaque intervenant.']],
   ['5 · Signalisation',['Information claire et permanente de la condamnation : nom de l’intervenant, date et objet de l’arrêt, balisage de la zone.']],
   ['6 · Vérification',['De l’absence d’énergie dans l’installation. S’assurer que personne ne pourrait être blessé avant le test.']],
   ['7 · Effectuez',['L’intervention sur l’installation.']],
   ['8 · Déconsignation',['En fin d’intervention, chaque dispositif doit être enlevé par l’intervenant qui l’a placé. Si besoin prévenir les intervenants avant remise en route.']]],
  qs:['Je connais les 8 étapes de la consignation : identifier, informer, séparer, condamner, signaliser, vérifier, intervenir, déconsigner.','Je n’interviens jamais sur une installation sous tension ou sous pression sans consignation vérifiée.','En fin d’intervention, je retire moi-même le dispositif que j’ai posé.']}),
 T('scr12',12,'Hygiène / santé','Je prends soin de mon hygiène et de ma santé',{
  contexte:'Installations, entretien, nettoyage des lieux, vêtements de travail, lavage des mains… l’hygiène sur les chantiers est essentielle au bien-être au travail et à la sécurité sur les chantiers.',
  objectifs:['Sensibiliser les équipes à l’hygiène sur les chantiers'],
  chiffres:['En France, 93 % des salariés sont plus motivés dans un espace propre et bien rangé'],
  vf:[['Il est préférable de porter ma tenue de travail plusieurs fois dans la semaine ?','F'],['Je me lave régulièrement les mains ?','V'],['Je ne prends pas de substances nocives pour ne pas nuire à ma santé ?','V'],['Je nettoie régulièrement mon poste de travail ?','V']],
  notions:[['Laver régulièrement mes vêtements de travail',['Il est important de laver régulièrement mes vêtements de travail pour plus de confort mais aussi pour répondre à une question d’hygiène importante afin de ne pas tomber malade.']],
   ['Se laver régulièrement les mains',['Se laver régulièrement les mains permet d’éliminer tous les microbes et/ou virus présents sur nos mains mais aussi d’enlever des produits collants, glissants présents dans nos mains.']],
   ['Je nettoie mon chantier quotidiennement',['L’hygiène passe aussi par la propreté des zones de travail (rangement), des cabines de fourgons et des installations mises à disposition sur le chantier.','La propreté du chantier a une importance majeure pour notre qualité de vie au travail. Elle est également bénéfique à l’image de l’entreprise.']]],
  fin:['Qu’entend-on par hygiène sur un chantier ? L’hygiène c’est : 1) l’alimentaire (bien s’hydrater, veiller au rythme des repas, équilibrer ses menus…) ; 2) l’hygiène individuelle (lavage des mains, du corps, l’entretien des pieds…) ; 3) les vêtements de travail ; 4) la base vie.']}),
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const L=a=>a&&a.length?'<ul>'+a.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'';
/* le sujet, prêt à dérouler (même rendu que les modules de prévention de l'accueil chantier) */
export function qhsScrHTML(t){return `<p class="qh-ctx"><b>Contexte.</b> ${esc(t.contexte)}</p>
  <div class="qh-two"><div><h3>Objectifs</h3>${L(t.objectifs)}</div><div><h3>Chiffres clés</h3>${L(t.chiffres)}</div></div>
  <h3>Les notions clés</h3>${(t.notions||[]).map((n,i)=>`<div class="qh-notion"><b>${/^\d+ · /.test(n[0])?'':(i+1)+' · '}${esc(n[0])}</b>${n[1].map(p=>'<p>'+esc(p)+'</p>').join('')}</div>`).join('')}
  ${t.instructions&&t.instructions.length?`<h3>Les instructions SCR</h3><ol>${t.instructions.map(x=>'<li>'+esc(x)+'</li>').join('')}</ol>`:''}
  ${(t.fin||[]).map(p=>'<p class="qh-fin">'+esc(p)+'</p>').join('')}
  <div class="pv-ok"><b>Je m’engage</b><p>${esc(t.slogan)}.</p></div>`;}
/* vue registre : même forme que les sujets importés / exemples */
export const QHS_SCR_TOPICS=QHS_SCR.map(t=>Object.assign({},t,{title:t.n+'. '+t.title,html:qhsScrHTML(t)}));
