// ACCUEIL GÉNÉRAL + ESPACES (refonte 09/10 soir, maquette validée) : l'appli s'ouvre sur l'accueil (avatar, Aujourd'hui, pointage, À faire = notifications
// poussées par les modules (documents QSE à signer, tâches, messages non lus, livraisons, pointages à valider, planning), À savoir, tuiles d'espaces selon les droits),
// barre d'espaces en bas, espace Exploitation (menu, planning des équipes, pointages à valider), une notification ouvre le chantier sur le bon onglet.
// + refonte ② (pointage à états, production des fiches en face du pointage à valider) et ⑤ (tableau de bord du chantier : checklist des 16 modules, bouton 📊 sur la carte).
import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:430,height:900}});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404|WebSocket/i.test(m.text()))logs.push(m.text().slice(0,200));});
page.on('dialog',d=>d.accept().catch(()=>{}));
const C={};
await page.goto(BASE+'/index.html');await page.waitForTimeout(600);await page.evaluate(()=>{localStorage.clear();});await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.reload();await page.waitForTimeout(1200);
const skip=async()=>{const s=await page.$('#loginSkip');if(s&&await s.isVisible())await s.click();await page.waitForTimeout(700);};await skip();
const seed=async()=>page.evaluate(()=>{const T=window.TRACE;const src=T.sites[Object.keys(T.sites).find(k=>k!=='__vide'&&T.sites[k]&&T.sites[k].lines)];if(!src)return 0;const now=new Date().toISOString();
  const mk=(id,name,ville,secteur,extra)=>{if(T.sites[id])return;const x=JSON.parse(JSON.stringify(src));x.id=id;x.name=name;x.fiche={ville,secteur};Object.assign(x,extra||{});T.sites[id]=x;};
  mk('demo_caen','Caen — Presqu\'île','Caen','ouest',{conv:{msgs:[{id:'m1',kind:'msg',by:'Julie M.',text:'Photos du DH tronçon 3 avant 15 h',at:now},{id:'t1',kind:'task',by:'Julie M.',text:'Reprendre S-0041 avant contrôle',task:{to:'tous',done:false},at:now},{id:'u1',kind:'undo',by:'Sofiane K.',text:'doublon',undo:{status:'pending',weldId:'S-0112',n:1},at:now}],seq:4},
    qse:{docs:[{id:'q1',type:'accueil',title:'Accueil chantier du 05/10/2026',by:'Paul D.',at:now,qs:[],sigs:[]}]},stock:{zones:[],lots:[],livs:[{id:'LV1',label:'Camion Renalia n° 3',bl:'BL-4471',date:now.slice(0,10),status:'prevu',prevu:[{label:'Tube DN150',qty:20}]}],moves:[],takes:[]},ts:{items:[{id:'ts1',etat:'propose',label:'Tranchée sup.'},{id:'ts2',etat:'valide',label:'Regard'}]},fiche:{ville:'Caen',secteur:'ouest',chef:'l:ethan'}}); /* Caen : chef de chantier = Ethan (validation des pointages, Mes chantiers) */
  mk('demo_rennes','Rennes — Baud-Chardonnet','Rennes','ouest',{conv:{msgs:[],seq:1}});return Object.keys(T.sites).length;});
console.log('seed',await seed());await page.evaluate(()=>window.TRACE.renderHome());await page.waitForTimeout(400);
// ── 1) ouverture : l'accueil général est l'onglet par défaut ; barre d'espaces selon les droits (Karim, soudeur : pas d'Exploitation ni d'Admin) ; héros + pointage + À faire + À savoir + tuiles
let out=await page.evaluate(()=>{const T=window.TRACE;const q=s=>document.querySelector(s);return {tab:T.state.homeTab,title:(q('.homeSub .t')||{}).textContent,tabs:[...document.querySelectorAll('#homeTabs button')].filter(b=>b.style.display!=='none').map(b=>b.id),on:[...document.querySelectorAll('#homeTabs button.on')].map(b=>b.id),hi:(q('#eq-app .ac-hi')||{}).textContent,hero:!!q('#eq-app .ac-hero'),svg:!!q('#eq-app .ac-hero svg'),pointer:!!q('#eq-app [data-act=pointer][data-v=start]'),subTabs:q('#homeSubTabs').style.display,
  notifs:[...document.querySelectorAll('#eq-app .ac-notif .tx b')].map(b=>b.textContent),kt:[...document.querySelectorAll('#eq-app .ac-kt .tx b')].map(b=>b.textContent),tiles:[...document.querySelectorAll('#eq-app .ac-tile b')].map(b=>b.textContent),st:(q('#eq-app .ac-h .st')||{}).textContent};});
console.log('1) accueil général :',JSON.stringify(out));
C.c1=out.tab==='accueil'&&out.title==='Accueil'&&out.tabs.join()==='htHome,htSites,htEspace,htEnt'&&out.on.join()==='htHome'&&/Bonjour Karim/.test(out.hi)&&out.hero&&out.svg&&out.pointer&&out.subTabs==='none'
  &&out.notifs.length>=4&&/Accueil nouvel arrivant/.test(out.notifs[0])&&/Règlement intérieur/.test(out.notifs[1])&&out.notifs.some(t=>/Accueil chantier à faire : Caen/.test(t))&&out.notifs.some(t=>/1 tâche pour toi sur Caen/.test(t))&&out.notifs.some(t=>/messages? non lus? sur Caen/.test(t))&&out.kt.some(t=>/Planning/.test(t))&&out.tiles.join()==='Mes chantiers,Mon espace,Entreprise'&&/actions attendues/.test(out.st);
// ── 2) ordre des notifications (règle Ethan) : documents d'entreprise → accueil chantier → tâches → messages ; la notification « accueil chantier » ouvre le chantier sur QSE et lance le parcours (PPSPS) ; retour à l'accueil
const idx=t=>out.notifs.findIndex(x=>t.test(x));
C.c2a=idx(/nouvel arrivant/)<idx(/Accueil chantier à faire/)&&idx(/Accueil chantier à faire/)<idx(/tâche/)&&idx(/tâche/)<idx(/message/);
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .ac-notif')].find(x=>/Accueil chantier à faire/.test(x.textContent)).click();});await page.waitForTimeout(1800);
let o2=await page.evaluate(()=>({screen:window.TRACE.state.screen,site:window.TRACE.state.siteId,tab:window.TRACE.state.tab,parcours:/PPSPS/.test(document.getElementById('modal').textContent)}));
await page.evaluate(()=>{const m=document.getElementById('modal');m.classList.remove('show');m.innerHTML='';document.getElementById('btnHome').click();});await page.waitForTimeout(600);
o2.back=await page.evaluate(()=>({screen:window.TRACE.state.screen,tab:window.TRACE.state.homeTab,hi:(document.querySelector('#eq-app .ac-hi')||{}).textContent}));
console.log('2) ordre + ouverture par notification :',JSON.stringify({c2a:C.c2a,...o2}));
C.c2=C.c2a&&o2.screen==='site'&&o2.site==='demo_caen'&&o2.tab==='qse'&&o2.parcours&&o2.back.screen==='home'&&o2.back.tab==='accueil'&&/Bonjour/.test(o2.back.hi);
// ── 3) barre d'espaces : Chantiers (sous-onglets Carte / Liste visibles, cartes), Mon espace (sous-onglets sans « Planning équipe »), retour Accueil
out=await page.evaluate(()=>{document.getElementById('htSites').click();const r={tab:window.TRACE.state.homeTab,sub:document.getElementById('homeSubTabs').style.display,cards:document.querySelectorAll('#homeBody .siteCard').length,title:document.querySelector('.homeSub .t').textContent};document.getElementById('htList').click();r.list=window.TRACE.state.homeTab;r.cardsL=document.querySelectorAll('#homeBody .siteCard').length;
  document.getElementById('htEspace').click();r.espSubs=[...document.querySelectorAll('#eq-app .eq-subs .chip')].map(c=>c.textContent.trim());r.espTitle=document.querySelector('.homeSub .t').textContent;document.getElementById('htHome').click();r.home=window.TRACE.state.homeTab;r.saved=localStorage.getItem('trace:homeTab');return r;});
console.log('3) barre d\'espaces :',JSON.stringify(out));
C.c3=(out.tab==='map'||out.tab==='list')&&out.sub!=='none'&&out.title==='Mes chantiers'&&out.list==='list'&&out.cardsL>=3&&out.espSubs.includes('Accueil')&&!out.espSubs.some(x=>/Planning équipe/.test(x))&&out.espTitle==='Mon espace'&&out.home==='accueil'&&out.saved==='accueil';
// ── 4) Ethan (admin, chef de chantier en démo) : Exploitation + Admin dans la barre ; menu Exploitation ; planning des équipes depuis le menu ; placer Karim ; pointages à valider ; demandes d'annulation (1, depuis la conversation de Caen) ; retour au menu
out=await page.evaluate(()=>{window.TRACE.state.userId='ethan';window.TRACE.renderHome();const r={tabs:[...document.querySelectorAll('#homeTabs button')].filter(b=>b.style.display!=='none').map(b=>b.id),tiles:[...document.querySelectorAll('#eq-app .ac-tile b')].map(b=>b.textContent)};
  document.getElementById('htExpl').click();r.title=document.querySelector('.homeSub .t').textContent;r.rows=[...document.querySelectorAll('#eq-app .ac-row .tx b')].map(b=>b.textContent);r.badges=[...document.querySelectorAll('#eq-app .ac-row .ac-n')].map(b=>b.textContent);
  [...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent)).click();r.orga=!!document.querySelector('#eq-app .eq-pltray');r.back=!!document.querySelector('#eq-app .ac-back');
  const c=[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>/Karim/.test(x.textContent));c.querySelector('.eq-plmain').click();document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] [data-act=plput]').click();r.placed=document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-plchip').length;
  document.querySelector('#eq-app .ac-back').click();r.menuBack=[...document.querySelectorAll('#eq-app .ac-row')].length;
  [...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Demandes d.annulation/.test(x.textContent)).click();r.annul=[...document.querySelectorAll('#eq-app .ac-row .tx b')].map(b=>b.textContent);
  document.querySelector('#eq-app .ac-back').click();[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Pointages à valider/.test(x.textContent)).click();r.valid=document.getElementById('eq-app').textContent.slice(0,400);return r;});
console.log('4) Exploitation :',JSON.stringify({...out,valid:out.valid.slice(0,80)}));
C.c4=out.tabs.includes('htExpl')&&out.tabs.includes('htAdmin')&&out.tiles.includes('Exploitation')&&out.tiles.includes('Administrateur')&&out.title==='Exploitation'&&out.rows.some(t=>/Planning des équipes/.test(t))&&out.rows.some(t=>/Pointages à valider/.test(t))&&out.rows.some(t=>/Demandes d'annulation/.test(t))&&out.badges.some(t=>/à placer/.test(t))&&out.orga&&out.back&&out.placed===1&&out.menuBack>=5&&out.annul.some(t=>/Sofiane K\. · S-0112/.test(t))&&/Pointages à valider|valider/i.test(out.valid);
// ── 5) Karim de retour sur l'accueil : le chantier du jour (planifié à Caen par Ethan) est dans le héros, « Ouvrir le chantier » l'ouvre ; la notification « pas de chantier » a disparu
out=await page.evaluate(async()=>{window.TRACE.state.userId='karim';document.getElementById('htHome').click();await new Promise(r=>setTimeout(r,300));const h=document.querySelector('#eq-app .ac-hero');const r={site:(h.querySelector('.ac-site')||{}).textContent,noPlan:[...document.querySelectorAll('#eq-app .ac-kt .tx b')].some(b=>/Planning/.test(b.textContent)),livr:[...document.querySelectorAll('#eq-app .ac-kt .tx b')].some(b=>/Livraison/.test(b.textContent)),btn:!!h.querySelector('[data-act=opensite]')};h.querySelector('[data-act=opensite]').click();await new Promise(r2=>setTimeout(r2,1500));r.screen=window.TRACE.state.screen;r.siteId=window.TRACE.state.siteId;return r;});
console.log('5) chantier du jour depuis l\'accueil :',JSON.stringify(out));
C.c5=/Caen/.test(out.site)&&!out.noPlan&&out.livr&&out.btn&&out.screen==='site'&&out.siteId==='demo_caen'; /* la livraison prévue sur SON chantier du jour apparaît en « à savoir » une fois placé */
// ── 6) REFONTE ② : Karim est sur le chantier (fiches chargées) → 2 soudures posées aujourd'hui à son nom ; retour accueil : carte pointage à états (pas commencée → au travail + compteur → pause midi → reprise → journée finie)
out=await page.evaluate(async()=>{const T=window.TRACE;const L=Object.values(T.state.lines);const l=L.find(x=>x.cond&&x.cond.A&&x.cond.A.joints&&x.cond.A.joints.length>6)||L[0];const todo=l.cond.A.joints.filter(j=>!j.status||j.status==='a_souder');const at=new Date().toISOString();
  todo.slice(0,2).forEach(j=>{j.steps=j.steps||{};j.steps[1]={done:true,by:'Karim B.',at,photos:['p'],visuel:true};j.status='soudee';});const m=todo[2];if(m){m.steps=m.steps||{};m.steps[1]={done:true,by:'Sofiane K.',at,photos:['p']};m.steps[3]={done:true,by:'Karim B.',at,photos:['p'],type:'retracte',press:true};m.status='manchonnee';} /* + 1 manchon par Karim : DN tube / enveloppe */
  document.getElementById('btnHome').click();await new Promise(r=>setTimeout(r,500));const q=s=>document.querySelector('#eq-app '+s);const st=()=>{const c=q('.ptc');return c?{cls:c.className.replace('card ptc ',''),big:(q('.ptbig')||{}).textContent,btns:[...c.querySelectorAll('[data-act=pointer]')].map(b=>b.dataset.v).join(),el:!!q('#ptElapsed')}:null;};
  const r={posed:todo.slice(0,2).map(j=>j.weldId),s0:st()};const go=async k=>{q('[data-act=pointer][data-v='+k+']').click();await new Promise(r2=>setTimeout(r2,150));return st();};r.s1=await go('start');r.s2=await go('pause');r.s3=await go('resume');r.s4=await go('end');return r;});
console.log('6) pointage à états :',JSON.stringify(out));
C.c6=out.posed.length===2&&out.s0.cls==='pt-off'&&out.s0.btns==='start'&&out.s1.cls==='pt-on'&&/Au travail/.test(out.s1.big)&&out.s1.el&&out.s1.btns==='pause,end'&&out.s2.cls==='pt-pause'&&/En pause/.test(out.s2.big)&&out.s2.btns==='resume,end'&&out.s3.cls==='pt-on'&&out.s4.cls==='pt-done'&&/Journée finie/.test(out.s4.big)&&out.s4.btns==='';
// ── 6b) Mon espace → Productions (Karim) : soudures par DN + manchons par DN tube / enveloppe, plus de pouces
out=await page.evaluate(async()=>{document.getElementById('htEspace').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Productions/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,200));const t=document.getElementById('eq-app').textContent.replace(/\s+/g,' ');return {tiles:[...document.querySelectorAll('#eq-app .eq-tile')].map(x=>x.textContent.replace(/\s+/g,' ').trim()),dn:[...document.querySelectorAll('#eq-app .eq-dn span')].map(x=>x.textContent.replace(/\s+/g,' ').trim()),labs:[...document.querySelectorAll('#eq-app .eq-lab')].map(x=>x.textContent),pouces:/pouce/i.test(t)};});
console.log('6b) Mes productions :',JSON.stringify(out));
C.c6b=out.tiles.some(t=>/^([2-9]|\d\d+)soudures$/.test(t))&&out.tiles.some(t=>/^1manchon$/.test(t))&&out.dn.some(t=>/^DN 100 · ([2-9]|\d\d+)$/.test(t))&&out.dn.some(t=>/^DN 100\/\d+ · 1$/.test(t))&&out.labs.some(t=>/Manchons · DN tube \/ enveloppe/.test(t))&&!out.pouces; /* la semaine compte aussi les soudures de démo signées « karim » */
// ── 7) REFONTE ② : Ethan (chef de Caen) valide → la production du jour lue dans les fiches est EN FACE du pointage (2 soudures, DN), boutons Valider / Corriger
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,300));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Pointages à valider/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,300));
  const rows=[...document.querySelectorAll('#eq-app .eq-vrow')].map(x=>x.textContent.replace(/\s+/g,' ').trim().slice(0,300));return {rows,valider:!!document.querySelector('#eq-app [data-act=valider]'),corr:!!document.querySelector('#eq-app [data-act=corr]')};});
console.log('7) production en face :',JSON.stringify(out));
C.c7=out.rows.length===1&&/Karim B\./.test(out.rows[0])&&/Production du jour : 2 soudures \(DN \d+ × 2\) · 1 manchon \(DN \d+\/\d+ × 1\)/.test(out.rows[0])&&out.valider&&out.corr; /* soudures par DN, manchon « DN tube/enveloppe » — plus de pouces */
// ── 8) REFONTE ⑤ : Exploitation → Mes chantiers (Caen : ✓ n / 16) → tableau de bord : % soudé lu dans les fiches, « Ce qui coince » (phasage et QSE bloquants), 16 cases de checklist, une case ouvre le chantier sur son onglet (Stock)
out=await page.evaluate(async()=>{const T=window.TRACE;document.querySelector('#eq-app .ac-back').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Mes chantiers/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,200));
  const r={list:[...document.querySelectorAll('#eq-app .ac-row')].map(x=>x.textContent.replace(/\s+/g,' ').trim().slice(0,120))};[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Caen/.test(x.textContent)).click();await new Promise(r2=>setTimeout(r2,200));
  r.title=(document.querySelector('#eq-app h2.vt')||{}).textContent;r.stats=[...document.querySelectorAll('#eq-app .ac-stat')].map(x=>x.textContent.replace(/\s+/g,' ').trim());r.coince=(document.querySelector('#eq-app .ac-h')||{}).textContent;
  r.bad=[...document.querySelectorAll('#eq-app .ac-notif.bad .tx b')].map(x=>x.textContent);r.tiles=[...document.querySelectorAll('#eq-app .ac-kt.ac-dk')].map(x=>x.textContent.replace(/\s+/g,' ').trim().slice(0,80));r.chk=document.querySelectorAll('#eq-app .ac-kt.ac-dk .ac-chk').length;
  const t=document.querySelector('#eq-app [data-act=opensite][data-v="demo_caen|stock"]');r.tile=!!t;if(t){t.click();await new Promise(r2=>setTimeout(r2,1500));}r.screen=T.state.screen;r.site=T.state.siteId;r.tab=T.state.tab;return r;});
console.log('8) tableau de bord :',JSON.stringify({...out,tiles:out.tiles.length}));
C.c8=out.list.some(t=>/Caen.*✓ \d+ \/ 16/.test(t))&&/Caen/.test(out.title)&&out.stats.length===3&&/^[1-9]\d? %soudé · \d+ \/ \d+/.test(out.stats[0])&&/bloquant/.test(out.stats[1])&&/\/ 16✓ complets/.test(out.stats[2])&&/Ce qui coince/.test(out.coince)&&out.bad.some(t=>/Phasage/.test(t))&&out.bad.some(t=>/QSE/.test(t))
  &&out.tiles.length===16&&out.chk===16&&out.tiles.some(t=>/Soudures.*\d+ \/ \d+ soudées/.test(t))&&out.tiles.some(t=>/Activité.*soudures? cette semaine/.test(t))&&out.tiles.some(t=>/Stock.*1 livraison/.test(t))&&out.tiles.some(t=>/TS.*2 TS/.test(t))&&out.tile&&out.screen==='site'&&out.site==='demo_caen'&&out.tab==='stock';
// ── 9) REFONTE ⑤ : bouton « 📊 Tableau de bord » sur la carte du chantier (liste) pour l'encadrement seulement ; il ouvre l'espace Exploitation sur le tableau de bord ; Karim (soudeur) ne l'a pas
out=await page.evaluate(async()=>{const T=window.TRACE;document.getElementById('btnHome').click();await new Promise(r=>setTimeout(r,400));document.getElementById('htSites').click();document.getElementById('htList').click();await new Promise(r=>setTimeout(r,300));
  const b=document.querySelector('#homeBody .siteCard [data-dash="demo_caen"]');const r={btn:!!b};if(b){b.click();await new Promise(r2=>setTimeout(r2,400));r.tab=T.state.homeTab;r.title=document.querySelector('.homeSub .t').textContent;r.h2=(document.querySelector('#eq-app h2.vt')||{}).textContent;r.chk=document.querySelectorAll('#eq-app .ac-chk').length;}
  T.state.userId='karim';T.state.homeTab='list';T.renderHome();await new Promise(r2=>setTimeout(r2,200));r.karim=document.querySelectorAll('#homeBody [data-dash]').length;r.cards=document.querySelectorAll('#homeBody .siteCard').length;return r;});
console.log('9) bouton tableau de bord :',JSON.stringify(out));
C.c9=out.btn&&out.tab==='expl'&&out.title==='Exploitation'&&/Caen/.test(out.h2)&&out.chk>=16&&out.karim===0&&out.cards>=3;
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
