// MON ESPACE & ENTREPRISE (import de la maquette, 09/10 soir) : onglets de l'accueil selon les droits, accueil « Bonjour », avatar SCR (kit) modifiable et gardé,
// contact d'urgence enregistré, pointage de la journée gardé, fiche d'une personne (panneau), annuaire Entreprise par poste avec filtres,
// puis avec un serveur simulé : fiches people lues, écritures envoyées par partie (people_set_part) et pointage (pointage_set), écriture en attente rejouée.
import { chromium, devices } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:430,height:900}});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404|WebSocket/i.test(m.text()))logs.push(m.text().slice(0,200));});
page.on('dialog',d=>d.accept().catch(()=>{}));
const C={};
await page.clock.install({time:new Date(2026,9,9,8,30,0)}); /* vendredi 09/10/2026 8 h 30 : le planning ignore le week-end, la date ne doit pas dépendre du jour du test */
await page.goto(BASE+'/index.html');await page.waitForTimeout(600);await page.evaluate(()=>{localStorage.clear();});await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.reload();await page.waitForTimeout(1200);
const skip=async()=>{const s=await page.$('#loginSkip');if(s&&await s.isVisible())await s.click();await page.waitForTimeout(700);};await skip();
// ── 1) accueil hors connexion (personnage Karim B., soudeur) : les onglets Mon espace et Entreprise sont là ; Mon espace → sous-onglets, « Bonjour Karim », avatar SCR dessiné (kit), pointage proposé, fiche
let out=await page.evaluate(()=>{const tabs=[...document.querySelectorAll('.homeTabs button')].filter(b=>b.style.display!=='none').map(b=>b.id);document.getElementById('htEspace').click();
  const app=document.getElementById('eq-app');return {screen:window.TRACE.state.screen,tabs,app:!!app,subs:[...document.querySelectorAll('#eq-app .eq-subs .chip')].map(c=>c.textContent.trim()),h2:(document.querySelector('#eq-app h2.vt')||{}).textContent,svg:document.querySelectorAll('#eq-app svg').length,fig:!!document.querySelector('#eq-app .eq-fig'),pointer:!!document.querySelector('#eq-app [data-act=pointer][data-v=start]'),fiche:/Ta fiche/.test(document.getElementById('eq-app').textContent),title:document.querySelector('.homeSub .t').textContent};});
console.log('1) accueil Mon espace :',JSON.stringify(out));
C.c1=out.screen==='home'&&out.tabs.includes('htEspace')&&out.tabs.includes('htEnt')&&out.app&&out.subs.includes('Accueil')&&out.subs.includes('Avatar')&&out.subs.includes('Heures')&&/Bonjour Karim/.test(out.h2)&&out.svg>0&&out.fig&&out.pointer&&out.fiche&&out.title==='Mon espace';
// ── 2) avatar : sous-onglet Avatar, options du kit (teints, coiffures…), un clic sur un teint change la cfg et l'enregistre (kv) ; « Hors travail / Au travail » bascule la tenue ; réinitialiser
out=await page.evaluate(async()=>{[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Avatar/.test(x.textContent)).click();const app=document.getElementById('eq-app');
  const r={h2:(app.querySelector('h2.vt')||{}).textContent,sw:app.querySelectorAll('.eq-sw').length,th:app.querySelectorAll('.eq-th').length,poste:(app.querySelector('.eq-pill')||{}).textContent,vues:[...app.querySelectorAll('[data-act=av]')].filter(b=>/travail/i.test(b.textContent)).length};
  const teints=[...app.querySelectorAll('.eq-sw')].slice(0,6);const sel0=teints.findIndex(b=>b.getAttribute('aria-pressed')==='true');const cible=teints[(sel0+3)%6];cible.click();await new Promise(z=>setTimeout(z,300));
  const teints2=[...document.querySelectorAll('#eq-app .eq-sw')].slice(0,6);r.sel0=sel0;r.sel1=teints2.findIndex(b=>b.getAttribute('aria-pressed')==='true');
  const E=window.TRACE.espace;const me=window.TRACE.acces.current();r.key=E.key(me);await new Promise(z=>setTimeout(z,900));
  return r;});
out.saved=await page.evaluate(async()=>{const me=window.TRACE.acces.current();const key=window.TRACE.espace.key(me);const req=indexedDB.open('trace-kv');return await new Promise(res=>{req.onsuccess=()=>{const db=req.result;const names=[...db.objectStoreNames];const tx=db.transaction(names[0]);const st=tx.objectStore(names[0]);const g=st.get('trace:people');g.onsuccess=()=>{const v=g.result;res({key,peau:v&&v[key]&&v[key].avatar&&v[key].avatar.peau,stores:names});};g.onerror=()=>res({key,err:true});};req.onerror=()=>res({err:true});});});
console.log('2) avatar :',JSON.stringify(out));
C.c2=/Mon avatar/.test(out.h2)&&out.sw>=6&&out.th>=10&&out.poste==='Soudeur'&&out.vues>=2&&out.sel1!==out.sel0&&out.sel1>=0&&!!out.saved.peau;
// ── 3) rechargement : l'avatar garde le teint choisi (kv) ; le médaillon du planning / de l'annuaire utilise le même profil
const peauChoisie=out.saved.peau;
await page.reload();await page.waitForTimeout(1200);await skip();
out=await page.evaluate(peau=>{document.getElementById('htEspace').click();[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Avatar/.test(x.textContent)).click();const app=document.getElementById('eq-app');
  const sel=[...app.querySelectorAll('.eq-sw')].slice(0,6).findIndex(b=>b.getAttribute('aria-pressed')==='true');const st=window.TRACE.espace.state();const me=window.TRACE.acces.current();const key=window.TRACE.espace.key(me);return {sel,peau,kv:st.people[key]&&st.people[key].avatar&&st.people[key].avatar.peau,tab:window.TRACE.state.homeTab};},peauChoisie);
console.log('3) rechargement :',JSON.stringify(out));
C.c3=out.sel>=0&&out.kv===out.peau&&out.tab==='espace';
// ── 4) contact d'urgence : « Définir », formulaire, enregistrer → affiché dans la fiche et gardé après rechargement
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Accueil/.test(x.textContent)).click();});await page.waitForTimeout(300);
await page.evaluate(()=>document.querySelector('#eq-app [data-act=edit]').click());await page.waitForTimeout(300);
out=await page.evaluate(()=>{const f=document.getElementById('eq-urg-nom');if(!f)return {form:false};f.value='Samira BENALI';document.getElementById('eq-urg-lien').value='épouse';document.getElementById('eq-urg-tel').value='06 39 98 02 01';document.querySelector('#eq-app [data-act=editok]').click();return {form:true,txt:document.getElementById('eq-app').textContent};});
await page.waitForTimeout(500);await page.reload();await page.waitForTimeout(1200);await skip();
out.after=await page.evaluate(()=>{document.getElementById('htEspace').click();return /Samira BENALI \(épouse\) · 06 39 98 02 01/.test(document.getElementById('eq-app').textContent);});
console.log('4) contact d\'urgence :',JSON.stringify({form:out.form,saved:/Samira BENALI/.test(out.txt||''),after:out.after}));
C.c4=out.form&&/Samira BENALI/.test(out.txt)&&out.after;
// ── 5) pointage : « Début de journée » → ligne du jour en cours (heure réelle), boutons Pause / Fin, gardé après rechargement ; Heures : la journée apparaît avec sa barre
out=await page.evaluate(()=>{document.querySelector('#eq-app [data-act=pointer][data-v=start]').click();const app=document.getElementById('eq-app');return {enCours:/Au travail/.test(app.textContent),pause:!!app.querySelector('[data-act=pointer][data-v=pause]'),fin:!!app.querySelector('[data-act=pointer][data-v=end]'),start:!app.querySelector('[data-act=pointer][data-v=start]')};});
await page.waitForTimeout(500);await page.reload();await page.waitForTimeout(1200);await skip();
out.after=await page.evaluate(()=>{document.getElementById('htEspace').click();const app=document.getElementById('eq-app');const r={pause:!!app.querySelector('[data-act=pointer][data-v=pause]')};[...app.querySelectorAll('.eq-subs .chip')].find(x=>/Heures/.test(x.textContent)).click();const a2=document.getElementById('eq-app');r.h2=(a2.querySelector('h2.vt')||{}).textContent;r.bar=!!a2.querySelector('.eq-bar');r.auj=/aujourd/i.test(a2.textContent)||/En cours/.test(a2.textContent);return r;});
console.log('5) pointage :',JSON.stringify(out));
C.c5=out.enCours&&out.pause&&out.fin&&out.start&&out.after.pause&&/Heures/.test(out.after.h2)&&out.after.bar;
// ── 6) Entreprise : par poste, avatars en pied, filtre famille, recherche, fiche d'une autre personne en panneau (téléphone / e-mail), fermeture
out=await page.evaluate(()=>{document.getElementById('htEnt').click();const app=document.getElementById('eq-app');const r={h2:(app.querySelector('h2.vt')||{}).textContent,pers:app.querySelectorAll('.eq-pers').length,groupes:app.querySelectorAll('.eq-ent-g').length,figs:app.querySelectorAll('.eq-pers .eq-fig').length,toi:/Toi/.test(app.textContent),title:document.querySelector('.homeSub .t').textContent};
  const fam=[...app.querySelectorAll('[data-act=ffam]')].find(b=>b.dataset.v==='terrain');fam.click();r.terrain=document.querySelectorAll('#eq-app .eq-pers').length;
  const autre=[...document.querySelectorAll('#eq-app .eq-pers')].find(b=>!/Toi/.test(b.textContent));autre.click();const sh=document.querySelector('#eq-app .eq-sheet');r.sheet=!!sh;r.sheetTxt=sh?sh.textContent:'';r.tel=sh?sh.querySelectorAll('a[href^="tel:"],a[href^="mailto:"]').length:0;
  document.querySelector('#eq-app [data-act=close]').click();r.closed=!document.querySelector('#eq-app .eq-sheet');return r;});
console.log('6) Entreprise :',JSON.stringify({...out,sheetTxt:out.sheetTxt.slice(0,80)}));
C.c6=/Entreprise/.test(out.h2)&&out.pers>=3&&out.groupes>=2&&out.figs>=3&&out.toi&&out.title==='Entreprise'&&out.terrain>=2&&out.terrain<out.pers&&out.sheet&&/Coordonnées/.test(out.sheetTxt)&&out.tel>=2&&out.closed;
// ── 8) PLANNING ÉQUIPE (09/10 soir, hors connexion, personnage Ethan L. administrateur) : sous-onglet, bac « À placer », choisir une personne puis un chantier, jours, retrait, reprise de la semaine passée, gardé après rechargement
const seed=async()=>page.evaluate(()=>{const T=window.TRACE;const src=T.sites[Object.keys(T.sites).find(k=>k!=='__vide'&&T.sites[k]&&T.sites[k].lines)];if(!src)return 0;
  const mk=(id,name,ville,secteur)=>{if(T.sites[id])return;const x=JSON.parse(JSON.stringify(src));x.id=id;x.name=name;x.fiche={ville,secteur};T.sites[id]=x;};mk('demo_caen','Caen — Presqu\'île','Caen','ouest');mk('demo_rennes','Rennes — Baud-Chardonnet','Rennes','ouest');mk('demo_lyon','Lyon — Confluence','Lyon','sudest');return Object.keys(T.sites).length;});
await page.evaluate(()=>{localStorage.setItem('trace:homeTab','espace');});await page.reload();await page.waitForTimeout(1200);await skip();await seed();
const goOrga=async()=>page.evaluate(()=>{window.TRACE.state.userId='ethan';window.TRACE.renderHome();document.getElementById('htExpl').click();const b=[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent));if(b)b.click();return !!b;}); /* refonte 09/10 soir : le planning des équipes vit dans l'espace Exploitation */
out={};out.sub=await goOrga();await page.waitForTimeout(400);
out.karimSub=await page.evaluate(()=>{window.TRACE.state.userId='karim';window.TRACE.renderHome();return document.getElementById('htExpl').style.display!=='none';}); // un soudeur n'a pas l'espace Exploitation
await goOrga();await page.waitForTimeout(400);
out.t0=await page.evaluate(()=>({tray:document.querySelectorAll('#eq-app .eq-pltray .eq-plchip').length,sites:document.querySelectorAll('#eq-app .eq-plsite').length,prog:(document.querySelector('#eq-app .eq-plprog')||{}).textContent,h2:(document.querySelector('#eq-app h2.vt')||{}).textContent}));
// Karim → Caen (toute la semaine), Julien → Rennes
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>/Karim/.test(x.textContent)).querySelector('.eq-plmain').click();});await page.waitForTimeout(200);
out.selDrop=await page.evaluate(()=>({sel:document.querySelectorAll('#eq-app .eq-plchip.sel').length,drop:document.querySelectorAll('#eq-app .eq-plsite.drop').length,btn:document.querySelectorAll('#eq-app [data-act=plput]').length}));
await page.evaluate(()=>document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] [data-act=plput]').click());await page.waitForTimeout(300);
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>/Julien/.test(x.textContent)).querySelector('.eq-plmain').click();document.querySelector('#eq-app .eq-plsite[data-drop=demo_rennes] [data-act=plput]').click();});await page.waitForTimeout(300);
out.t1=await page.evaluate(()=>({tray:document.querySelectorAll('#eq-app .eq-pltray .eq-plchip').length,caen:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-plchip').length,rennes:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_rennes] .eq-plchip').length,prog:(document.querySelector('#eq-app .eq-plprog')||{}).textContent,dotsOn:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-pldots i.on').length}));
// jours : ouvrir l'éditeur de Karim, retirer le vendredi → 4 points ; secteur de rattachement proposé
await page.evaluate(()=>document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] .eq-plchip .eq-plmain').click());await page.waitForTimeout(200);
out.edit=await page.evaluate(()=>{const e=document.querySelector('#eq-app .eq-pledit');return {open:!!e,days:e?e.querySelectorAll('[data-act=plday]').length:0,sect:!!(e&&e.querySelector('select[data-chg=plpers]'))};});
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-pledit [data-act=plday]')].pop().click();});await page.waitForTimeout(200);
out.t2=await page.evaluate(()=>({dotsOn:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-pldots i.on').length,plan:(()=>{const E=window.TRACE.espace.state();const aff=window.TRACE.espace.planning?Object.values(window.TRACE.espace.planning())[0]:null;return aff?Object.keys(aff.aff).length:-1;})()}));
// retirer Julien de Rennes → de retour dans le bac
await page.evaluate(()=>{document.querySelector('#eq-app .eq-plsite[data-drop=demo_rennes] .eq-plchip .eq-plmain').click();});await page.waitForTimeout(200);
await page.evaluate(()=>{document.querySelector('#eq-app .eq-pledit [data-act=plrm]').click();});await page.waitForTimeout(200);
out.t3=await page.evaluate(()=>({tray:document.querySelectorAll('#eq-app .eq-pltray .eq-plchip').length,rennes:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_rennes] .eq-plchip').length,prog:(document.querySelector('#eq-app .eq-plprog')||{}).textContent}));
// semaine prochaine vide → « Reprendre la semaine passée » recopie Karim (4 jours) ; progression
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app [data-act=plweek]')].find(b=>b.dataset.v==='1').click();});await page.waitForTimeout(300);
out.t4=await page.evaluate(()=>({tray:document.querySelectorAll('#eq-app .eq-pltray .eq-plchip').length,place:document.querySelectorAll('#eq-app .eq-plsite .eq-plchip').length,h2:(document.querySelector('#eq-app h2.vt')||{}).textContent}));
await page.evaluate(()=>document.querySelector('#eq-app [data-act=plcopy]').click());await page.waitForTimeout(300);
out.t5=await page.evaluate(()=>({caen:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-plchip').length,dotsOn:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-pldots i.on').length,tray:document.querySelectorAll('#eq-app .eq-pltray .eq-plchip').length}));
// secteur Ouest seulement : Lyon passe dans « autres secteurs » ; fiche chantier (⚙) : changer le secteur de Lyon → Ouest le ramène
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app [data-act=plweek]')].find(b=>b.dataset.v==='0').click();});await page.waitForTimeout(200);
await page.evaluate(()=>{const s=document.querySelector('#eq-app select[data-chg=plSect]');s.value='ouest';s.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(300);
out.t6=await page.evaluate(()=>({main:[...document.querySelectorAll('#eq-app .eq-plsites')][0].querySelectorAll('.eq-plsite').length,hors:document.querySelectorAll('#eq-app details[data-det=plAutres] .eq-plsite').length,lyonHors:!!document.querySelector('#eq-app details[data-det=plAutres] .eq-plsite[data-drop=demo_lyon]')}));
await page.evaluate(()=>{const s=document.querySelector('#eq-app .eq-plsite[data-drop=demo_lyon] select[data-chg=plfiche][data-k=secteur]');s.value='ouest';s.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(500);
out.t7=await page.evaluate(()=>({lyonMain:!!document.querySelector('#eq-app .eq-plsites .eq-plsite[data-drop=demo_lyon]')&&!document.querySelector('#eq-app details[data-det=plAutres] .eq-plsite[data-drop=demo_lyon]'),fiche:window.TRACE.sites.demo_lyon.fiche.secteur}));
// rechargement : le planning est gardé (kv)
await page.reload();await page.waitForTimeout(1200);await skip();await seed();await goOrga();await page.waitForTimeout(500);
out.t8=await page.evaluate(()=>({caen:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-plchip').length,dotsOn:document.querySelectorAll('#eq-app .eq-plsite[data-drop=demo_caen] .eq-pldots i.on').length}));
console.log('8) planning équipe :',JSON.stringify(out));
C.c8=out.sub&&!out.karimSub&&out.t0.tray===3&&out.t0.sites>=4&&/0 \/ 3/.test(out.t0.prog)&&/Planning équipe/.test(out.t0.h2)&&out.selDrop.sel===1&&out.selDrop.drop>=4&&out.selDrop.btn>=4&&out.t1.tray===1&&out.t1.caen===1&&out.t1.rennes===1&&/2 \/ 3/.test(out.t1.prog)&&out.t1.dotsOn===5&&out.edit.open&&out.edit.days===5&&out.edit.sect&&out.t2.dotsOn===4&&out.t3.tray===3&&out.t3.rennes===0&&/0 \/ 3/.test(out.t3.prog)&&/11 jours à pourvoir/.test(out.t3.prog)&&out.t4.tray===3&&out.t4.place===0&&out.t5.caen===1&&out.t5.dotsOn===4&&out.t5.tray===3 /* ③ : Karim placé 4 jours sur 5 reste « à placer » (vendredi libre) */&&out.t6.main===4&&out.t6.hors===1&&out.t6.lyonHors&&out.t7.lyonMain&&out.t7.fiche==='ouest'&&out.t8.caen===1&&out.t8.dotsOn===4;
// ── 9) VERROU DU PLANNING sur l'accueil : Karim (soudeur, planifié à Caen) voit les autres chantiers grisés et ne peut pas les ouvrir ; Caen s'ouvre ; Julien (pas placé) voit tout (règle souple) ; règle stricte → rien ; retour souple
await page.evaluate(()=>{localStorage.setItem('trace:homeTab','list');});await page.reload();await page.waitForTimeout(1200);await skip();await seed();
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='karim';T.renderHome();await new Promise(r=>setTimeout(r,200));const cards=[...document.querySelectorAll('.siteCard')].map(c=>({id:c.dataset.open,locked:c.classList.contains('locked'),txt:c.textContent}));
  const refus=await T.openSiteFromHome('demo_rennes');const stillHome=T.state.screen==='home';const toast=(document.querySelector('#toast')||document.querySelector('.toast')||{}).textContent||'';
  return {cards,refus,stillHome,toast,first:cards[0]&&cards[0].id,locked:T.state.homeLocked};});
out.openCaen=await page.evaluate(async()=>{const T=window.TRACE;const ok=await T.openSiteFromHome('demo_caen');await new Promise(r=>setTimeout(r,800));return {ok:ok!==false,screen:T.state.screen,site:T.state.siteId};});
await page.evaluate(()=>{window.TRACE.showScreen('home');window.TRACE.renderHome();});await page.waitForTimeout(200);
out.julien=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='julien';T.renderHome();await new Promise(r=>setTimeout(r,200));return {locked:[...document.querySelectorAll('.siteCard.locked')].length,n:document.querySelectorAll('.siteCard').length};});
// règle stricte (bouton administrateur dans Planning équipe) : Julien, pas placé, ne voit plus rien ; puis retour
await page.evaluate(()=>{localStorage.setItem('trace:homeTab','espace');});await goOrga();await page.waitForTimeout(300);
out.strictBtn=await page.evaluate(()=>{const b=document.querySelector('#eq-app [data-act=plstrict]');if(!b)return null;const t=b.textContent;b.click();return t;});await page.waitForTimeout(400);
out.strict=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='julien';T.state.homeTab='list';T.renderHome();await new Promise(r=>setTimeout(r,200));return {locked:[...document.querySelectorAll('.siteCard.locked')].length,n:document.querySelectorAll('.siteCard').length,rules:localStorage.getItem('trace:planningRules'),refus:await T.openSiteFromHome('demo_caen')};});
await page.evaluate(()=>{localStorage.setItem('trace:homeTab','espace');});await goOrga();await page.waitForTimeout(300);await page.evaluate(()=>document.querySelector('#eq-app [data-act=plstrict]').click());await page.waitForTimeout(300);
out.back=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='julien';T.state.homeTab='list';T.renderHome();await new Promise(r=>setTimeout(r,200));return {locked:[...document.querySelectorAll('.siteCard.locked')].length,rules:localStorage.getItem('trace:planningRules')};});
console.log('9) verrou planning :',JSON.stringify({...out,cards:out.cards.map(c=>c.id+(c.locked?'🔒':''))}));
C.c9=out.cards.length>=4&&out.cards.filter(c=>c.locked).length===out.cards.length-1&&out.cards.find(c=>c.id==='demo_caen')&&!out.cards.find(c=>c.id==='demo_caen').locked&&out.first==='demo_caen'&&out.cards.filter(c=>c.locked).every(c=>/pas dans ton planning/.test(c.txt))&&out.refus===false&&out.stillHome&&/planning/i.test(out.toast)&&out.locked===out.cards.length-1&&out.openCaen.ok&&out.openCaen.screen==='site'&&out.openCaen.site==='demo_caen'&&out.julien.locked===0&&out.julien.n>=4&&/tout voir/.test(out.strictBtn||'')&&out.strict.locked===out.strict.n&&out.strict.n>=4&&/"strict":true/.test(out.strict.rules||'')&&out.strict.refus===false&&out.back.locked===0&&/"strict":false/.test(out.back.rules||'');
await page.evaluate(()=>{localStorage.setItem('trace:homeTab','espace');});
// ── 7) serveur simulé : fiches people lues (avatar + habilitations), écriture d'une partie → RPC people_set_part avec la clé e-mail, pointage → RPC pointage_set ; refus serveur → gardé en attente et rejoué
let USER={id:'00000000-0000-0000-0000-000000000001',aud:'authenticated',role:'authenticated',email:'k.benali@scr.fr',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-01-01T00:00:00Z'};
let SESSION={access_token:'fake-token',token_type:'bearer',expires_in:86400,expires_at:Math.floor(Date.now()/1000)+86400,refresh_token:'fake-refresh',user:USER};
const META=(id,name,ville,secteur)=>({id,name,supplier:'AXIOM',updated_at:'2026-10-01T10:00:00Z',geo:null,origin:null,bgo:null,sat:'2026-10-01T10:00:00Z',w:100,h:100,bbox:[0,0,100,100],nbox:[10,10,90,90],nw:12,deleted:null,deletedAt:null,builtin:null,ville,chef:null,conducteur:null,secteur});
let PLAN_ROWS=[];
const calls=[];let refuse=false;let sitesSrv=[];
await page.route(u=>u.hostname.endsWith('supabase.co'),route=>{const url=route.request().url();const json=(o,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(o)});
  if(url.includes('/auth/v1/token'))return json(SESSION);if(url.includes('/auth/v1/user'))return json(USER);
  if(url.includes('/rest/v1/profiles')){const rows=[{id:'00000000-0000-0000-0000-000000000001',email:'k.benali@scr.fr',name:'Karim BENALI',prenom:'Karim',nom:'BENALI',poste:'soudeur',role:'soudeur',type:'salarie',admin:false,active:true,created_at:'2026-01-01'},{id:'00000000-0000-0000-0000-000000000002',email:'p.durand@scr.fr',name:'Paul DURAND',prenom:'Paul',nom:'DURAND',poste:'chef',role:'chef',type:'salarie',admin:false,active:true,created_at:'2026-01-02'},{id:'00000000-0000-0000-0000-000000000005',email:'elebihan@scr-soudure.fr',name:'Ethan LE BIHAN',prenom:'Ethan',nom:'LE BIHAN',poste:'resp_exploitation',role:'chef',type:'salarie',admin:true,active:true,created_at:'2026-01-01'},{id:'00000000-0000-0000-0000-000000000004',email:'j.martin@scr.fr',name:'Julie MARTIN',prenom:'Julie',nom:'MARTIN',poste:'conducteur',role:'bureau',type:'salarie',admin:false,active:true,created_at:'2026-01-03'},{id:'00000000-0000-0000-0000-000000000003',email:'m.amrani@interim.fr',name:'Mehdi AMRANI',prenom:'Mehdi',nom:'AMRANI',poste:'manchonneur',role:'manchonneur',type:'interim',sites:['S1'],admin:false,active:true,created_at:'2026-01-03'}];if(url.includes('id=eq.')){const id=decodeURIComponent(url).split('id=eq.')[1].split('&')[0];return json(rows.find(r=>r.id===id)||rows[0]);}return json(rows);}
  if(url.includes('/rest/v1/invites'))return json([]);if(url.includes('/rest/v1/app_settings'))return json([]);
  if(url.includes('/rest/v1/people')){return json([{key:'k.benali@scr.fr',data:{avatar:{peau:'p5',cheveux:'chauve'},tel:'06 39 98 01 01',entree:'2019-03-04',contrat:{type:'CDI'},habs:[{type:'qs141',num:'QS-141-22917',fin:'2026-10-27',piece:'pdf'},{type:'sst',fin:'2026-09-20'}]},updated_at:'2026-10-09T08:00:00Z'},{key:'p.durand@scr.fr',data:{avatar:{barbe:'moustache'}},updated_at:'2026-10-09T08:00:00Z'}]);}
  if(url.includes('/rest/v1/pointages'))return json([]);
  if(url.includes('/rest/v1/planning'))return json(PLAN_ROWS);
  if(url.includes('/rest/v1/rpc/planning_set')){const b=route.request().postDataJSON();calls.push({fn:'planning_set',week:b.p_week,patch:b.p_patch});let row=PLAN_ROWS.find(r=>r.week===b.p_week);if(!row){row={week:b.p_week,data:{aff:{}},updated_at:new Date().toISOString()};PLAN_ROWS.push(row);}Object.entries((b.p_patch||{}).aff||{}).forEach(([k,v])=>{if(v===null)delete row.data.aff[k];else row.data.aff[k]=v;});return json(row);}
  if(url.includes('/rest/v1/rpc/site_set_part')){const b=route.request().postDataJSON();calls.push({fn:'site_set_part',site:b.p_site,key:b.p_key,value:b.p_value});return json(new Date().toISOString());}
  if(url.includes('/rest/v1/rpc/people_set_part')){const b=route.request().postDataJSON();calls.push({fn:'people_set_part',...b});if(refuse)return json({message:'réseau coupé'},500);return json({at:new Date().toISOString(),value:b.p_value});}
  if(url.includes('/rest/v1/rpc/pointage_set')){const b=route.request().postDataJSON();calls.push({fn:'pointage_set',p:b.p_row.p,n:(b.p_row.events||[]).length});return json({id:b.p_row.p+'|'+b.p_row.d,...b.p_row});}
  if(url.includes('/rest/v1/rpc/'))return json([]);if(url.includes('/rest/v1/sites')){if(url.includes('id=eq.'))return json(null);return json(sitesSrv);}if(url.includes('/rest/v1/welds')||url.includes('/rest/v1/line_state')||url.includes('/rest/v1/events'))return json([]);
  return route.fulfill({status:404,contentType:'application/json',body:'{}'});});
const meteoCalls=[];const isoLocal=dt=>dt.getFullYear()+'-'+String(dt.getMonth()+1).padStart(2,'0')+'-'+String(dt.getDate()).padStart(2,'0');
await page.route(u=>/open-meteo\.com$/.test(u.hostname),route=>{const url=route.request().url();const json=o=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(o)});
  if(url.includes('geocoding-api')){meteoCalls.push({geo:decodeURIComponent(url.split('name=')[1].split('&')[0])});return json({results:[{name:'Caen',latitude:49.18,longitude:-0.37,country_code:'FR'}]});}
  meteoCalls.push({fc:url.match(/latitude=([-\d.]+)&longitude=([-\d.]+)/).slice(1,3)});const days=[...Array(7)].map((_,i)=>{const d=new Date(2026,9,9,12);d.setDate(d.getDate()+i);return isoLocal(d);}); /* à partir du « aujourd'hui » de la page (horloge figée au 09/10) */
  return json({daily:{time:days,weathercode:[63,0,71,2,3,1,2],temperature_2m_max:[14,28,5,15,16,17,18],temperature_2m_min:[9,16,-1,8,8,9,9],precipitation_sum:[8,0,2,0,0.2,0,0],precipitation_probability_max:[90,5,60,10,20,5,5]}});});
await page.evaluate(()=>{localStorage.clear();});await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.evaluate(s=>{localStorage.setItem('sb-pghftlepduvfazbiavhq-auth-token',JSON.stringify(s));localStorage.setItem('trace:homeTab','espace');},SESSION);
await page.reload();await page.waitForTimeout(2500);
out=await page.evaluate(()=>{const T=window.TRACE;const app=document.getElementById('eq-app');const E=T.espace.state?T.espace.state():null;return {cloud:!!T.state.cloudUser,screen:T.state.screen,me:T.espace.key(T.acces.current()),h2:(app&&app.querySelector('h2.vt')||{}).textContent,txt:app?app.textContent:'',fig:!!(app&&app.querySelector('.eq-fig'))};});
out.habs=/QS 141 TIG/.test(out.txt)&&/Expire dans/.test(out.txt)&&/SST/.test(out.txt)&&/Expirée depuis/.test(out.txt);out.tel=/06 39 98 01 01/.test(out.txt);out.entree=/04\/03\/2019/.test(out.txt);
// écriture : teint via l'écran Avatar → RPC avec la clé e-mail et la partie avatar
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Avatar/.test(x.textContent)).click();const teints=[...document.querySelectorAll('#eq-app .eq-sw')].slice(0,6);teints[0].click();});await page.waitForTimeout(1500);
const c1=calls.filter(c=>c.fn==='people_set_part');
// pointage : début de journée → RPC pointage_set
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Accueil/.test(x.textContent)).click();document.querySelector('#eq-app [data-act=pointer][data-v=start]').click();});await page.waitForTimeout(1500);
const c2=calls.filter(c=>c.fn==='pointage_set');
// refus serveur → en attente, puis rejoué au rechargement (serveur de nouveau d'accord)
refuse=true;await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-subs .chip')].find(x=>/Avatar/.test(x.textContent)).click();const teints=[...document.querySelectorAll('#eq-app .eq-sw')].slice(0,6);teints[2].click();});await page.waitForTimeout(1500);
const pendBefore=await page.evaluate(()=>window.TRACE.espace.state().pending.length);refuse=false;const n0=calls.length;
await page.reload();await page.waitForTimeout(3000);const pendAfter=await page.evaluate(()=>window.TRACE.espace.state().pending.length);const replayed=calls.slice(n0).filter(c=>c.fn==='people_set_part'&&c.p_part==='avatar').length;
console.log('7) serveur simulé :',JSON.stringify({cloud:out.cloud,screen:out.screen,me:out.me,h2:out.h2,fig:out.fig,habs:out.habs,tel:out.tel,entree:out.entree,c1:c1.map(c=>[c.p_key,c.p_part,c.p_value&&c.p_value.peau]),c2,pendBefore,pendAfter,replayed}));
C.c7=out.cloud&&out.me==='k.benali@scr.fr'&&/Bonjour Karim/.test(out.h2)&&out.fig&&out.habs&&out.tel&&out.entree&&c1.length>=1&&c1[0].p_key==='k.benali@scr.fr'&&c1[0].p_part==='avatar'&&c1[0].p_value.peau==='p1'&&c2.length>=1&&c2[0].p==='k.benali@scr.fr'&&c2[0].n===1&&pendBefore===1&&pendAfter===0&&replayed>=1;
// ── 10) serveur simulé, planning : Julie MARTIN (conducteur) place Karim sur un chantier du serveur → RPC planning_set (semaine ISO, patch par personne) + rattachement au secteur du chantier (people_set_part secteur) ;
//        fiche chantier → RPC site_set_part 'fiche' ; rechargement : le planning du serveur est repris ; puis Karim connecté : l'autre chantier est grisé
USER={...USER,id:'00000000-0000-0000-0000-000000000004',email:'j.martin@scr.fr'};SESSION={...SESSION,user:USER};sitesSrv=[META('SRV_A','Caen — Presqu\'île (serveur)','Caen','ouest'),META('SRV_B','Lille — Fives (serveur)','Lille',null)];PLAN_ROWS=[];
await page.evaluate(()=>{localStorage.clear();});await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.evaluate(s=>{localStorage.setItem('sb-pghftlepduvfazbiavhq-auth-token',JSON.stringify(s));localStorage.setItem('trace:homeTab','espace');},SESSION);
await page.reload();await page.waitForTimeout(3000);
out=await page.evaluate(()=>{const T=window.TRACE;const me=T.acces.current();document.getElementById('htEspace').click();const subs=[...document.querySelectorAll('#eq-app .eq-subs .chip')].map(c=>c.textContent.trim());document.getElementById('htExpl').click();const b=[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent));if(b)b.click();
  return {me:T.espace.key(me),poste:me.poste,subs,expl:document.getElementById('htExpl').style.display!=='none',sites:[...document.querySelectorAll('#eq-app .eq-plsite')].map(x=>x.dataset.drop),tray:[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].map(x=>x.dataset.drag)};});
const n10=calls.length;
await page.evaluate(()=>{[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>x.dataset.drag==='k.benali@scr.fr').querySelector('.eq-plmain').click();document.querySelector('#eq-app .eq-plsite[data-drop=SRV_A] [data-act=plput]').click();});await page.waitForTimeout(1800);
const cPlan=calls.slice(n10).filter(c=>c.fn==='planning_set'),cSect=calls.slice(n10).filter(c=>c.fn==='people_set_part'&&c.p_part==='secteur');
await page.evaluate(()=>{const s=document.querySelector('#eq-app .eq-plsite[data-drop=SRV_B] select[data-chg=plfiche][data-k=secteur]');s.value='idf';s.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(1200);
const cFiche=calls.slice(n10).filter(c=>c.fn==='site_set_part');
out.after=await page.evaluate(()=>({caen:document.querySelectorAll('#eq-app .eq-plsite[data-drop=SRV_A] .eq-plchip').length,pending:window.TRACE.espace.state().pending.length,secteurKarim:(window.TRACE.espace.state().people['k.benali@scr.fr']||{}).secteur,resume:(document.querySelector('#eq-app .eq-plsite[data-drop=SRV_B] .eq-plfd summary')||{}).textContent}));
// rechargement : le planning vient du serveur (PLAN_ROWS), plus rien en attente, Karim toujours sur SRV_A
await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));await page.reload();await page.waitForTimeout(3000);
out.reload=await page.evaluate(()=>{document.getElementById('htExpl').click();const b=[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent));if(b)b.click();return {caen:document.querySelectorAll('#eq-app .eq-plsite[data-drop=SRV_A] .eq-plchip').length,dots:document.querySelectorAll('#eq-app .eq-plsite[data-drop=SRV_A] .eq-pldots i.on').length,weeks:Object.keys(window.TRACE.espace.planning()).length};});
// Karim connecté : liste des chantiers → SRV_B grisé, SRV_A ouvert
USER={...USER,id:'00000000-0000-0000-0000-000000000001',email:'k.benali@scr.fr'};SESSION={...SESSION,user:USER};
await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.evaluate(s=>{localStorage.setItem('sb-pghftlepduvfazbiavhq-auth-token',JSON.stringify(s));localStorage.setItem('trace:homeTab','list');},SESSION);await page.reload();await page.waitForTimeout(3000);
out.karim=await page.evaluate(()=>({me:window.TRACE.espace.key(window.TRACE.acces.current()),cards:[...document.querySelectorAll('.siteCard')].map(c=>c.dataset.open+(c.classList.contains('locked')?'🔒':'')),subs:[...document.querySelectorAll('#eq-app .eq-subs .chip')].length}));
console.log('10) serveur simulé, planning :',JSON.stringify({...out,cPlan:cPlan.map(c=>[c.week,Object.keys(c.patch.aff||{}),Object.keys(c.patch.aff['k.benali@scr.fr']||{}).length]),cSect:cSect.map(c=>[c.p_key,c.p_value]),cFiche:cFiche.map(c=>[c.site,c.key,c.value&&c.value.secteur])}));
C.c10=out.me==='j.martin@scr.fr'&&out.poste==='conducteur'&&out.expl&&out.subs.includes('Accueil')&&out.sites.includes('SRV_A')&&out.sites.includes('SRV_B')&&out.tray.includes('k.benali@scr.fr')&&cPlan.length===1&&/^\d{4}-W\d{2}$/.test(cPlan[0].week)&&Object.keys(cPlan[0].patch.aff).join()==='k.benali@scr.fr'&&Object.keys(cPlan[0].patch.aff['k.benali@scr.fr']).length===5&&Object.values(cPlan[0].patch.aff['k.benali@scr.fr']).every(v=>v.join()==='SRV_A')&&cSect.length===1&&cSect[0].p_key==='k.benali@scr.fr'&&cSect[0].p_value==='ouest'&&cFiche.length===1&&cFiche[0].site==='SRV_B'&&cFiche[0].key==='fiche'&&cFiche[0].value.secteur==='idf'&&out.after.caen===1&&out.after.pending===0&&out.after.secteurKarim==='ouest'&&/Île-de-France/.test(out.after.resume)&&out.reload.caen===1&&out.reload.dots===5&&out.reload.weeks>=1&&out.karim.me==='k.benali@scr.fr'&&out.karim.cards.includes('SRV_A')&&out.karim.cards.includes('SRV_B🔒');
// ── 11) 👁 VOIR L'APPLI COMME… (administrateur connecté, Ethan) : sélecteur à l'accueil → vue de Karim (bandeau, onglet Administrateur caché, chantier hors planning grisé, Mon espace « Bonjour Karim »,
//        rien n'est modifié à sa place : pointer → toast, aucun pointage_set) ; retour à mon compte. MÉTÉO (Open-Meteo simulé) : géocodage de la ville, pluie aujourd'hui → scène et planning.
USER={...USER,id:'00000000-0000-0000-0000-000000000005',email:'elebihan@scr-soudure.fr'};SESSION={...SESSION,user:USER};
await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.evaluate(s=>{localStorage.setItem('sb-pghftlepduvfazbiavhq-auth-token',JSON.stringify(s));localStorage.setItem('trace:homeTab','list');},SESSION);await page.reload();await page.waitForTimeout(3500);
out=await page.evaluate(()=>{const T=window.TRACE;const sel=document.getElementById('homeAs');return {me:T.espace.key(T.acces.current()),admin:T.acces.isAdmin(),bar:!!sel&&document.getElementById('homeAsBar').style.display!=='none',opts:sel?[...sel.options].map(o=>o.value):[],groups:sel?sel.querySelectorAll('optgroup').length:0,adminTab:document.getElementById('htAdmin').style.display!=='none',locked:document.querySelectorAll('.siteCard.locked').length,banner:document.getElementById('homeBanner').style.display};});
const nCalls=calls.length;
await page.evaluate(()=>{const sel=document.getElementById('homeAs');sel.value='acc:00000000-0000-0000-0000-000000000001';sel.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(600);
out.karim=await page.evaluate(()=>{const T=window.TRACE;return {me:T.espace.key(T.acces.current()),test:T.acces.current().test===true,banner:document.getElementById('homeBanner').textContent,adminTab:document.getElementById('htAdmin').style.display!=='none',cards:[...document.querySelectorAll('.siteCard')].map(c=>c.dataset.open+(c.classList.contains('locked')?'🔒':'')),sel:document.getElementById('homeAs').value,who:document.getElementById('homeWho').textContent};});
await page.evaluate(()=>document.getElementById('htEspace').click());await page.waitForTimeout(800);
out.espace=await page.evaluate(()=>{const app=document.getElementById('eq-app');const h2=(app.querySelector('h2.vt')||{}).textContent;const sc=app.querySelector('.eq-scene');const expl=document.getElementById('htExpl').style.display!=='none';const b=app.querySelector('[data-act=pointer][data-v=start]');if(b)b.click();return {h2,expl,subs:[...app.querySelectorAll('.eq-subs .chip')].map(c=>c.textContent.trim()),scene:sc?sc.getAttribute('style'):'',meteo:sc?(sc.querySelector('.eq-meteo')||{}).textContent:'',pointerBtn:!!b};});
await page.waitForTimeout(1200);
out.afterClick=await page.evaluate(()=>({toast:document.getElementById('toast').textContent,enCours:/Au travail/.test(document.getElementById('eq-app').textContent),pending:window.TRACE.espace.state().pending.length}));
out.ptCalls=calls.slice(nCalls).filter(c=>c.fn==='pointage_set').length;
// retour à mon compte (lien du bandeau)
await page.evaluate(()=>document.getElementById('hbMe').click());await page.waitForTimeout(600);
out.back=await page.evaluate(()=>{const T=window.TRACE;return {me:T.espace.key(T.acces.current()),banner:document.getElementById('homeBanner').style.display,adminTab:document.getElementById('htAdmin').style.display!=='none',sel:document.getElementById('homeAs').value,locked:document.querySelectorAll('.siteCard.locked').length};});
// météo : store rempli (géocodage « Caen » puis prévisions), planning → 5 cases météo sous le chantier SRV_A
out.meteo=await page.evaluate(()=>{const T=window.TRACE;const m=T.espace.meteo();const today=(()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');})();const a=m.SRV_A;return {sites:Object.keys(m),ll:a&&a.ll,today:a&&a.days&&a.days[today],n:a?Object.keys(a.days||{}).length:0,kinds:a?Object.values(a.days||{}).map(x=>x[0]):[]};});
await page.evaluate(()=>{document.getElementById('htExpl').click();});await page.waitForTimeout(500);
await page.evaluate(()=>{const b=[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent));b&&b.click();});await page.waitForTimeout(500);
out.plMeteo=await page.evaluate(()=>{const c=document.querySelector('#eq-app .eq-plsite[data-drop=SRV_A] .eq-plmeteo');const cells=c?[...c.querySelectorAll('span')]:[];const today=cells.find(x=>/Pluie/.test(x.getAttribute('title')||''));return {cells:cells.length,txt:c?c.textContent:'',titleToday:today?today.getAttribute('title'):''};}); /* la semaine affichée peut commencer avant aujourd'hui : les jours passés n'ont pas de prévision */
console.log('11) voir comme + météo :',JSON.stringify({...out,meteoCalls:meteoCalls.length}));
C.c11=out.me==='elebihan@scr-soudure.fr'&&out.admin&&out.bar&&out.opts[0]==='__me'&&out.opts.includes('acc:00000000-0000-0000-0000-000000000001')&&out.groups>=2&&out.adminTab&&out.locked===0&&out.banner==='none'
  &&out.karim.me==='k.benali@scr.fr'&&out.karim.test&&/comme Karim BENALI/.test(out.karim.banner)&&/Soudeur/.test(out.karim.banner)&&!out.karim.adminTab&&out.karim.cards.includes('SRV_A')&&out.karim.cards.includes('SRV_B🔒')&&out.karim.sel==='acc:00000000-0000-0000-0000-000000000001'&&/Karim BENALI/.test(out.karim.who)&&/👁/.test(out.karim.who)
  &&/Bonjour Karim/.test(out.espace.h2)&&!out.espace.expl&&out.espace.pointerBtn&&/DCE5EA/i.test(out.espace.scene)&&/Pluie/.test(out.espace.meteo)&&/14 °C/.test(out.espace.meteo)
  &&/rien n'est modifié/.test(out.afterClick.toast)&&!out.afterClick.enCours&&out.afterClick.pending===0&&out.ptCalls===0
  &&out.back.me==='elebihan@scr-soudure.fr'&&out.back.banner==='none'&&out.back.adminTab&&out.back.sel==='__me'&&out.back.locked===0
  &&out.meteo.sites.includes('SRV_A')&&out.meteo.ll&&Math.abs(out.meteo.ll[1]-49.18)<0.01&&out.meteo.today&&out.meteo.today[0]==='pluie'&&out.meteo.today[1]===14&&out.meteo.n===7&&out.meteo.kinds[1]==='chaud'&&out.meteo.kinds[2]==='froid'&&out.meteo.kinds[3]==='frais'
  &&out.plMeteo.cells===5&&/🌧️14°/.test(out.plMeteo.txt)&&/Pluie 14 °C · 8 mm/.test(out.plMeteo.titleToday)&&meteoCalls.length>=2;
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
