// CONVERSATION DU CHANTIER (Ethan 08/10) : messages, note géoréférencée posée sur le plan (pastille, PK de la ligne), photo, tâche assignée → l'opérateur la voit
// (pastille sur l'onglet), la déclare faite avec photo ; filtres ; clic sur une pastille du plan → le message ; persistance sur l'appareil ; droits.
import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:1000,height:940}});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404/i.test(m.text()))logs.push(m.text().slice(0,200));});
page.on('dialog',d=>d.accept().catch(()=>{}));
const C={};
await page.goto(BASE+'/traceur.html');await page.waitForTimeout(500);
await page.evaluate(()=>{localStorage.clear();});await page.reload();await page.waitForTimeout(500);
await page.evaluate(()=>{const S=window.MAQ.state;S.supplier='RENALIA';S.lines=[{id:'L1',name:'Rue de la Gare',dn:150,bar:12,pts:[[10,50],[130,50]],specials:[{id:'v1',type:'valve',m:40}],parent:null}];S.seq=2;window.MAQ.setMode('select');window.MAQ.rebuild();});
await page.click('#bSave');await page.waitForTimeout(200);await page.fill('#svName','Conv test');await page.click('#svOk');await page.waitForTimeout(700);await page.click('#svGo');await page.waitForTimeout(1500);await page.selectOption('#roleSel','ethan');await page.waitForTimeout(300);
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';
// ── 1) onglet présent (après Modifs), vide, composeur avec 📍 / 📷 / tâche
let out=await page.evaluate(()=>{const tabs=[...document.querySelectorAll('#tabbar button')].filter(b=>b.style.display!=='none').map(b=>b.dataset.tab);document.querySelector('#tabbar [data-tab=conv]').click();const v=document.querySelector('#convview');
  return {tabs,active:document.querySelector('#view-conv').classList.contains('active'),title:/Conversation — Conv test/.test(v.textContent),empty:/Rien pour l'instant/.test(v.textContent),pose:!!v.querySelector('#cvPose'),photo:!!v.querySelector('#cvPhoto'),task:!!v.querySelector('#cvTask'),send:!!v.querySelector('#cvSend')};});
console.log('1) onglet Conversation :',JSON.stringify(out));C.c1=out.tabs.indexOf('ts')<out.tabs.indexOf('conv')&&out.tabs.indexOf('conv')<out.tabs.indexOf('qse')&&out.active&&out.title&&out.empty&&out.pose&&out.photo&&out.task&&out.send;
// ── 2) message simple
await page.fill('#cvText','Bonjour à tous, réunion de chantier à 14h');await page.click('#cvSend');await page.waitForTimeout(400);
out=await page.evaluate(()=>{const C=window.TRACE.net.conv;const m=C.msgs[0];return {n:C.msgs.length,kind:m.kind,by:m.by,txt:m.text,shown:/réunion de chantier/.test(document.querySelector('#cvList').textContent),mine:!!document.querySelector('.cvMsg.mine'),draftCleared:(document.querySelector('#cvText').value||'')===''};});
console.log('2) message :',JSON.stringify(out));C.c2=out.n===1&&out.kind==='msg'&&out.by==='Ethan L.'&&out.shown&&out.mine&&out.draftCleared;
// ── 3) note géoréférencée : 📍 → le plan → tap sur la conduite (PK 40 ≈ la vanne) → retour conversation avec la position, photo, envoi → pastille sur le plan
await page.fill('#cvText','Vanne fermée, ne pas ouvrir');await page.click('#cvPose');await page.waitForTimeout(300);
out=await page.evaluate(()=>({tab:window.TRACE.state.tab,pose:!!window.TRACE.state.convPose,pill:!!document.querySelector('#planPills [data-pill=conv]'),btn:document.querySelector('#btnConvNote')&&document.querySelector('#btnConvNote').textContent}));
await page.evaluate(()=>{const T=window.TRACE;const L=Object.values(T.lines)[0];const q=T.hydro.nearest(50,50);T.conv.tap(50.3,50.2);});await page.waitForTimeout(400);
out.after=await page.evaluate(()=>{const d=window.TRACE.state.convDraft;return {tab:window.TRACE.state.tab,pos:d&&d.pos,line:d&&d.line,pk:d&&d.pk,chip:/S-\d{4}/.test(document.querySelector('.cvComposer').textContent),text:document.querySelector('#cvText').value};});
await page.evaluate(PNG=>{const d=window.TRACE.state.convDraft;d.photos.push(PNG);window.TRACE.conv.render();},PNG);await page.waitForTimeout(200);
await page.click('#cvSend');await page.waitForTimeout(500);
out.sent=await page.evaluate(()=>{const C=window.TRACE.net.conv;const m=C.msgs[1];const pins=document.querySelectorAll('#convG [data-conv]');return {kind:m.kind,pos:!!m.pos,line:m.line,pk:m.pk,photos:m.photos.length,pins:pins.length,pinId:pins[0]&&pins[0].dataset.conv===m.id,noPose:!window.TRACE.state.convPose,goBtn:!!document.querySelector('[data-cvgo]')};});
console.log('3) note sur le plan :',JSON.stringify(out));C.c3=out.tab==='plan'&&out.pose&&out.pill&&/Annuler/.test(out.btn||'')&&out.after.tab==='conv'&&out.after.pos&&out.after.line==='L1'&&Math.abs(out.after.pk-40)<2&&out.after.chip&&/Vanne fermée/.test(out.after.text)&&out.sent.kind==='note'&&out.sent.pos&&out.sent.line==='L1'&&out.sent.photos===1&&out.sent.pins===1&&out.sent.pinId&&out.sent.noPose&&out.sent.goBtn;
// ── 4) tâche assignée à Karim (chef → opérateur) ; Karim la voit (pastille sur l'onglet, filtre « mes tâches ») et la déclare faite avec photo
await page.evaluate(()=>{document.querySelector('#cvTask').click();});await page.waitForTimeout(200);await page.selectOption('#cvTo','Karim B.');await page.fill('#cvText','Vannes dans le conteneur à souder (sous-station)');await page.click('#cvSend');await page.waitForTimeout(400);
out=await page.evaluate(()=>{const C=window.TRACE.net.conv;const m=C.msgs[2];return {kind:m.kind,to:m.task&&m.task.to,open0:m.task&&m.task.done===false,tag:/à faire/.test(document.querySelector('#cvList').textContent),badgeEthan:!!document.querySelector('#tabbar [data-tab=conv] .qseBadge')};});
await page.selectOption('#roleSel','karim');await page.waitForTimeout(300);
out.k=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();const badge=document.querySelector('#tabbar [data-tab=conv] .qseBadge');document.querySelector('[data-cvf=mine]').click();const n=document.querySelectorAll('#cvList .cvMsg').length;const btn=document.querySelector('[data-cvdone]');return {mine:T.conv.mine().length,badge:badge&&badge.textContent,n,btn:!!btn};});
await page.evaluate(()=>document.querySelector('[data-cvdone]').click());await page.waitForTimeout(300);
await page.evaluate(PNG=>{const m=document.getElementById('modal');m.querySelector('#cvdNote').value='2 vannes soudées';const th=m.querySelector('#cvdThumbs');th.innerHTML='<div class="thumb"><img src="'+PNG+'"></div>';},PNG);
// la photo passe par l'input fichier normalement ; ici on simule via l'API interne : on pousse directement la photo de preuve puis on valide
await page.evaluate(PNG=>{const C=window.TRACE.net.conv;const m=C.msgs[2];document.getElementById('cvdOk').click();},PNG);await page.waitForTimeout(500);
out.done=await page.evaluate(()=>{const C=window.TRACE.net.conv;const m=C.msgs[2];const pin=[...document.querySelectorAll('#convG [data-conv]')];return {done:m.task.done,by:m.task.doneBy,note:m.task.doneNote,badgeGone:!document.querySelector('#tabbar [data-tab=conv] .qseBadge'),mine:window.TRACE.conv.mine().length,fait:/✓ fait/.test(document.querySelector('#convview').textContent)||/fait/.test(document.querySelector('#convview').textContent)};});
console.log('4) tâche → faite :',JSON.stringify(out));C.c4=out.kind==='task'&&out.to==='Karim B.'&&out.open0&&out.tag&&!out.badgeEthan&&out.k.mine===1&&out.k.badge==='1'&&out.k.n===1&&out.k.btn&&out.done.done===true&&out.done.by==='Karim B.'&&out.done.note==='2 vannes soudées'&&out.done.badgeGone&&out.done.mine===0;
// ── 5) clic sur la pastille du plan → la conversation s'ouvre sur le message ; filtre « sur le plan » ; bouton « voir sur le plan »
await page.selectOption('#roleSel','ethan');await page.waitForTimeout(200);
out=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();document.querySelector('[data-cvf=all]').click();T.state.tab='plan';T.renderAll();const pin=document.querySelector('#convG [data-conv]');T.conv.open(pin.dataset.conv); /* les pastilles suivent les filtres de la conversation : on remet « Tout » */const f=document.querySelector('.cvMsg.flash');return {tab:T.state.tab,flash:!!f,id:f&&f.dataset.cvid===pin.dataset.conv};});
await page.evaluate(()=>document.querySelector('[data-cvf=notes]').click());await page.waitForTimeout(200);
out.notes=await page.evaluate(()=>document.querySelectorAll('#cvList .cvMsg').length);
await page.evaluate(()=>document.querySelector('[data-cvgo]').click());await page.waitForTimeout(300);out.go=await page.evaluate(()=>window.TRACE.state.tab);
console.log('5) pastille → message, filtres, voir sur le plan :',JSON.stringify(out));C.c5=out.tab==='conv'&&out.flash&&out.id&&out.notes===1&&out.go==='plan';
// ── 6) droits : un visiteur (démo : compte local inactif → pas de droits) ne peut pas écrire ; persistance après rechargement (handoff)
out=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();const canK=T.acces.can('conv.post');return {canK};});
const siteId=await page.evaluate(()=>window.TRACE.state.siteId);await page.reload();await page.waitForTimeout(1500);await page.evaluate(id=>window.TRACE.go(id),siteId);await page.waitForTimeout(2500);await page.selectOption('#roleSel','ethan');await page.waitForTimeout(300);
out.after=await page.evaluate(()=>{const C=window.TRACE.net.conv;window.TRACE.state.tab='conv';window.TRACE.renderAll();return {n:C&&C.msgs.length,task:C&&C.msgs[2]&&C.msgs[2].task.done,pins:document.querySelectorAll('#convG [data-conv]').length,shown:document.querySelectorAll('#cvList .cvMsg').length};});
console.log('6) droits + rechargement :',JSON.stringify(out));C.c6=out.canK&&out.after.n===3&&out.after.task===true&&out.after.pins===1&&out.after.shown===3;
// ── 7) filtres à plusieurs choix (Ethan 08/10 : « cocher plusieurs choix, messages ET tâches ») : Messages seul, puis + Faites ; « Tout » remet tout ; les pastilles du plan suivent
out=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();const v=document.querySelector('#convview');const n=()=>document.querySelectorAll('#cvList .cvMsg').length;const act=()=>[...v.querySelectorAll('[data-cvf].active')].map(b=>b.dataset.cvf).join(',');
  const r={all:n(),act0:act()};v.querySelector('[data-cvf=msg]').click();r.msg=n();r.act1=act();r.pins1=document.querySelectorAll('#convG [data-conv]').length;
  document.querySelector('#convview [data-cvf=done]').click();r.both=n();r.act2=act();r.hint=/masqué/.test(document.querySelector('#convview').textContent);
  document.querySelector('#convview [data-cvf=msg]').click();r.doneOnly=n();r.act3=act();r.pins3=document.querySelectorAll('#convG [data-conv]').length;
  document.querySelector('#convview [data-cvf=all]').click();r.back=n();r.act4=act();r.pins4=document.querySelectorAll('#convG [data-conv]').length;return r;});
console.log('7) filtres multiples :',JSON.stringify(out));C.c7=out.all===3&&out.act0==='all'&&out.msg===2&&out.act1==='msg'&&out.pins1===1&&out.both===3&&out.act2==='msg,done'&&out.doneOnly===1&&out.act3==='done'&&out.pins3===0&&out.back===3&&out.act4==='all'&&out.pins4===1;
// ── 8) période : « Aujourd'hui » garde tout (tout date d'aujourd'hui) ; une période passée vide la liste ET le plan ; « Toute la période » revient ; 👁 « Conversation » masque les pastilles
out=await page.evaluate(()=>{const T=window.TRACE;const v=document.querySelector('#convview');v.querySelector('[data-cvrange]').click();const r={ui:!!document.querySelector('#cvDFrom')};document.querySelector('[data-cvpre="today"]').click();r.today=document.querySelectorAll('#cvList .cvMsg').length;r.chip=document.querySelector('[data-cvrange]').textContent;
  const fi=document.querySelector('#cvDFrom'),ti=document.querySelector('#cvDTo');fi.value='2020-01-01';fi.dispatchEvent(new Event('change'));document.querySelector('#cvDTo').value='2020-01-31';document.querySelector('#cvDTo').dispatchEvent(new Event('change'));r.past=document.querySelectorAll('#cvList .cvMsg').length;r.pinsPast=document.querySelectorAll('#convG [data-conv]').length;r.range=JSON.stringify(T.state.convRange);
  document.querySelector('[data-cvpre="clear"]').click();r.cleared=document.querySelectorAll('#cvList .cvMsg').length;r.pins=document.querySelectorAll('#convG [data-conv]').length;
  T.state.show.conv=false;T.renderPlan();r.hidden=document.querySelectorAll('#convG [data-conv]').length;T.state.show.conv=true;T.renderPlan();r.shown=document.querySelectorAll('#convG [data-conv]').length;r.eye=/Conversation : notes et tâches/.test(document.querySelector('#disp')?document.querySelector('#disp').textContent:'');return r;});
console.log('8) période + 👁 :',JSON.stringify(out));C.c8=out.ui&&out.today===3&&/du \d\d\/\d\d au/.test(out.chip)&&out.past===0&&out.pinsPast===0&&/2020-01-01/.test(out.range)&&out.cleared===3&&out.pins===1&&out.hidden===0&&out.shown===1;
// ── 9) non-lus : Karim filtre sur « Faites » et quitte l'onglet ; Ethan écrit (un autre appareil : on recule le repère « vu ») ; Karim revient : pastille sur l'onglet, puis alerte « 1 non lu masqué par tes filtres » → Tout afficher
await page.selectOption('#roleSel','karim');await page.waitForTimeout(200);
await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();document.querySelector('#convview [data-cvf=done]').click();T.state.tab='plan';T.renderAll();});
await page.selectOption('#roleSel','ethan');await page.waitForTimeout(200);
await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();T.state.convDraft={text:'Balisage zone B posé, photo faite',photos:[],pos:null,line:null,pk:null,task:null,to:'tous'};T.conv.render();document.querySelector('#cvSend').click();});await page.waitForTimeout(400);
await page.evaluate(()=>{const T=window.TRACE;T.state.tab='plan';T.renderAll();localStorage.setItem('trace:convSeen:'+T.net.id,'2020-01-01T00:00:00.000Z');}); // comme si Karim n'avait jamais vu ce message (autre appareil)
await page.selectOption('#roleSel','karim');await page.waitForTimeout(200);
out=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='plan';T.renderAll();const b=document.querySelector('#tabbar [data-tab="conv"] .qseBadge');const r={badge:b?b.textContent:null,unread:T.conv.unread().length};
  T.state.tab='conv';T.renderAll();const v=document.querySelector('#convview');r.alert=/non lu/.test(v.textContent)&&/masqué/.test(v.textContent);r.shown=document.querySelectorAll('#cvList .cvMsg').length;const btn=[...v.querySelectorAll('[data-cvf=all]')].pop();btn.click();r.after=document.querySelectorAll('#cvList .cvMsg').length;r.alertGone=!/non lu/.test(document.querySelector('#convview').textContent);
  T.state.tab='plan';T.renderAll();const b2=document.querySelector('#tabbar [data-tab="conv"] .qseBadge');r.badge2=b2?b2.textContent:null;return r;});
console.log('9) non-lus masqués :',JSON.stringify(out));C.c9=out.badge==='4'&&out.unread===4&&out.alert&&out.shown===1&&out.after===4&&out.alertGone&&out.badge2===null;
// ── 10) types de message (Ethan 09/10 : « des icônes selon ce que c'est — barriérage, tranchée, stockage, sécurité ») : 🚧 Balisage posé sur le plan → icône sur la carte ET sur la pastille ; filtre « Type »
out=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='conv';T.renderAll();const v=document.querySelector('#convview');const cats=[...v.querySelectorAll('[data-cvcat]')].map(b=>b.dataset.cvcat);const r={cats,def:(v.querySelector('[data-cvcat].active')||{}).dataset.cvcat};
  v.querySelector('[data-cvcat=balisage]').click();r.sel=(document.querySelector('#convview [data-cvcat].active')||{}).dataset.cvcat;
  T.state.convDraft.text='Barrières posées rue de la Gare, zone fermée';T.conv.tap(70,50.4);T.state.tab='conv';T.renderAll();document.querySelector('#cvSend').click();return r;});
await page.waitForTimeout(500);
out.m=await page.evaluate(()=>{const T=window.TRACE;const C=T.net.conv;const m=C.msgs[C.msgs.length-1];const card=document.querySelector('[data-cvid="'+m.id+'"]');const pin=document.querySelector('#convG [data-conv="'+m.id+'"]');const sel=document.querySelector('#cvCatSel');
  const r={cat:m.cat,near:Array.isArray(m.near)&&m.near.length,icon:card&&/🚧/.test(card.querySelector('.cvHead').textContent),pinGlyph:pin&&pin.querySelector('text').textContent,pins:document.querySelectorAll('#convG [data-conv]').length,opts:sel?[...sel.options].map(o=>o.value).join(','):null};
  sel.value='balisage';sel.dispatchEvent(new Event('change'));r.typed=document.querySelectorAll('#cvList .cvMsg').length;r.pinsTyped=document.querySelectorAll('#convG [data-conv]').length;r.onlyBal=[...document.querySelectorAll('#cvList .cvMsg')].every(c=>/🚧/.test(c.querySelector('.cvHead').textContent));
  const s2=document.querySelector('#cvCatSel');s2.value='';s2.dispatchEvent(new Event('change'));r.back=document.querySelectorAll('#cvList .cvMsg').length;r.pinsBack=document.querySelectorAll('#convG [data-conv]').length;return r;});
console.log('10) types :',JSON.stringify(out));C.c10=out.cats.length===9&&out.cats[0]==='balisage'&&out.cats.includes('tranchee')&&out.cats.includes('stockage')&&out.cats.includes('securite')&&out.def==='divers'&&out.sel==='balisage'&&out.m.cat==='balisage'&&out.m.near>=1&&out.m.icon&&out.m.pinGlyph==='🚧'&&out.m.pins===2&&/balisage/.test(out.m.opts)&&/divers/.test(out.m.opts)&&out.m.typed===1&&out.m.pinsTyped===1&&out.m.onlyBal&&out.m.back===5&&out.m.pinsBack===2;
// ── 11) plan dépollué (Ethan 09/10 : « une tâche faite, le check vert ne doit pas rester sur le plan ») : tâche posée sur le plan → pastille ; faite → plus de pastille ; filtre « Faites », période ou 👁 « tout l'historique » la font revenir ; une note de 30 jours disparaît aussi du plan (reste dans la liste)
await page.selectOption('#roleSel','ethan');await page.waitForTimeout(200); /* Karim (soudeur) ne crée pas de tâche */
out=await page.evaluate(()=>{const T=window.TRACE;const S=T.state;S.tab='conv';T.renderAll();S.convDraft={text:'Remettre les barrières après le passage du camion',photos:[],pos:[90,50.3],line:'L1',pk:80,near:null,task:{},to:'tous',cat:'balisage'};T.conv.render();document.querySelector('#cvSend').click();return true;});
await page.waitForTimeout(400);
out=await page.evaluate(()=>{const T=window.TRACE;const S=T.state;const C=T.net.conv;const m=C.msgs[C.msgs.length-1];const pins=()=>document.querySelectorAll('#convG [data-conv]').length;const has=()=>!!document.querySelector('#convG [data-conv="'+m.id+'"]');const r={kind:m.kind,open:has(),bang:!!document.querySelector('#convG [data-conv="'+m.id+'"] circle[fill="#d03b3b"]'),pins0:pins()};
  m.task.done=true;m.task.doneAt=new Date().toISOString();m.task.doneBy='Karim B.';T.renderPlan();r.doneHidden=!has();r.onPlan=T.conv.onPlan(m);r.visible=T.conv.visible(m);
  S.tab='conv';T.renderAll();document.querySelector('#convview [data-cvf=done]').click();r.withDoneFilter=has();document.querySelector('#convview [data-cvf=all]').click();r.afterAll=!has();
  S.show.convAll=true;T.renderPlan();r.withAll=has();S.show.convAll=false;T.renderPlan();r.afterAllOff=!has();
  S.convRange={from:'2020-01-01',to:'2099-12-31'};T.renderPlan();r.withRange=has();S.convRange=null;T.renderPlan();
  const note=C.msgs[1];const at0=note.at;note.at=new Date(Date.now()-30*864e5).toISOString();T.renderPlan();r.oldHidden=!document.querySelector('#convG [data-conv="'+note.id+'"]');S.tab='conv';T.renderAll();r.oldListed=!!document.querySelector('#cvList [data-cvid="'+note.id+'"]');
  document.querySelector('#convview [data-cvrange]').click();document.querySelector('#convview [data-cvpre="30"]').click();r.old30=!!document.querySelector('#convG [data-conv="'+note.id+'"]');document.querySelector('#convview [data-cvpre="clear"]').click();note.at=at0;T.renderPlan();r.restored=!!document.querySelector('#convG [data-conv="'+note.id+'"]');
  S.tab='plan';T.renderAll();const eb=document.querySelector('.zoomctl [data-z=eye]');if(eb)eb.click();r.eye=/tout l'historique/.test(document.querySelector('#disp')?document.querySelector('#disp').textContent:'');r.eyeOff=!!document.querySelector('#disp input[data-k=convAll]')&&!document.querySelector('#disp input[data-k=convAll]').checked;if(eb)eb.click();S.tab='conv';T.renderAll();r.hint=/7 derniers jours/.test(document.querySelector('#convview').textContent);return r;});
console.log('11) plan dépollué :',JSON.stringify(out));C.c11=out.kind==='task'&&out.open&&out.bang&&out.pins0===3&&out.doneHidden&&out.onPlan===false&&out.visible===true&&out.withDoneFilter&&out.afterAll&&out.withAll&&out.afterAllOff&&out.withRange&&out.oldHidden&&out.oldListed&&out.old30&&out.restored&&out.eye&&out.eyeOff&&out.hint;
// ── 12) localiser par les n° de soudure (Ethan 09/10 : « les "Ligne L13…" personne va comprendre ») : « entre S-0003 et S-0004 · Rue de la Gare » ; une ligne nommée « Ligne L13 » n'est pas citée
out=await page.evaluate(()=>{const T=window.TRACE;const C=T.net.conv;const note=C.msgs[1];const l=T.lines.L1;const r={txt:T.conv.loc(note),near:note.near&&note.near.slice(0,2)};
  const q=T.hydro.nearest(56,50.1);const mid={near:T.conv.near(56,50.1),line:q&&q.line,pk:q&&+q.m.toFixed(1),pos:[56,50.1]};r.mid=T.conv.loc(mid);r.midPk=mid.pk;r.midNear=mid.near.slice(0,3);
  const n0=l.name;l.name='Ligne L13';r.generic=T.conv.loc(mid);l.name='Antenne A2';r.generic2=T.conv.loc(mid);l.name=n0;
  r.far=T.conv.loc({near:[{id:'S-0007',line:'L1',cond:'A',idx:6,m:84,d:23.4}],line:null,pk:null});r.on=T.conv.loc({near:[{id:'S-0007',line:'L1',cond:'A',idx:6,m:84,d:0.4}]});r.none=T.conv.loc({near:null,line:'L1',pk:12});r.nothing=T.conv.loc({});
  r.card=document.querySelector('#cvList [data-cvid="'+note.id+'"] [data-cvgo]').textContent;return r;});
console.log('12) localisation :',JSON.stringify(out));C.c12=/^sur S-\d{4} · Rue de la Gare$/.test(out.txt)&&/^entre S-\d{4} et S-\d{4} · Rue de la Gare$/.test(out.mid)&&/^entre S-\d{4} et S-\d{4}$/.test(out.generic)&&out.generic2===out.generic&&out.far==='à 23,4 m de S-0007'&&out.on==='sur S-0007'&&out.none==='Rue de la Gare · PK 12 m'&&out.nothing==='voir sur le plan'&&/sur S-\d{4} · Rue de la Gare/.test(out.card);
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
