// BUREAU DU CHANTIER (onglet « Bureau », nuit 09→10/10) : premier onglet du chantier — infos de la fiche, « aujourd'hui » (accueil à faire, QSE, objectif, tâches, messages),
// checklist + « ce qui coince » pour l'encadrement, raccourcis vers les onglets ; les onglets existants ne bougent pas ; le tableau de bord de l'accueil ouvre le bureau.
import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:430,height:900}});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404|WebSocket/i.test(m.text()))logs.push(m.text().slice(0,200));});
page.on('dialog',d=>d.accept().catch(()=>{}));
const C={};const wait=ms=>page.waitForTimeout(ms);
await page.clock.install({time:new Date(2026,9,9,8,30,0)}); /* vendredi 09/10/2026 8 h 30 : le planning ignore le week-end */
await page.goto(BASE+'/index.html');await wait(600);await page.evaluate(()=>{localStorage.clear();}); /* vendredi : le planning ignore le week-end */await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.reload();await wait(1200);
const skip=async()=>{const s=await page.$('#loginSkip');if(s&&await s.isVisible())await s.click();await wait(700);};await skip();
await page.evaluate(()=>{const T=window.TRACE;const src=T.sites[Object.keys(T.sites).find(k=>k!=='__vide'&&T.sites[k]&&T.sites[k].lines)];const now=new Date().toISOString();const x=JSON.parse(JSON.stringify(src));x.id='demo_caen';x.name='Caen — Presqu\'île';x.fiche={ville:'Caen',secteur:'ouest',chef:'l:ethan',horaires:'7 h 30 – 16 h 30',rassemblement:'base vie, rue de la Mer'};
  x.conv={msgs:[{id:'m1',kind:'msg',by:'Julie M.',text:'Photos du DH avant 15 h',at:now},{id:'t1',kind:'task',by:'Julie M.',text:'Reprendre S-0041',task:{to:'tous',done:false},at:now}],seq:3};x.qse={docs:[]};x.stock={zones:[],lots:[],livs:[{id:'LV1',label:'Camion',date:now.slice(0,10),status:'prevu'}],moves:[],takes:[]};
  const d=new Date();const iso=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');x.missions={[iso]:[{id:'m1',type:'soud',label:'Souder le tronçon 3',h:12,who:['l:karim'],by:'Ethan L.',at:now}]};T.sites.demo_caen=x;T.renderHome();});await wait(300);
// Ethan place Karim à Caen
await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';T.renderHome();document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,200));
  const c=[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>/Karim/.test(x.textContent));c.querySelector('.eq-plmain').click();document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] [data-act=plput]').click();});await wait(300);
// ── 1) Ethan : tableau de bord (accueil) → « Ouvrir le bureau du chantier » → onglet Bureau (premier onglet), checklist 16, ce qui coince, raccourcis ; une case ouvre son onglet ; les anciens onglets sont toujours là
let out=await page.evaluate(async()=>{const T=window.TRACE;document.getElementById('htHome').click();await new Promise(r=>setTimeout(r,200));document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Mes chantiers/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Caen/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,200));
  const b=document.querySelector('#eq-app [data-act=opensite][data-v="demo_caen|bureau"]');const r={btn:!!b};b.click();await new Promise(r2=>setTimeout(r2,1800));r.screen=T.state.screen;r.tab=T.state.tab;r.first=document.querySelector('#tabbar button').dataset.tab;r.tabs=[...document.querySelectorAll('#tabbar button')].map(x=>x.dataset.tab);
  const el=document.getElementById('bureau');r.h2=(el.querySelector('h2.vt')||{}).textContent;r.kv=(el.querySelector('.card .kv')||{}).textContent;r.today=[...el.querySelectorAll('.ac-notif .tx b')].map(x=>x.textContent);r.chk=el.querySelectorAll('.ac-kt.ac-dk .ac-chk').length;r.short=[...el.querySelectorAll('.ac-kt')].filter(x=>!x.querySelector('.ac-chk')).map(x=>x.dataset.bur);r.coince=(el.querySelector('.ac-h span')||{}).textContent;
  [...el.querySelectorAll('[data-bur="stock"]')][0].click();await new Promise(r2=>setTimeout(r2,300));r.after=T.state.tab;r.view=document.querySelector('.view.active')&&document.querySelector('.view.active').id;return r;});
console.log('1) bureau (Ethan) :',JSON.stringify(out));
C.c1=out.btn&&out.screen==='site'&&out.tab==='bureau'&&out.first==='bureau'&&['plan','bouclage','hydro','stock','phasage','ts','conv','qse','export'].every(t=>out.tabs.includes(t))&&/Bureau — Caen/.test(out.h2)&&/chef : Ethan/.test(out.kv)&&/7 h 30 – 16 h 30/.test(out.kv)&&/rue de la Mer/.test(out.kv)&&/aujourd'hui : Karim/.test(out.kv)&&out.today.some(t=>/Objectif du jour · 1 mission · 12 h/.test(t))&&out.today.some(t=>/1 tâche pour toi/.test(t))&&out.today.some(t=>/2 messages non lus/.test(t))&&out.chk===16&&out.short.includes('plan')&&out.short.includes('conv')&&out.after==='stock'&&out.view==='view-stock';
// ── 2) Karim (soudeur) : bureau sans checklist, avec « accueil chantier pas fait » (→ parcours), objectif du jour, raccourcis limités à ses onglets ; retour Plan d'ensemble par le raccourci
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='karim';T.state.tab='bureau';T.renderAll();await new Promise(r=>setTimeout(r,300));const el=document.getElementById('bureau');const r={chk:el.querySelectorAll('.ac-kt.ac-dk .ac-chk').length,today:[...el.querySelectorAll('.ac-notif .tx b')].map(x=>x.textContent),short:[...el.querySelectorAll('.ac-kt')].map(x=>x.dataset.bur),parcours:!!el.querySelector('[data-bur="__parcours"]')};
  el.querySelector('[data-bur="__parcours"]').click();await new Promise(r2=>setTimeout(r2,400));r.modal=/PPSPS/.test(document.getElementById('modal').textContent);const m=document.getElementById('modal');m.classList.remove('show');m.innerHTML='';
  el.querySelector('[data-bur="plan"]').click();await new Promise(r2=>setTimeout(r2,300));r.after=T.state.tab;return r;});
console.log('2) bureau (Karim) :',JSON.stringify(out));
C.c2=out.chk===0&&out.parcours&&out.today.some(t=>/accueil chantier n'est pas fait/.test(t))&&out.today.some(t=>/Objectif du jour/.test(t))&&out.short.includes('plan')&&out.short.includes('conv')&&!out.short.includes('stock')&&!out.short.includes('__orga')&&out.modal&&out.after==='plan';
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
