// HYDRAULIQUE — EXÉCUTION (Ethan 09/10, refonte 09/10 soir) : section 5 de l'onglet, fiche en sections (Infos / Relevé de début / Relevé de fin / Résultat / Photos & pièces),
// durée de maintien en HEURES liée à début/fin, chute et résultat calculés, T° début et fin, plus de PS ni de manomètre, photos caméra + galerie, pièces au Dossier (export mano, PV),
// rapport de réalisation + PV, ancien format relu sans perte, persistance
import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:1000,height:940}});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404/i.test(m.text()))logs.push(m.text().slice(0,200));});
page.on('dialog',d=>d.accept().catch(()=>{}));
const C={};
await page.goto(BASE+'/traceur.html');await page.waitForTimeout(500);await page.evaluate(()=>{localStorage.clear();});await page.reload();await page.waitForTimeout(500);
await page.evaluate(()=>{const S=window.MAQ.state;S.supplier='RENALIA';S.lines=[{id:'L1',name:'Rue de la Gare',dn:150,bar:12,pts:[[10,50],[130,50]],specials:[],parent:null}];S.seq=2;window.MAQ.setMode('select');window.MAQ.rebuild();});
await page.click('#bSave');await page.waitForTimeout(200);await page.fill('#svName','Hydro exé');await page.click('#svOk');await page.waitForTimeout(700);await page.click('#svGo');await page.waitForTimeout(1500);await page.selectOption('#roleSel','ethan');await page.waitForTimeout(300);
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';
const addFile=(sel,name,type,b64)=>page.evaluate(([sel,name,type,b64])=>{const dt=new DataTransfer();const b=atob(b64);const u8=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u8[i]=b.charCodeAt(i);dt.items.add(new File([u8],name,{type}));const inp=document.querySelector(sel);inp.files=dt.files;inp.dispatchEvent(new Event('change'));},[sel,name,type,b64]);
// ── 1) section 5 : une ligne par prestation cochée (épreuve seule par défaut), « à faire », bouton Renseigner ; coche rinçage → 2 lignes
let out=await page.evaluate(()=>{const T=window.TRACE;T.state.tab='hydro';T.renderAll();const el=document.getElementById('hydro');const r={sec:/5 · Exécution/.test(el.textContent),rows:el.querySelectorAll('.hxRow').length,afaire:[...el.querySelectorAll('.hxTag')].map(t=>t.textContent),btn:!!el.querySelector('[data-hxedit][data-hxkind=epreuve]'),report:!!el.querySelector('#hyExecReport'),pvBtn:!!el.querySelector('[data-hxpv]')};
  el.querySelector('.hyCard[data-p=rincage]').click();r.rows2=document.querySelectorAll('#hydro .hxRow').length;return r;});
console.log('1) section exécution :',JSON.stringify(out));C.c1=out.sec&&out.rows===1&&out.afaire[0]==='à faire'&&out.btn&&out.report&&!out.pvBtn&&out.rows2===2;
// ── 2) fiche d'épreuve T1 : 5 sections ; PE 20,8 proposée, PAS de pression de service ni de manomètre ; début 08:30 + fin 10:30 → durée 2 h calculée ; durée 1,5 → fin 10:00 ;
//       pressions 20,8 → 20,7, chute admise 0,2 → chute 0,1 CONFORME ; T° eau début et fin ; photo de début (appareil) + photo de fin (galerie) ; enregistré → ligne « conforme », résumé, miniatures, bouton PV
await page.evaluate(()=>document.querySelector('#hydro [data-hxedit="0"][data-hxkind=epreuve]').click());await page.waitForTimeout(300);
out=await page.evaluate(()=>{const m=document.getElementById('modal');const v=k=>{const i=m.querySelector('[data-hx="'+k+'"]');return i?i.value:null;};return {open:m.classList.contains('show'),title:(m.querySelector('h3')||{}).textContent,secs:[...m.querySelectorAll('.hxSecH')].map(x=>x.textContent),pe:v('pe'),ps:v('ps'),mano:v('mano'),date:v('date'),chef:v('chef'),tEauD:v('debut.tEau')!==null,tEauF:v('fin.tEau')!==null,tAmbF:v('fin.tAmb')!==null,dur:v('dureeH'),cam:m.querySelectorAll('[data-hxph][capture]').length,gal:m.querySelectorAll('[data-hxph]:not([capture])').length,mano2:!!m.querySelector('#hxMano'),calc:(m.querySelector('#hxCalc')||{}).textContent};});
const set=(k,v)=>page.evaluate(([k,v])=>{const i=document.querySelector('#modal [data-hx="'+k+'"]');i.value=v;i.dispatchEvent(new Event('input'));},[k,v]);
const get=k=>page.evaluate(k=>document.querySelector('#modal [data-hx="'+k+'"]').value,k);
await set('debut.h','08:30');await set('fin.h','10:30');out.dur1=await get('dureeH');out.durHint=await page.evaluate(()=>document.getElementById('hxDurHint').textContent);
await set('dureeH','1,5');out.fin2=await get('fin.h');
await set('debut.p','20,8');await set('fin.p','20.7');await set('equipe','Karim B., Sofiane K.');await set('temoin','M. Durand (MOE)');await set('debut.tEau','12');await set('fin.tEau','13');await set('fin.tAmb','18');await set('obs','RAS');
out.calc2=await page.evaluate(()=>document.querySelector('#hxCalc').textContent);
await addFile('#modal [data-hxph="debut"][capture]','mano_debut.png','image/png',PNG.split(',')[1]);await page.waitForTimeout(600);
await addFile('#modal [data-hxph="fin"]:not([capture])','mano_fin.png','image/png',PNG.split(',')[1]);await page.waitForTimeout(600);
out.thumbs=await page.evaluate(()=>({d:document.querySelectorAll('#modal [data-hxth=debut] .thumb').length,f:document.querySelectorAll('#modal [data-hxth=fin] .thumb').length,a:document.querySelectorAll('#modal [data-hxth=all] .thumb').length}));
await page.evaluate(()=>document.querySelector('#hxOk').click());await page.waitForTimeout(400);
out.after=await page.evaluate(()=>{const T=window.TRACE;const r=T.hydroExec.of(0,'epreuve');const el=document.getElementById('hydro');const row=[...el.querySelectorAll('.hxRow')][0];return {saved:!!r,p0:r&&r.debut.p,p1:r&&r.fin.p,h0:r&&r.debut.h,h1:r&&r.fin.h,dur:r&&r.dureeH,durCalc:T.hydroExec.duree(r),tEauF:r&&r.fin.tEau,phD:r&&r.debut.photos.length,phF:r&&r.fin.photos.length,ps:r&&r.ps,pe:T.net.hydro.pe,tag:row.querySelector('.hxTag').textContent,sum:row.textContent,res:T.hydroExec.result('epreuve',r).code,thumb:row.querySelectorAll('.thumb').length,pvBtn:!!row.querySelector('[data-hxpv]'),modal:document.getElementById('modal').classList.contains('show')};});
console.log('2) épreuve conforme :',JSON.stringify(out));
C.c2=out.open&&/Épreuve hydraulique — Tronçon 1/.test(out.title)&&out.secs.length===5&&/Infos/.test(out.secs[0])&&/début/.test(out.secs[1])&&/fin/.test(out.secs[2])&&/Résultat/.test(out.secs[3])&&/pièces/.test(out.secs[4])
  &&out.pe==='20,8'&&out.ps===null&&out.mano===null&&/^\d{4}-\d{2}-\d{2}$/.test(out.date)&&out.chef==='Ethan L.'&&out.tEauD&&out.tEauF&&out.tAmbF&&out.dur===''&&out.cam===3&&out.gal===3&&out.mano2&&/Renseigne les pressions/.test(out.calc)
  &&out.dur1==='2'&&/2 h \(08:30 → 10:30\)/.test(out.durHint)&&out.fin2==='10:00'&&/0,1 bar/.test(out.calc2)&&/maintien 1 h 30/.test(out.calc2)&&/CONFORME/.test(out.calc2)&&!/NON CONFORME/.test(out.calc2)
  &&out.thumbs.d===1&&out.thumbs.f===1&&out.thumbs.a===0&&out.after.saved&&out.after.p0==='20,8'&&out.after.p1==='20.7'&&out.after.h0==='08:30'&&out.after.h1==='10:00'&&out.after.dur==='1,5'&&out.after.durCalc===1.5&&out.after.tEauF==='13'&&out.after.phD===1&&out.after.phF===1&&out.after.ps===undefined&&out.after.pe===20.8
  &&out.after.tag==='conforme'&&/chute 0,1 bar \/ 0,2 admis · maintien 1 h 30/.test(out.after.sum)&&/2 photos/.test(out.after.sum)&&out.after.res==='ok'&&out.after.thumb===2&&out.after.pvBtn&&!out.after.modal;
// ── 3) règles : chute 0,5 > 0,2 → non conforme ; pression d'épreuve non atteinte ; maintien 1 h < 2 h exigé → non conforme ; vide → null ; ancien format (pDebut/pFin/duree en min) relu
out=await page.evaluate(()=>{const T=window.TRACE;const E=T.hydroExec.epreuve;const e1=E({debut:{p:'20.8'},fin:{p:'20.3'},chuteAdm:'0.2',pe:'20.8'});const e2=E({debut:{p:'18'},fin:{p:'18'},chuteAdm:'0.2',pe:'20.8'});const e3=E({debut:{p:''},fin:{p:''},chuteAdm:'0.2'});
  const e4=E({debut:{h:'08:00',p:'20.8'},fin:{h:'09:00',p:'20.8'},chuteAdm:'0.2',pe:'20.8',dureeReq:'2'});const e5=E({debut:{h:'23:00',p:'20.8'},fin:{h:'01:00',p:'20.75'},chuteAdm:'0.2',pe:'20.8',dureeReq:'2'});
  const old=T.hydroExec.norm({date:'2026-10-08',debut:'08:30',fin:'09:45',ps:'16',pe:'20,8',pDebut:'20,8',pFin:'20,7',duree:'60',chuteAdm:'0,2',tEau:'12',mano:'MN-07',photos:['x']},'epreuve');const eo=E(old);
  return {c1:e1.chute,ok1:e1.ok,c2:e2.chute,ok2:e2.ok,ok3:e3.ok,ok4:e4.ok,why4:e4.why.join(';'),dur5:e5.dur,ok5:e5.ok,lab:T.hydroExec.result('epreuve',{debut:{p:'20.8'},fin:{p:'20.3'},chuteAdm:'0.2',pe:'20.8'}).label,old:{h0:old.debut.h,p0:old.debut.p,p1:old.fin.p,tEau:old.debut.tEau,dur:old.dureeH,ok:eo.ok,chute:eo.chute,sum:T.hydroExec.result('epreuve',old).label}};});
console.log('3) règles :',JSON.stringify(out));
C.c3=out.c1===0.5&&out.ok1===false&&out.c2===0&&out.ok2===false&&out.ok3===null&&out.ok4===false&&/maintien trop court \(1 h < 2 h\)/.test(out.why4)&&out.dur5===2&&out.ok5===true&&out.lab==='non conforme'
  &&out.old.h0==='08:30'&&out.old.p0==='20,8'&&out.old.p1==='20,7'&&out.old.tEau==='12'&&out.old.dur==='1'&&out.old.ok===true&&out.old.chute===0.1&&out.old.sum==='conforme';
// ── 4) rinçage T1 : débit visé proposé d'après la prépa (Infos) ; relevé début débit 42, fin eau claire, volume 4,2, résultat conforme → « conforme »
await page.evaluate(()=>document.querySelector('#hydro [data-hxedit="0"][data-hxkind=rincage]').click());await page.waitForTimeout(300);
out=await page.evaluate(()=>{const m=document.getElementById('modal');const v=k=>{const i=m.querySelector('[data-hx="'+k+'"]');return i?i.value:null;};const r={debitCible:v('debitCible'),debitD:v('debut.debit')!==null,volF:v('fin.volume')!==null,volD:v('debut.volume'),clarteF:v('fin.clarte')!==null};
  const set=(k,val)=>{const i=m.querySelector('[data-hx="'+k+'"]');i.value=val;i.dispatchEvent(new Event('input'));};set('debut.debit','42');set('fin.clarte','claire');set('fin.volume','4,2');set('debut.h','14:00');set('fin.h','14:20');r.dur=v('dureeH');m.querySelector('[data-hxres=ok]').click();m.querySelector('#hxOk').click();return r;});
await page.waitForTimeout(400);
out.after=await page.evaluate(()=>{const T=window.TRACE;const r=T.hydroExec.of(0,'rincage');const row=[...document.querySelectorAll('#hydro .hxRow')][1];return {clarte:r.fin.clarte,result:r.result,tag:row.querySelector('.hxTag').textContent,sum:row.textContent};});
console.log('4) rinçage :',JSON.stringify(out));C.c4=+out.debitCible>0&&out.debitD&&out.volF&&out.volD===null&&out.clarteF&&out.dur==='0,33'&&out.after.clarte==='claire'&&out.after.result==='ok'&&out.after.tag==='conforme'&&/eau claire/.test(out.after.sum)&&/42 m³\/h/.test(out.after.sum)&&/4,2 m³/.test(out.after.sum)&&/20 min/.test(out.after.sum);
// ── 5) pièces : export du manomètre déposé depuis la fiche → Dossier administratif › Épreuves & essais, rattaché à T1/épreuve ; « PV → dossier » → PDF du PV classé (pdf.js) ; la section 5 et le Dossier les listent
await page.evaluate(()=>document.querySelector('#hydro [data-hxedit="0"][data-hxkind=epreuve]').click());await page.waitForTimeout(300);
out=await page.evaluate(()=>({docs0:document.getElementById('hxDocs').textContent}));
await addFile('#hxMano','courbe_mano_T1.pdf','application/pdf',btoa('%PDF-1.4 test'));await page.waitForTimeout(700);
out.docs1=await page.evaluate(()=>document.getElementById('hxDocs').textContent);
await page.evaluate(()=>document.querySelector('#modal [data-close]').click());await page.waitForTimeout(200);
await page.evaluate(()=>window.TRACE.hydroExec.filePV(0,'epreuve'));await page.waitForTimeout(900);
out.after=await page.evaluate(()=>{const T=window.TRACE;const docs=T.net.admin.docs;const mine=T.hydroExec.docs(0,'epreuve');const row=[...document.querySelectorAll('#hydro .hxRow')][0];
  T.state.tab='admin';T.renderAll();const ad=document.getElementById('admin');const det=[...ad.querySelectorAll('details')].find(d=>/Épreuves & essais/.test(d.textContent));
  return {n:docs.length,mine:mine.length,cats:docs.map(d=>d.cat),names:mine.map(d=>d.name),pv:mine.filter(d=>d.pv).length,hydro:mine.every(d=>d.hydro&&d.hydro.t===0&&d.hydro.kind==='epreuve'),notes:mine.map(d=>d.note),rowLinks:row.querySelectorAll('a').length,admin:!!det,adminOpen:det&&det.open,adminRows:det?det.querySelectorAll('tr').length:0,adminTxt:det?det.textContent:'',pvData:(mine.find(d=>d.pv)||{}).data||''};});
// le PV est un vrai PDF (le stockage sert un .html en texte brut) : en-tête %PDF, 1 page, textes WinAnsi (É = 0xC9, — = 0x97), 3 images JPEG (logo SCR + 2 photos), fin %%EOF ; copie sur disque pour contrôle externe
const pvBin=out.after.pvData?atob(out.after.pvData.split(',')[1]):'';out.pdf={mime:out.after.pvData.slice(0,28),head:pvBin.slice(0,8),eof:/%%EOF\s*$/.test(pvBin),pages:(pvBin.match(/\/Type \/Page\b/g)||[]).length,imgs:(pvBin.match(/\/DCTDecode/g)||[]).length,titre:pvBin.includes("PV D'\u00C9PREUVE HYDRAULIQUE \u0097 CONFORME"),mano:pvBin.includes('courbe_mano_T1.pdf')&&pvBin.includes('Courbe du manom\u00E8tre'),dur:pvBin.includes('Dur\u00E9e de maintien')&&pvBin.includes('1 h 30'),noPS:!pvBin.includes('Pression de service'),xref:pvBin.includes('xref')&&pvBin.includes('startxref'),size:pvBin.length};
try{const fs=await import('node:fs');fs.writeFileSync('/tmp/sweep/pv_test.pdf',Buffer.from(pvBin,'latin1'));}catch(e){}
console.log('5) pièces au dossier :',JSON.stringify({...out,after:{...out.after,pvData:out.after.pvData.slice(0,40)}}));
C.c5=/aucune pièce/.test(out.docs0)&&/courbe_mano_T1\.pdf/.test(out.docs1)&&out.after.n===2&&out.after.mine===2&&out.after.cats.every(c=>c==='epreuves')&&out.after.pv===1&&out.after.hydro&&/Export manomètre — Épreuve hydraulique — tronçon 1/.test(out.after.notes[0])&&/PV — Épreuve hydraulique — tronçon 1 — conforme/.test(out.after.notes[1])
  &&/^PV_Epreuve_T1_\d{4}-\d{2}-\d{2}_conforme\.pdf$/.test(out.after.names[1])&&out.after.rowLinks===2&&out.after.admin&&out.after.adminOpen&&out.after.adminRows===2&&/Export manomètre/.test(out.after.adminTxt)
  &&out.pdf.mime==='data:application/pdf;base64,'&&out.pdf.head==='%PDF-1.4'&&out.pdf.eof&&out.pdf.pages===1&&out.pdf.imgs===3&&out.pdf.titre&&out.pdf.mano&&out.pdf.dur&&out.pdf.noPS&&out.pdf.xref&&out.pdf.size>2000;
// ── 6) rapport de réalisation (charte SCR : logo, en-tête, chiffres clés) : page de garde (tableau) + un PV par prestation renseignée ; relevés Début | Fin, durée, chute, courbe mentionnée, photos légendées, signatures ; fenêtre
await page.evaluate(()=>{window.TRACE.state.tab='hydro';window.TRACE.renderAll();});
const popup=page.waitForEvent('popup');await page.evaluate(()=>document.querySelector('#hyExecReport').click());const pop=await popup;await pop.waitForLoadState('domcontentloaded');await page.waitForTimeout(500);
out=await pop.evaluate(()=>({title:document.title,h1:(document.querySelector('h1')||{}).textContent,logo:!!document.querySelector('.scrHead img.logo'),sub:(document.querySelector('.scrHead .sub')||{}).textContent||'',kpi:document.querySelectorAll('.kpi div').length,pages:document.querySelectorAll('.page').length,pv:document.body.textContent.match(/PV D'ÉPREUVE HYDRAULIQUE — CONFORME/g)?.length||0,rin:/Rinçage dynamique — Tronçon 1/.test(document.body.textContent),chute:/Chute de pression mesurée/.test(document.body.textContent),rel:document.querySelectorAll('table.rel').length,relHead:/Début/.test([...document.querySelectorAll('table.rel th')].map(x=>x.textContent).join('|')),tEau:/T° eau/.test(document.body.textContent)&&/12/.test(document.body.textContent)&&/13/.test(document.body.textContent),dur:/Durée de maintien/.test(document.body.textContent)&&/1 h 30/.test(document.body.textContent),mano:/courbe extraite de l'enregistreur du manomètre est jointe au dossier/i.test(document.body.textContent),noPS:!/Pression de service/.test(document.body.textContent),imgs:document.querySelectorAll('.ph img').length,caps:[...document.querySelectorAll('.ph figcaption')].map(x=>x.textContent),sig:document.querySelectorAll('table.sig').length,temoin:/M\. Durand/.test(document.body.textContent),print:!!document.querySelector('.np'),pieces:/1pièce au dossier/.test(document.body.textContent)}));
await pop.close();
console.log('6) rapport + PV :',JSON.stringify(out));C.c6=/Rapport de réalisation/.test(out.title)&&/Rapport de réalisation hydraulique/.test(out.h1)&&out.logo&&/Hydro exé/.test(out.sub)&&out.kpi===5&&out.pages===2&&out.pv===1&&out.rin&&out.chute&&out.rel===2&&out.relHead&&out.tEau&&out.dur&&out.mano&&out.noPS&&out.imgs===2&&out.caps.join('|')==='Début — 08:30|Fin — 10:00'&&out.sig===2&&out.temoin&&out.print&&out.pieces;
// ── 7) persistance (parties hydro + admin) après rechargement ; « Effacer » la prépa garde les fiches
const siteId=await page.evaluate(()=>window.TRACE.state.siteId);await page.reload();await page.waitForTimeout(1500);
for(let i=0;i<6;i++){await page.evaluate(id=>window.TRACE.go(id),siteId);try{await page.waitForFunction(()=>window.TRACE.state.siteId&&window.TRACE.state.screen==='site'&&Object.keys(window.TRACE.lines).length>0,null,{timeout:4000});break;}catch(e){}}
try{await page.selectOption('#roleSel','ethan');await page.waitForTimeout(300);}catch(e){}
out=await page.evaluate(()=>{const T=window.TRACE;const r=T.hydroExec.of(0,'epreuve');const before={saved:!!r,p0:r&&r.debut.p,phD:r&&r.debut.photos.length,phF:r&&r.fin.photos.length,rin:!!T.hydroExec.of(0,'rincage'),docs:T.hydroExec.docs(0,'epreuve').length};
  T.state.tab='hydro';T.renderAll();document.getElementById('hyClear').click();const r2=T.hydroExec.of(0,'epreuve');return {...before,afterClear:!!r2&&r2.debut.p==='20,8',rows:document.querySelectorAll('#hydro .hxRow').length};});
console.log('7) rechargement + effacer prépa :',JSON.stringify(out));C.c7=out.saved&&out.p0==='20,8'&&out.phD===1&&out.phF===1&&out.rin&&out.docs===2&&out.afterClear&&out.rows===1;
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
