// FLOTTE (parc véhicules) + RH (grands déplacements, ancienneté) — nuit 09→10/10. Hors connexion, registre sur l'appareil, géocodage Open-Meteo simulé.
import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:430,height:900}});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404|WebSocket/i.test(m.text()))logs.push(m.text().slice(0,200));});
let promptAnswer='GT-648-SE';page.on('dialog',d=>d.accept(promptAnswer).catch(()=>{}));
await page.route(u=>/open-meteo\.com$/.test(u.hostname),route=>{const url=route.request().url();const json=o=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(o)});
  if(url.includes('geocoding-api')){const n=decodeURIComponent(url.split('name=')[1].split('&')[0]).toLowerCase();const C={'caen':[49.18,-0.37],'rennes':[48.11,-1.68],'saint gilles':[48.15,-1.83]};const k=Object.keys(C).find(x=>n.includes(x));return json({results:k?[{name:k,latitude:C[k][0],longitude:C[k][1]}]:[]});}
  return json({daily:{time:[],weathercode:[],temperature_2m_max:[],precipitation_sum:[],precipitation_probability_max:[]}});});
const C={};const wait=ms=>page.waitForTimeout(ms);
await page.goto(BASE+'/index.html');await wait(600);await page.evaluate(()=>{localStorage.clear();});await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.reload();await wait(1200);
const skip=async()=>{const s=await page.$('#loginSkip');if(s&&await s.isVisible())await s.click();await wait(700);};await skip();
await page.evaluate(()=>{const T=window.TRACE;const src=T.sites[Object.keys(T.sites).find(k=>k!=='__vide'&&T.sites[k]&&T.sites[k].lines)];const x=JSON.parse(JSON.stringify(src));x.id='demo_caen';x.name='Caen — Presqu\'île';x.fiche={ville:'Caen',secteur:'ouest',chef:'l:ethan'};x.conv={msgs:[],seq:1};x.qse={docs:[]};delete x.geo;T.sites.demo_caen=x;
  const P=T.espace.state().people;P['l:karim']=Object.assign({},P['l:karim']||{},{adresse:{voie:'9 rue Louis Braille',cp:'35590',ville:'Saint Gilles'},entree:'2016-10-20',emploi:'Soudeur'});T.renderHome();});await wait(300);
const chg=async(sel,val)=>page.evaluate(([s,v])=>{const el=document.querySelector(s);el.value=v;el.dispatchEvent(new Event('change',{bubbles:true}));},[sel,val]);
const iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
// ── 1) Ethan : Flotte → parc vide → ➕ véhicule (immat par invite) → fiche → CT dans 10 jours → alerte ; stats de la liste
let out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';T.renderHome();document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));const row=[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Flotte · parc/.test(x.textContent));row.click();await new Promise(r=>setTimeout(r,200));
  const r={title:(document.querySelector('#eq-app h2.vt')||{}).textContent,empty:/Aucun véhicule/.test(document.getElementById('eq-app').textContent)};document.querySelector('#eq-app [data-act=fl][data-v="new|"]').click();await new Promise(r2=>setTimeout(r2,250));r.fiche=(document.querySelector('#eq-app .af-head h2')||{}).textContent;r.fields=document.querySelectorAll('#eq-app [data-flf]').length;return r;});
const ct=new Date();ct.setDate(ct.getDate()+10);
await chg('#eq-app [data-flf=marque]','MERCEDES');await wait(80);await chg('#eq-app [data-flf=modele]','VITO');await wait(80);await chg('#eq-app [data-flf=type]','Soudeur');await wait(80);await chg('#eq-app [data-flf=ctProchain]',iso(ct));await wait(80);await chg('#eq-app [data-flf=km]','120500');await wait(80);await chg('#eq-app [data-flf=cadenceVidange]','30000');await wait(80);await chg('#eq-app [data-flf=kmVidange]','85000');await wait(200);
out.after=await page.evaluate(()=>{const T=window.TRACE;const v=T.flotte.get('GT-648-SE');return {marque:v.marque,ct:v.ctProchain,km:v.km,alertes:T.flotte.alertes(v).map(a=>a.t),txt:document.querySelector('#eq-app .af-head').textContent.replace(/\s+/g,' ')};});
console.log('1) flotte : création + alertes :',JSON.stringify(out));
C.c1=/Parc véhicules/.test(out.title)&&out.empty&&/GT-648-SE/.test(out.fiche)&&out.fields>25&&out.after.marque==='MERCEDES'&&out.after.km===120500&&out.after.alertes.some(t=>/Contrôle technique dans (9|10) j/.test(t))&&out.after.alertes.some(t=>/Vidange à faire/.test(t))&&/Contrôle technique dans (9|10) j/.test(out.after.txt);
// ── 2) contrôle visuel + conducteur = Karim (annuaire) ; liste : 1 véhicule, 1 alerte bloquante ; Karim : « Mon véhicule » dans Mon espace + à savoir ; signalement
await page.evaluate(()=>document.querySelector('#eq-app [data-act=fl][data-v="ctrl|"]').click());await wait(250);
out=await page.evaluate(()=>{const click=(k,e)=>document.querySelector(`#modal [data-flc="${k}"][data-e="${e}"]`).click();click('proprete','OK');click('pneus','À revoir');click('extincteur','HS');document.getElementById('flc-accrocs').value='Rayure porte latérale';document.getElementById('flc-km').value='120600';const n=document.querySelectorAll('#modal .ct-item').length;document.getElementById('flc-ok').click();return {items:n};});await wait(300);
await chg('#eq-app [data-flf=conducteurKey]','l:karim');await wait(250);
out.after=await page.evaluate(async()=>{const T=window.TRACE;const v=T.flotte.get('GT-648-SE');const r={ctrl:v.controles&&v.controles.length,km:v.km,extinct:v.controles&&v.controles[0].items.extincteur,cond:v.conducteur,condKey:v.conducteurKey};document.querySelector('#eq-app [data-act=fl][data-v="back|"]').click();await new Promise(x=>setTimeout(x,200));r.list=document.querySelectorAll('#eq-app .fl-row').length;r.stats=[...document.querySelectorAll('#eq-app .ac-stat')].map(x=>x.textContent.replace(/\s+/g,' ').trim());
  T.state.userId='karim';document.getElementById('htHome').click();await new Promise(x=>setTimeout(x,300));r.kt=[...document.querySelectorAll('#eq-app .ac-kt .tx')].map(x=>x.textContent.replace(/\s+/g,' ').trim());document.getElementById('htEspace').click();await new Promise(x=>setTimeout(x,250));r.card=[...document.querySelectorAll('#eq-app .card h3')].map(h=>h.textContent).find(t=>/Mon véhicule/.test(t));r.sigBtn=!!document.querySelector('#eq-app [data-act=fl][data-v="signal|GT-648-SE"]');return r;});
promptAnswer='Pneu avant gauche usé';await page.evaluate(()=>document.querySelector('#eq-app [data-act=fl][data-v="signal|GT-648-SE"]').click());await wait(300);
out.sig=await page.evaluate(()=>{const v=window.TRACE.flotte.get('GT-648-SE');return {n:(v.signalements||[]).length,txt:v.signalements&&v.signalements[0].text,by:v.signalements&&v.signalements[0].by};});
console.log('2) contrôle + conducteur + mon véhicule + signalement :',JSON.stringify(out));
C.c2=out.items===10&&out.after.ctrl===1&&out.after.km===120600&&out.after.extinct==='HS'&&/Karim/.test(out.after.cond)&&out.after.condKey==='l:karim'&&out.after.list===1&&out.after.stats.some(t=>/^1\s*véhicules/.test(t))&&out.after.kt.some(t=>/Mon véhicule GT-648-SE/.test(t))&&/Mon véhicule/.test(out.after.card||'')&&out.after.sigBtn&&out.sig.n===1&&/Pneu avant gauche/.test(out.sig.txt)&&/Karim/.test(out.sig.by);
// ── 3) grands déplacements : Ethan place Karim à Caen (domicile Saint-Gilles ≈ 150 km → ×1,25 ≈ 187 km → cas 2) ; Mon espace « Mon déplacement » ; Exploitation → Grands déplacements
await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';T.renderHome();document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,200));
  const c=[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>/Karim/.test(x.textContent));c.querySelector('.eq-plmain').click();document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] [data-act=plput]').click();});await wait(300);
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='karim';document.getElementById('htEspace').click();await new Promise(r=>setTimeout(r,1500));const card=[...document.querySelectorAll('#eq-app .card')].find(c=>/Mon déplacement/.test(c.textContent));return {card:card&&card.textContent.replace(/\s+/g,' ').trim()};});
console.log('3a) mon déplacement :',JSON.stringify(out));
C.c3a=/Caen/.test(out.card||'')&&/km de chez toi/.test(out.card||'')&&/Cas 2 · Grand déplacement/.test(out.card||'')&&/5\s*nuitées/.test(out.card||'')&&/10\s*repas/.test(out.card||'')&&/15 €/.test(out.card||'')&&/5 jours planifiés/.test(out.card||''); /* plput place toute la semaine */
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Grands déplacements/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,600));const t=document.getElementById('eq-app').textContent.replace(/\s+/g,' ');return {stats:[...document.querySelectorAll('#eq-app .ac-stat')].map(x=>x.textContent.replace(/\s+/g,' ').trim()),karim:/Karim B\..*cas 2/.test(t),regles:/Cas 4 · Très grand déplacement/.test(t)};});
console.log('3b) exploitation GD :',JSON.stringify(out));
C.c3b=out.stats.some(t=>/^1\s*planifiés/.test(t))&&out.stats.some(t=>/^1\s*en grand/.test(t))&&out.stats.some(t=>/^5\s*nuitées/.test(t))&&out.karim&&out.regles;
// ── 4) ancienneté : Entreprise (Ethan) → « Ancienneté & médailles » : Karim 10 ans le 20/10/2026 dans les paliers des 6 mois
out=await page.evaluate(async()=>{document.getElementById('htEnt').click();await new Promise(r=>setTimeout(r,300));const c=[...document.querySelectorAll('#eq-app .card')].find(x=>/Ancienneté & médailles/.test(x.textContent));return {card:c&&c.textContent.replace(/\s+/g,' ').trim().slice(0,300)};});
console.log('4) ancienneté :',JSON.stringify(out));
C.c4=/Karim B\. — 10 ans le 20\/10\/2026/.test(out.card||'')&&/entré le 20\/10\/2016/.test(out.card||'');
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
