// 3e vague de la nuit 09→10/10 : rapport heures & production (⑦) + exports CSV, bons de commande & débours, production des équipes dans Exploitation,
// fiche chantier (horaires, point de rassemblement), notification des non-conformités du contrôle chantier, récap CA commerce + numéro d'affaire proposé.
import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:430,height:900},acceptDownloads:true});const page=await ctx.newPage();
const logs=[];page.on('pageerror',e=>logs.push('PAGEERROR: '+e.message.slice(0,300)));page.on('console',m=>{if(m.type()==='error'&&!/supabase|Failed to fetch|net::ERR|404|WebSocket/i.test(m.text()))logs.push(m.text().slice(0,200));});
page.on('dialog',d=>d.accept().catch(()=>{}));const downloads=[];page.on('download',d=>downloads.push(d.suggestedFilename()));
const C={};const wait=ms=>page.waitForTimeout(ms);
await page.clock.install({time:new Date(2026,9,9,8,30,0)}); /* vendredi 09/10/2026 8 h 30 : le planning ignore le week-end, la date ne doit pas dépendre du jour du test */
await page.goto(BASE+'/index.html');await wait(600);await page.evaluate(()=>{localStorage.clear();});await page.evaluate(()=>new Promise(r=>{try{const q=indexedDB.deleteDatabase('trace-kv');q.onsuccess=q.onerror=q.onblocked=()=>r();}catch(e){r();}}));
await page.reload();await wait(1200);
const skip=async()=>{const s=await page.$('#loginSkip');if(s&&await s.isVisible())await s.click();await wait(700);};await skip();
await page.evaluate(()=>{const T=window.TRACE;const src=T.sites[Object.keys(T.sites).find(k=>k!=='__vide'&&T.sites[k]&&T.sites[k].lines)];const x=JSON.parse(JSON.stringify(src));x.id='demo_caen';x.name='Caen — Presqu\'île';x.fiche={ville:'Caen',secteur:'ouest',chef:'l:ethan'};x.conv={msgs:[],seq:1};x.qse={docs:[],controles:[{id:'c1',at:new Date().toISOString(),by:'Ethan L.',lieu:'Base vie',items:{ch_place:{e:'NC',lab:'Espace de travail',action:'Déplacer la benne'},eq_trousse:{e:'NC',lab:'Trousse de secours',action:''},bv_rang:{e:'C',lab:'Rangement'}}}]};T.sites.demo_caen=x;T.renderHome();});await wait(300);
const chg=async(sel,val)=>page.evaluate(([s,v])=>{const el=document.querySelector(s);el.value=v;el.dispatchEvent(new Event('change',{bubbles:true}));},[sel,val]);
// ── 1) Ethan : menu Exploitation (lignes actives) + notification NC du contrôle chantier ; fiche chantier : horaires + rassemblement
let out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';T.renderHome();const r={notifs:[...document.querySelectorAll('#eq-app .ac-notif .tx b')].map(b=>b.textContent)};document.getElementById('htExpl').click();await new Promise(x=>setTimeout(x,200));
  r.rows=[...document.querySelectorAll('#eq-app .ac-row')].map(x=>({t:(x.querySelector('.tx > b')||{}).textContent,soon:x.classList.contains('soon')}));
  [...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Planning des équipes/.test(x.textContent)).click();await new Promise(x=>setTimeout(x,200));const det=document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] details');det.open=true;r.inputs=!!document.querySelector('#eq-app [data-chg=plfiche][data-site=demo_caen][data-k=horaires]');
  const c=[...document.querySelectorAll('#eq-app .eq-pltray .eq-plchip')].find(x=>/Karim/.test(x.textContent));c.querySelector('.eq-plmain').click();document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] [data-act=plput]').click();await new Promise(x=>setTimeout(x,200));return r;});
await page.evaluate(()=>{const det=document.querySelector('#eq-app .eq-plsite[data-drop=demo_caen] details');if(det)det.open=true;});
await chg('#eq-app [data-chg=plfiche][data-site=demo_caen][data-k=horaires]','7 h 30 – 16 h 30');await wait(300);
out.fiche=await page.evaluate(()=>window.TRACE.sites.demo_caen.fiche.horaires);
console.log('1) menu + NC + fiche chantier :',JSON.stringify(out));
const rowOf=t=>out.rows.find(r=>new RegExp(t).test(r.t||''));
C.c1=out.notifs.some(t=>/2 non-conformités au contrôle chantier/.test(t))&&rowOf('Heures & production')&&!rowOf('Heures & production').soon&&rowOf('Bons de commande')&&!rowOf('Bons de commande').soon&&rowOf('Production des équipes')&&!rowOf('Production des équipes').soon&&out.inputs&&out.fiche==='7 h 30 – 16 h 30';
// ── 2) Karim pointe (début → fin) ; Ethan valide ; rapport Heures & production : ligne Karim, heures « chef » ; exports CSV (variables de paie + rapport)
await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='karim';document.getElementById('htHome').click();await new Promise(r=>setTimeout(r,300));const q=s=>document.querySelector('#eq-app '+s);q('[data-act=pointer][data-v=start]').click();await new Promise(r=>setTimeout(r,120));q('[data-act=pointer][data-v=end]').click();await new Promise(r=>setTimeout(r,120));
  T.state.userId='ethan';document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Pointages à valider/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,250));document.querySelector('#eq-app [data-act=valider]').click();await new Promise(r=>setTimeout(r,200));});
out=await page.evaluate(async()=>{document.querySelector('#eq-app .ac-back').click();await new Promise(r=>setTimeout(r,150));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Heures & production/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,300));const t=document.getElementById('eq-app').textContent.replace(/\s+/g,' ');
  return {stats:[...document.querySelectorAll('#eq-app .ac-stat')].map(x=>x.textContent.replace(/\s+/g,' ').trim()),karim:/Karim B\./.test(t),rows:document.querySelectorAll('#eq-app table.af-tab tr').length,btns:document.querySelectorAll('#eq-app [data-act=rpcsv]').length};});
await page.evaluate(()=>document.querySelector('#eq-app [data-act=rpcsv][data-v=paie]').click());await wait(700);await page.evaluate(()=>document.querySelector('#eq-app [data-act=rpcsv][data-v=semaine]').click());await wait(700);
out.downloads=downloads.slice();
console.log('2) rapport heures & production :',JSON.stringify(out));
C.c2=out.karim&&out.rows>=2&&out.btns===2&&out.stats.some(t=>/heures pointées/.test(t))&&out.stats.some(t=>/validées chef/.test(t))&&out.downloads.some(f=>/^variables_paie_S\d+\.csv$/.test(f))&&out.downloads.some(f=>/^rapport_S\d+\.csv$/.test(f));
// ── 3) bons de commande : nouveau BC (numéro BC-AAMM-01), fournisseur, ligne 20 × 38,50 → total 770 ; liste avec état brouillon → envoyée
out=await page.evaluate(async()=>{document.querySelector('#eq-app .ac-back').click();await new Promise(r=>setTimeout(r,150));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Bons de commande/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,250));const r={empty:/Aucun bon de commande/.test(document.getElementById('eq-app').textContent)};document.querySelector('#eq-app [data-act=cmd][data-v="new|"]').click();await new Promise(x=>setTimeout(x,250));r.num=(document.querySelector('#eq-app .af-num')||{}).textContent;return r;});
await chg('#eq-app [data-cmdf=fournisseur]','Isoplus France');await wait(150);await chg('#eq-app [data-cmdl="0|designation"]','Tube DN150 pré-isolé 12 m');await wait(80);await chg('#eq-app [data-cmdl="0|qte"]','20');await wait(120);await chg('#eq-app [data-cmdl="0|pu"]','38.5');await wait(200);
out.after=await page.evaluate(async()=>{const T=window.TRACE;const c=T.commandes.all()[0];const r={num:c.num,fourn:c.fournisseur,total:c.lignes.reduce((s,l)=>s+l.qte*l.pu,0),txt:/770,00/.test(document.getElementById('eq-app').textContent)};const sel=document.querySelector('#eq-app [data-cmdf=etat]');sel.value='envoyee';sel.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(x=>setTimeout(x,200));document.querySelector('#eq-app [data-act=cmd][data-v="back|"]').click();await new Promise(x=>setTimeout(x,200));r.list=[...document.querySelectorAll('#eq-app .ac-row .tx')].map(x=>x.textContent.replace(/\s+/g,' ').trim());return r;});
console.log('3) bons de commande :',JSON.stringify(out));
const ym=new Date();const bcPre='BC-'+String(ym.getFullYear()).slice(2)+String(ym.getMonth()+1).padStart(2,'0')+'-01';
C.c3=out.empty&&out.num.startsWith(bcPre)&&out.after.num===bcPre&&out.after.fourn==='Isoplus France'&&out.after.total===770&&out.after.txt&&out.after.list.some(t=>new RegExp(bcPre+' · Isoplus France').test(t)&&/Envoyée/.test(t)&&/770,00 €/.test(t));
// ── 4) débours : Karim saisit (Mon espace → Mes débours) ; Ethan : notification « 1 débours à valider » → valide ; Karim le voit validé
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='karim';document.getElementById('htEspace').click();await new Promise(r=>setTimeout(r,250));const card=[...document.querySelectorAll('#eq-app .card')].find(c=>/Mes débours/.test(c.textContent));const r={card:!!card,dbg:card&&card.outerHTML.slice(0,400),sub:T.espace.state().S.sub};if(!card||!card.querySelector('[data-act=cmd][data-v="dbnew|"]'))return r;card.querySelector('[data-act=cmd][data-v="dbnew|"]').click();await new Promise(x=>setTimeout(x,200));r.modal=!!document.getElementById('db-montant');document.getElementById('db-montant').value='48.60';document.getElementById('db-nature').value='carburant';document.getElementById('db-com').value='Plein du Master';document.getElementById('db-ok').click();await new Promise(x=>setTimeout(x,300));
  const d=T.commandes.debours()[0];r.saved=d&&{montant:d.montant,nature:d.nature,etat:d.etat,key:d.key,site:d.site};r.mine=[...document.querySelectorAll('#eq-app .card')].find(c=>/Mes débours/.test(c.textContent)).textContent.replace(/\s+/g,' ');
  T.state.userId='ethan';document.getElementById('htHome').click();await new Promise(x=>setTimeout(x,300));r.notif=[...document.querySelectorAll('#eq-app .ac-notif .tx b')].map(b=>b.textContent).find(t=>/débours à valider/.test(t));r.allNotifs=[...document.querySelectorAll('#eq-app .ac-notif .tx b')].map(b=>b.textContent);r.todo=T.commandes.debours().map(d=>d.etat+'/'+d.key);const nn=[...document.querySelectorAll('#eq-app .ac-notif')].find(x=>/débours à valider/.test(x.textContent));if(!nn)return r;nn.click();await new Promise(x=>setTimeout(x,300));r.tab=(document.querySelector('#eq-app .eq-filtres .chip.active')||{}).textContent;
  document.querySelector('#eq-app [data-act=cmd][data-v^="dbok|"]').click();await new Promise(x=>setTimeout(x,250));const d2=T.commandes.debours()[0];r.valide={etat:d2.etat,par:d2.validePar};T.state.userId='karim';document.getElementById('htEspace').click();await new Promise(x=>setTimeout(x,250));r.mine2=[...document.querySelectorAll('#eq-app .card')].find(c=>/Mes débours/.test(c.textContent)).textContent.replace(/\s+/g,' ');return r;});
console.log('4) logs :',JSON.stringify(logs));console.log('4) débours :',JSON.stringify({...out,mine:(out.mine||'').slice(0,120),mine2:(out.mine2||'').slice(0,160)}));
C.c4=out.card&&out.modal&&out.saved&&out.saved.montant===48.6&&out.saved.nature==='carburant'&&out.saved.etat==='saisi'&&out.saved.key==='l:karim'&&out.saved.site==='demo_caen'&&/48,60 €/.test(out.mine)&&/Saisi/.test(out.mine)&&/1 débours à valider/.test(out.notif||'')&&/Débours/.test(out.tab||'')&&out.valide.etat==='valide'&&/Ethan/.test(out.valide.par)&&/Validé/.test(out.mine2);
// ── 5) production des équipes (Exploitation) + commerce : numéro proposé, récap CA, export CSV
out=await page.evaluate(async()=>{const T=window.TRACE;T.state.userId='ethan';document.getElementById('htExpl').click();await new Promise(r=>setTimeout(r,200));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Production des équipes/.test(x.textContent)).click();await new Promise(r=>setTimeout(r,250));const r={prod:(document.querySelector('#eq-app h2.vt')||{}).textContent};
  document.querySelector('#eq-app .ac-back').click();await new Promise(x=>setTimeout(x,150));[...document.querySelectorAll('#eq-app .ac-row')].find(x=>/Affaires · commerce/.test(x.textContent)).click();await new Promise(x=>setTimeout(x,200));document.querySelector('#eq-app [data-act=af][data-v="new|"]').click();await new Promise(x=>setTimeout(x,150));r.num=document.getElementById('afn-num').value;const sel=document.getElementById('afn-sect');sel.value='idf';sel.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(x=>setTimeout(x,100));r.numIdf=document.getElementById('afn-num').value;
  document.getElementById('afn-nom').value='Test récap';document.getElementById('afn-client').value='ENGIE';document.getElementById('afn-etat').value='en_cours';document.getElementById('afn-montant').value='100000';document.querySelector('#eq-app [data-act=af][data-v="create|"]').click();await new Promise(x=>setTimeout(x,250));document.querySelector('#eq-app [data-act=af][data-v="tab|fact"]').click();await new Promise(x=>setTimeout(x,150));const y=new Date().getFullYear();const inp=document.querySelector(`#eq-app [data-aff="${y}-05"]`);inp.value='25000';inp.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(x=>setTimeout(x,200));
  document.querySelector('#eq-app [data-act=af][data-v="back|"]').click();await new Promise(x=>setTimeout(x,150));document.querySelector('#eq-app [data-act=af][data-v="recap|"]').click();await new Promise(x=>setTimeout(x,200));const t=document.getElementById('eq-app').textContent.replace(/\s+/g,' ');r.recap=/CA mensuel/.test(t)&&/Île-de-France/.test(t)&&/25 k€/.test(t)&&/Restant à facturer/.test(t)&&/75 k€/.test(t);document.querySelector('#eq-app [data-act=af][data-v="csv|"]').click();return r;});
await wait(700);out.downloads=downloads.slice();
console.log('5) production équipes + commerce récap :',JSON.stringify(out));
const pre=String(ym.getFullYear()).slice(2)+String(ym.getMonth()+1).padStart(2,'0')+'-';
C.c5=/Productions de ton équipe/.test(out.prod||'')&&out.num==='O'+pre+'01'&&out.numIdf==='I'+pre+'01'&&out.recap&&out.downloads.some(f=>/^affaires_\d{4}\.csv$/.test(f));
const bad=Object.entries(C).filter(([k,v])=>!v).map(([k])=>k);console.log(bad.length?'RESULTAT: ECHEC '+bad.join(','):'RESULTAT: TOUT VERT');console.log(logs.length?logs:'[]');
await browser.close();
