import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:520,height:860},deviceScaleFactor:2});const page=await ctx.newPage();
page.on('dialog',d=>d.accept().catch(()=>{}));
await page.goto(BASE+'/traceur.html');await page.waitForTimeout(500);
await page.evaluate(()=>{localStorage.clear();});await page.reload();await page.waitForTimeout(500);
await page.evaluate(()=>{const S=window.MAQ.state;S.supplier='RENALIA';S.lines=[{id:'L1',name:'Feeder',dn:100,bar:12,pts:[[10,50],[80,50]],specials:[],parent:null}];S.seq=2;window.MAQ.setMode('select');window.MAQ.rebuild();});
await page.click('#bSave');await page.waitForTimeout(200);await page.fill('#svName','Soudure supplémentaire');await page.click('#svOk');await page.waitForTimeout(600);
await page.click('#svGo');await page.waitForTimeout(1200);await page.selectOption('#roleSel','ethan');await page.waitForTimeout(300);
await page.evaluate(()=>{const T=window.TRACE;const L1=Object.values(T.lines)[0];const e=L1.cond.A.els.find((x,q)=>x.kind==='pipe'&&x.len>8);T.centerOn(e.axis[0][0].x+5,e.axis[0][0].y+.2,40);});await page.waitForTimeout(400);
await page.screenshot({path:'/tmp/shot_extra0.png'});
await page.evaluate(()=>document.querySelector('#btnExtraWeld').click());await page.waitForTimeout(300);
await page.screenshot({path:'/tmp/shot_extra1.png'});
const pt=await page.evaluate(()=>{const T=window.TRACE;const L1=Object.values(T.lines)[0];const e=L1.cond.A.els.find((x,q)=>x.kind==='pipe'&&x.len>8);const pl=e.axis[0];const t=5/e.len;const wx=pl[0].x+(pl[1].x-pl[0].x)*t,wy=pl[0].y+(pl[1].y-pl[0].y)*t;const v=T.state.view;const r=document.querySelector('#canvas').getBoundingClientRect();return {x:r.left+wx*v.k+v.tx,y:r.top+wy*v.k+v.ty};});
await page.mouse.move(pt.x,pt.y);await page.mouse.down();await page.waitForTimeout(40);await page.mouse.up();await page.waitForTimeout(700);
await page.screenshot({path:'/tmp/shot_extra2.png'});
await page.evaluate(()=>window.TRACE.closeSheet());await page.waitForTimeout(400);
await page.screenshot({path:'/tmp/shot_extra3.png'});
console.log('ok');await browser.close();
