import { chromium } from 'playwright';
const BASE=process.env.BASE||'http://localhost:8765';
const browser=await chromium.launch({headless:true, executablePath: process.env.CHROMIUM_PATH||undefined});
const ctx=await browser.newContext({viewport:{width:520,height:900},deviceScaleFactor:2,geolocation:{latitude:48.1173,longitude:-1.6778,accuracy:12},permissions:['geolocation']});const page=await ctx.newPage();
page.on('dialog',d=>d.accept().catch(()=>{}));
await page.goto(BASE+'/traceur.html');await page.waitForTimeout(500);
await page.evaluate(()=>{localStorage.clear();localStorage.setItem('trace:next',JSON.stringify({pointage:1,profil:1,tabs:1}));});await page.reload();await page.waitForTimeout(500);
await page.evaluate(()=>{const S=window.MAQ.state;S.supplier='RENALIA';S.lines=[{id:'L1',name:'Feeder',dn:100,bar:12,pts:[[10,50],[130,50]],specials:[],parent:null}];S.seq=2;window.MAQ.setMode('select');window.MAQ.rebuild();});
await page.click('#bSave');await page.waitForTimeout(200);await page.fill('#svName','SCR démo');await page.click('#svOk');await page.waitForTimeout(600);
await page.click('#svGo');await page.waitForTimeout(1500);await page.selectOption('#roleSel','karim');await page.waitForTimeout(300);
await page.evaluate(()=>document.querySelector('#tabbar [data-tab="pointage"]').click());await page.waitForTimeout(400);
await page.evaluate(()=>document.querySelector('#pointage [data-pt="start"]').click());await page.waitForTimeout(900);
await page.evaluate(()=>document.querySelector('#pointage [data-pt="pause"]').click());await page.waitForTimeout(200);
await page.evaluate(()=>document.querySelector('#pointage [data-pt="resume"]').click());await page.waitForTimeout(200);
await page.evaluate(()=>{const day=Object.keys(window.TRACE.net.pointage.days)[0];const e=window.TRACE.net.pointage.days[day]['Karim B.'];const hh=(h,m)=>new Date(day+'T'+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':00').toISOString();e.events[0].at=hh(7,30);e.events[1].at=hh(12,0);e.events[2].at=hh(13,5);
  const T=window.TRACE;const L=Object.values(T.lines)[0];const now=new Date().toISOString();[1,2,3].forEach(i=>{const j=L.cond.A.joints[i];j.steps={1:{done:true,by:'Karim B.',at:now,photos:[],visuel:true}};j.status='soudee';});T.renderAll();});await page.waitForTimeout(400);
await page.screenshot({path:'/tmp/scr_1.png'});
await page.selectOption('#roleSel','ethan');await page.waitForTimeout(400);await page.evaluate(()=>{const v=document.querySelector('#view-pointage');if(v)v.scrollTop=520;});await page.waitForTimeout(200);
await page.screenshot({path:'/tmp/scr_2.png'});
await page.selectOption('#roleSel','karim');await page.waitForTimeout(300);
await page.evaluate(()=>document.querySelector('#tabbar [data-tab="profil"]').click());await page.waitForTimeout(400);
await page.screenshot({path:'/tmp/scr_3.png'});
console.log('ok');await browser.close();
